"use strict";

// Biblioteca-base de exercícios de futebol de formação (sub-7 a sub-10).
// Metodologia: jogo como professor, jogos reduzidos, muitos toques, sessões curtas.
// Cada item tem uma `chave` estável para nunca duplicar ao carregar mais que uma vez.
const EXERCICIOS_BASE = [
  // ---------- Coordenação / motricidade ----------
  {
    chave: "escada-coordenacao",
    titulo: "Escada de coordenação",
    objetivo: "Agilidade, ritmo e coordenação de pés",
    categoria: "Coordenação / motricidade",
    n_jogadores_min: 4, n_jogadores_max: 14, duracao_min: 8,
    escaloes: ["sub-7", "sub-8", "sub-9", "sub-10"],
    material: "1–2 escadas de coordenação (ou aros/linhas no chão)",
    descricao: "Filas a passar pela escada com padrões simples: um pé por espaço, dois pés por espaço, dentro-fora. Depois de sair, pequena corrida até a um cone e volta a trás da fila. Progressão: acabar a passagem com uma condução de bola até à baliza.",
  },
  {
    chave: "circuito-saltos",
    titulo: "Circuito de saltos e corrida",
    objetivo: "Impulsão, equilíbrio e mudança de apoio",
    categoria: "Coordenação / motricidade",
    n_jogadores_min: 4, n_jogadores_max: 16, duracao_min: 8,
    escaloes: ["sub-7", "sub-8"],
    material: "Aros, cones baixos ou barreiras pequenas",
    descricao: "Percurso com estações: saltar a pés juntos dentro dos aros, passar por cima de barreiras pequenas, correr em zig-zag entre cones. Fazer como estafeta em duas equipas para dar ritmo e diversão. Sem foco em velocidade máxima — foco na execução limpa.",
  },

  // ---------- Domínio e condução de bola ----------
  {
    chave: "cada-um-sua-bola",
    titulo: "Cada um com a sua bola",
    objetivo: "Muitos toques, domínio e uso das duas superfícies",
    categoria: "Domínio e condução de bola",
    n_jogadores_min: 4, n_jogadores_max: 16, duracao_min: 8,
    escaloes: ["sub-7", "sub-8", "sub-9", "sub-10"],
    material: "Uma bola por jogador, cones a delimitar a área",
    descricao: "Todos a conduzir dentro de uma área, sem chocar nem sair. O treinador dá ordens: parar a bola com a sola, mudar de pé, acelerar, travar. Muitos toques por minuto. É o exercício ideal para começar a sessão.",
  },
  {
    chave: "slalom-cones",
    titulo: "Slalom entre cones",
    objetivo: "Condução com toques curtos e mudança de direção",
    categoria: "Domínio e condução de bola",
    n_jogadores_min: 3, n_jogadores_max: 12, duracao_min: 8,
    escaloes: ["sub-7", "sub-8", "sub-9", "sub-10"],
    material: "Cones em linha (60–80 cm de distância), uma bola por fila",
    descricao: "Conduzir a bola em zig-zag por entre os cones com toques curtos, usando as duas superfícies do pé. No fim, condução rápida de volta pela lateral. Evitar filas grandes — no máximo 3 por percurso para haver muitas repetições.",
  },
  {
    chave: "conducao-mudancas",
    titulo: "Condução com mudanças de direção",
    objetivo: "Fintas simples e proteção de bola",
    categoria: "Domínio e condução de bola",
    n_jogadores_min: 4, n_jogadores_max: 12, duracao_min: 8,
    escaloes: ["sub-9", "sub-10"],
    material: "Cones a marcar portas/mudanças, uma bola por jogador",
    descricao: "Conduzir livremente e, ao chegar a um cone, executar uma mudança de direção (corte com o interior, sola, ou finta simples) e sair para outro espaço. Introduzir 1–2 gestos técnicos de cada vez e dar-lhes nome para as crianças pedirem.",
  },

  // ---------- Passe e receção ----------
  {
    chave: "passe-a-pares",
    titulo: "Passe a pares",
    objetivo: "Passe rasteiro preciso e primeira receção",
    categoria: "Passe e receção",
    n_jogadores_min: 4, n_jogadores_max: 16, duracao_min: 7,
    escaloes: ["sub-7", "sub-8", "sub-9"],
    material: "Uma bola por par, dois cones por par",
    descricao: "A pares, frente a frente, a passar e receber entre dois cones (porta). Contar quantos passes seguidos sem falhar. Progressão: receber orientado para o lado, ou passar sempre com o pé menos forte.",
  },
  {
    chave: "quadrado-de-passe",
    titulo: "Quadrado de passe",
    objetivo: "Passar e apoiar, orientar a receção",
    categoria: "Passe e receção",
    n_jogadores_min: 4, n_jogadores_max: 12, duracao_min: 8,
    escaloes: ["sub-8", "sub-9", "sub-10"],
    material: "4 cones em quadrado (5–8 m), uma bola por grupo",
    descricao: "Jogadores nos cantos de um quadrado. Passar para o colega seguinte e seguir a bola (passa-e-vai) ou passar e ficar. Trabalhar receção orientada para o próximo passe. Fazer nos dois sentidos.",
  },
  {
    chave: "rondo-4x1",
    titulo: "Rondo 4x1",
    objetivo: "Manter a posse, timing do passe, pressão",
    categoria: "Passe e receção",
    n_jogadores_min: 5, n_jogadores_max: 10, duracao_min: 8,
    escaloes: ["sub-9", "sub-10"],
    material: "Cones a delimitar o círculo/quadrado, uma bola",
    descricao: "Quatro por fora a manter a posse, um no meio a tentar recuperar. Quem perde a bola (ou o que a deu mal) vai para o meio. Espaço pequeno para sub-9, um pouco maior para começar. Incentivar passe rasteiro e olhar antes de receber.",
  },
  {
    chave: "passe-em-losango",
    titulo: "Passe em movimento (losango)",
    objetivo: "Passe e apoio com deslocamento",
    categoria: "Passe e receção",
    n_jogadores_min: 4, n_jogadores_max: 12, duracao_min: 8,
    escaloes: ["sub-10"],
    material: "4 cones em losango, uma bola por grupo",
    descricao: "Circulação de bola pelas estações do losango com o jogador a seguir o seu passe para a estação seguinte. Introduz a ideia de dar e receber em movimento. Manter grupos pequenos para muitas repetições.",
  },

  // ---------- Remate / finalização ----------
  {
    chave: "remate-apos-conducao",
    titulo: "Remate após condução",
    objetivo: "Conduzir e finalizar à baliza",
    categoria: "Remate / finalização",
    n_jogadores_min: 3, n_jogadores_max: 12, duracao_min: 8,
    escaloes: ["sub-7", "sub-8", "sub-9", "sub-10"],
    material: "Balizas pequenas ou uma baliza com GR, cones, várias bolas",
    descricao: "Conduzir de um cone até à zona de remate e finalizar. Duas filas em ângulos diferentes para dar variedade. Muitas bolas para não haver esperas. Celebrar os golos — a finalização deve ser divertida.",
  },
  {
    chave: "1x1-com-gr",
    titulo: "1x1 com guarda-redes",
    objetivo: "Decisão de finalização em ataque ao GR",
    categoria: "Remate / finalização",
    n_jogadores_min: 3, n_jogadores_max: 10, duracao_min: 8,
    escaloes: ["sub-8", "sub-9", "sub-10"],
    material: "Baliza com GR, várias bolas, cones de partida",
    descricao: "O jogador recebe/parte de um cone e vai para o 1x1 com o guarda-redes: rematar cedo ou driblar. Rodar o GR. Trabalha a decisão simples de finalização. Para sub-8 pode ser sem GR, só baliza.",
  },
  {
    chave: "concurso-de-golos",
    titulo: "Concurso de golos",
    objetivo: "Remate colocado e diversão competitiva",
    categoria: "Remate / finalização",
    n_jogadores_min: 4, n_jogadores_max: 12, duracao_min: 7,
    escaloes: ["sub-7", "sub-8", "sub-9"],
    material: "Baliza, várias bolas, cones a marcar distâncias",
    descricao: "Estações de remate a distâncias diferentes; cada golo vale pontos por equipa. Alvos nas balizas (zonas) para trabalhar colocação. Ambiente de jogo/competição saudável, sem pressão sobre quem falha.",
  },

  // ---------- Jogos reduzidos (SSG) ----------
  {
    chave: "1x1-quatro-balizas",
    titulo: "1x1 em quatro balizas",
    objetivo: "Duelo individual, condução e finalização",
    categoria: "Jogos reduzidos (SSG)",
    n_jogadores_min: 2, n_jogadores_max: 8, duracao_min: 8,
    escaloes: ["sub-7", "sub-8", "sub-9"],
    material: "4 mini-balizas (cones), bolas, coletes",
    descricao: "Campo pequeno com duas mini-balizas de cada lado. No 1x1, o jogador pode marcar em qualquer das duas balizas adversárias, o que premeia procurar o espaço livre. Jogos curtos (30–45 s) e muitas trocas.",
  },
  {
    chave: "2x2-com-apoios",
    titulo: "2x2 com apoios",
    objetivo: "Ajuda ao portador, passe e desmarcação",
    categoria: "Jogos reduzidos (SSG)",
    n_jogadores_min: 4, n_jogadores_max: 10, duracao_min: 10,
    escaloes: ["sub-8", "sub-9", "sub-10"],
    material: "2 mini-balizas, coletes, bolas",
    descricao: "2x2 em campo reduzido com jogadores de apoio nas laterais (jokers que jogam sempre com quem tem a bola). Facilita manter a posse e cria situações de superioridade. Rodar os apoios.",
  },
  {
    chave: "3x3-campo-reduzido",
    titulo: "3x3 em campo reduzido",
    objetivo: "Jogar juntos, ocupar espaços, transições",
    categoria: "Jogos reduzidos (SSG)",
    n_jogadores_min: 6, n_jogadores_max: 12, duracao_min: 10,
    escaloes: ["sub-8", "sub-9", "sub-10"],
    material: "2 balizas pequenas, coletes, bolas",
    descricao: "Jogo livre 3x3. Muitos contactos com a bola e decisões constantes. Deixar jogar; intervir pouco, com perguntas ('onde está o espaço?'). Ideal como núcleo da sessão.",
  },
  {
    chave: "4x4-balizas-laterais",
    titulo: "4x4 com balizas laterais",
    objetivo: "Mudar o jogo, procurar o lado livre",
    categoria: "Jogos reduzidos (SSG)",
    n_jogadores_min: 8, n_jogadores_max: 12, duracao_min: 10,
    escaloes: ["sub-9", "sub-10"],
    material: "4 mini-balizas (duas por linha de fundo), coletes, bolas",
    descricao: "4x4 com duas mini-balizas em cada linha de fundo. Marca-se pontos ao atacar a baliza menos protegida, incentivando a mudar o jogo para o lado livre. Boa introdução à noção de amplitude.",
  },

  // ---------- Jogo final ----------
  {
    chave: "jogo-final-5x5",
    titulo: "Jogo final 5v5",
    objetivo: "Transferir o treino para o jogo real",
    categoria: "Jogo final",
    n_jogadores_min: 6, n_jogadores_max: 12, duracao_min: 12,
    escaloes: ["sub-8", "sub-9", "sub-10"],
    material: "Balizas, coletes, bolas",
    descricao: "Jogo livre a fechar a sessão, formato próximo do de competição. Poucas regras, muito jogo. O treinador observa e celebra as boas ações. Equipas equilibradas e, se preciso, rodar para todos jogarem.",
  },
  {
    chave: "jogo-balizas-pequenas",
    titulo: "Jogo com balizas pequenas (sem GR)",
    objetivo: "Muitos golos, condução e remate em jogo",
    categoria: "Jogo final",
    n_jogadores_min: 6, n_jogadores_max: 12, duracao_min: 10,
    escaloes: ["sub-7", "sub-8"],
    material: "Mini-balizas ou cones, coletes, bolas",
    descricao: "Jogo reduzido sem guarda-redes, com balizas pequenas. Baixa a pressão, aumenta os golos e mantém as crianças perto da bola. Perfeito para os escalões mais novos terminarem a rir.",
  },

  // ---------- Jogos lúdicos ----------
  {
    chave: "tubaroes-e-peixes",
    titulo: "Tubarões e peixinhos",
    objetivo: "Condução, proteção de bola e fuga",
    categoria: "Jogos lúdicos",
    n_jogadores_min: 6, n_jogadores_max: 16, duracao_min: 7,
    escaloes: ["sub-7", "sub-8"],
    material: "Bolas para os peixinhos, coletes para os tubarões, área",
    descricao: "Os 'peixinhos' conduzem a bola de uma margem à outra sem que os 'tubarões' (sem bola) lhes tirem a bola para fora. Quem perde a bola vira tubarão. Trabalha condução com cabeça levantada e proteção.",
  },
  {
    chave: "toca-do-coelho",
    titulo: "Toca do coelho",
    objetivo: "Reação, orientação e primeiro toque",
    categoria: "Jogos lúdicos",
    n_jogadores_min: 6, n_jogadores_max: 16, duracao_min: 6,
    escaloes: ["sub-7", "sub-8"],
    material: "Aros (as tocas), bolas, área",
    descricao: "Cada coelho tem a sua toca (aro) com a bola parada. Ao sinal, saem a passear/conduzir; a outro sinal, correm a proteger uma toca livre. Tira-se uma toca de cada vez para dar emoção. Muito movimento e boa disposição.",
  },

  // ============================================================
  // Manual Completo de Exercícios: Futebol Infantil (do treinador)
  // Dinâmicas lúdicas, sem filas e de alta participação.
  // ============================================================

  // --- 1. Aquecimento e Reação ---
  {
    chave: "m-rei-da-selva",
    titulo: "O Rei da Selva",
    objetivo: "Escuta ativa, reação e coordenação com bola",
    categoria: "Jogos lúdicos",
    n_jogadores_min: 4, n_jogadores_max: 16, duracao_min: 6,
    escaloes: ["sub-7", "sub-8"],
    material: "Uma bola por criança, cones a demarcar o quadrado",
    descricao: "Cada criança conduz a sua bola livremente num quadrado demarcado. Ao comando do treinador (ex: 'Macaco', 'Sapo', 'Guepardo'), as crianças realizam ações físicas imediatas associadas ao animal, treinando a escuta ativa e a coordenação.",
  },
  {
    chave: "m-ladrao-de-bolas",
    titulo: "Ladrão de Bolas",
    objetivo: "Proteção de bola e condução sob pressão",
    categoria: "Jogos lúdicos",
    n_jogadores_min: 5, n_jogadores_max: 16, duracao_min: 6,
    escaloes: ["sub-7", "sub-8", "sub-9"],
    material: "Bolas para todos menos os ladrões, área delimitada",
    descricao: "Duas crianças começam sem bola como os 'ladrões'. As restantes tentam proteger a sua bola dentro do espaço delimitado. Se um ladrão roubar uma bola, quem a perdeu passa a ser o novo ladrão.",
  },
  {
    chave: "m-esconderijo-cores",
    titulo: "O Esconderijo Cor de Rosa/Azul",
    objetivo: "Reação a estímulos e condução dirigida",
    categoria: "Domínio e condução de bola",
    n_jogadores_min: 4, n_jogadores_max: 16, duracao_min: 7,
    escaloes: ["sub-7", "sub-8"],
    material: "Cones de várias cores, uma bola por criança",
    descricao: "Espalhe cones de várias cores pelo campo. As crianças conduzem livremente. Ao sinal do treinador gritando uma cor, todos devem conduzir rapidamente a bola para o cone mais próximo da respetiva cor.",
  },

  // --- 2. Coordenação e Agilidade (Sem Bola) ---
  {
    chave: "m-pega-pega-sombras",
    titulo: "Pega-Pega das Sombras",
    objetivo: "Agilidade, fintas de direção e imitação",
    categoria: "Coordenação / motricidade",
    n_jogadores_min: 4, n_jogadores_max: 16, duracao_min: 6,
    escaloes: ["sub-8", "sub-9", "sub-10"],
    material: "Nenhum (área delimitada)",
    descricao: "Em duplas, um jogador corre e realiza fintas de direção aleatórias enquanto o colega tenta imitá-lo perfeitamente como uma sombra. Inverter os papéis após 1 minuto.",
  },
  {
    chave: "m-apanhada-coletes",
    titulo: "Apanhada dos Coletes",
    objetivo: "Agilidade, mudança de direção e diversão",
    categoria: "Jogos lúdicos",
    n_jogadores_min: 6, n_jogadores_max: 16, duracao_min: 6,
    escaloes: ["sub-7", "sub-8"],
    material: "Um colete por criança (a 'cauda'), área delimitada",
    descricao: "Cada criança prende um colete na parte de trás dos calções, simulando uma cauda. O objetivo é tentar roubar o maior número possível de caudas dos colegas enquanto protege a sua própria.",
  },

  // --- 3. Condução e Domínio de Bola ---
  {
    chave: "m-transito",
    titulo: "O Trânsito",
    objetivo: "Controlo de ritmo e paragem da bola",
    categoria: "Domínio e condução de bola",
    n_jogadores_min: 4, n_jogadores_max: 16, duracao_min: 7,
    escaloes: ["sub-7", "sub-8"],
    material: "Uma bola por criança",
    descricao: "As crianças reagem a sinais visuais ou auditivos do treinador. Sinal Verde: condução rápida. Sinal Amarelo: condução lenta e controlada. Sinal Vermelho: parar a bola imediatamente usando a sola do pé.",
  },
  {
    chave: "m-corrida-portoes",
    titulo: "Corrida dos Portões",
    objetivo: "Condução com cabeça levantada e leitura do espaço",
    categoria: "Domínio e condução de bola",
    n_jogadores_min: 4, n_jogadores_max: 16, duracao_min: 7,
    escaloes: ["sub-7", "sub-8", "sub-9", "sub-10"],
    material: "Muitos mini-portões de cones, uma bola por jogador",
    descricao: "Espalhe mini-portões de cones pelo campo. No espaço de 1 minuto, cada jogador tenta atravessar a conduzir o maior número de portões diferentes que conseguir, sem repetir o mesmo de forma seguida.",
  },
  {
    chave: "m-labirinto-cones",
    titulo: "Labirinto de Cones",
    objetivo: "Condução em ziguezague, sem filas de espera",
    categoria: "Domínio e condução de bola",
    n_jogadores_min: 4, n_jogadores_max: 16, duracao_min: 7,
    escaloes: ["sub-7", "sub-8", "sub-9"],
    material: "Vários circuitos paralelos de cones pequenos, bolas",
    descricao: "Circuitos curtos montados em paralelo com pequenos cones em ziguezague. Garante que várias crianças realizem o trajeto ao mesmo tempo, eliminando filas de espera.",
  },

  // --- 4. Passe e Trabalho de Equipa ---
  {
    chave: "m-cacadores-cones",
    titulo: "Caçadores de Cones",
    objetivo: "Passe rasteiro preciso e recuperação rápida",
    categoria: "Passe e receção",
    n_jogadores_min: 6, n_jogadores_max: 16, duracao_min: 8,
    escaloes: ["sub-8", "sub-9", "sub-10"],
    material: "Vários cones ao centro, bolas para o grupo",
    descricao: "As crianças formam um grande círculo ao redor de vários cones posicionados no centro. O objetivo é derrubar os cones centrais através de passes rasteiros e precisos, recuperando as bolas rapidamente.",
  },
  {
    chave: "m-espaco-secreto",
    titulo: "O Espaço Secreto",
    objetivo: "Passar e apoiar, ocupar o espaço livre",
    categoria: "Passe e receção",
    n_jogadores_min: 4, n_jogadores_max: 12, duracao_min: 8,
    escaloes: ["sub-9", "sub-10"],
    material: "Uma bola por dupla, cones a marcar zonas/quadrados",
    descricao: "Em duplas, os jogadores trocam passes dentro de um espaço delimitado. Após realizar um passe, é obrigatório correr imediatamente para ocupar uma zona livre ou um quadrado vazio no campo.",
  },

  // --- 5. Finalização e Remate ---
  {
    chave: "m-batalha-remates",
    titulo: "Batalha de Remates",
    objetivo: "Timing do remate e defesa da própria baliza",
    categoria: "Remate / finalização",
    n_jogadores_min: 2, n_jogadores_max: 10, duracao_min: 8,
    escaloes: ["sub-8", "sub-9", "sub-10"],
    material: "Duas balizas pequenas frente a frente, bolas",
    descricao: "Confronto direto de 1x1 à distância. Duas balizas pequenas frente a frente, onde cada jogador tenta chutar no momento certo e defender a sua própria baliza sem sair da zona permitida.",
  },
  {
    chave: "m-ataque-surpresa",
    titulo: "O Ataque Surpresa",
    objetivo: "Domínio em velocidade e finalização",
    categoria: "Remate / finalização",
    n_jogadores_min: 3, n_jogadores_max: 12, duracao_min: 8,
    escaloes: ["sub-8", "sub-9", "sub-10"],
    material: "Baliza (com ou sem GR), várias bolas",
    descricao: "O treinador lança uma bola em profundidade de forma aleatória. A criança arranca em velocidade, domina a bola em movimento e finaliza à baliza antes que a bola ultrapasse a linha de fundo.",
  },
  {
    chave: "m-guarda-redes-gigante",
    titulo: "O Guarda-Redes Gigante",
    objetivo: "Pontaria e colocação do remate nos cantos",
    categoria: "Remate / finalização",
    n_jogadores_min: 3, n_jogadores_max: 12, duracao_min: 7,
    escaloes: ["sub-7", "sub-8", "sub-9"],
    material: "Baliza, um obstáculo/cone grande ao centro, bolas",
    descricao: "Um obstáculo ou cone grande é colocado exatamente no meio da baliza. Os remates direcionados para os cantos valem pontuação a dobrar, estimulando a pontaria e a precisão.",
  },

  // --- 6. Jogos Reduzidos ---
  {
    chave: "m-jogo-4-balizas",
    titulo: "Jogo das 4 Balizas",
    objetivo: "Visão de jogo, inversão e procura do espaço vazio",
    categoria: "Jogos reduzidos (SSG)",
    n_jogadores_min: 6, n_jogadores_max: 12, duracao_min: 10,
    escaloes: ["sub-8", "sub-9", "sub-10"],
    material: "4 balizas pequenas, coletes, bolas",
    descricao: "Partida normal de futebol reduzido (3x3 ou 4x4), mas cada equipa defende duas balizas e ataca outras duas. Estimula a visão de jogo, inversão de jogo e procura pelo espaço vazio.",
  },
  {
    chave: "m-jogo-curinga",
    titulo: "Jogo com Curinga (Coringa)",
    objetivo: "Superioridade numérica e circulação de bola",
    categoria: "Jogos reduzidos (SSG)",
    n_jogadores_min: 5, n_jogadores_max: 12, duracao_min: 10,
    escaloes: ["sub-8", "sub-9", "sub-10"],
    material: "2 balizas, coletes, bolas",
    descricao: "Um jogador neutro (ou o próprio treinador) joga sempre a favor da equipa que detém a posse de bola. Isto cria cenários de superioridade numérica, facilitando a troca de passes e a criação de golos.",
  },

  // ---------- Poucos jogadores (1 a 3): grupos pequenos, sem inventar formatos ----------
  {
    chave: "p-circuito-coordenacao",
    titulo: "Circuito de coordenação individual",
    objetivo: "Coordenação, agilidade e ritmo, cada um ao seu tempo",
    categoria: "Coordenação / motricidade",
    n_jogadores_min: 1, n_jogadores_max: 8, duracao_min: 10,
    escaloes: ["sub-7", "sub-8", "sub-9", "sub-10"],
    material: "Escada ou aros, 4-6 cones",
    descricao: "Circuito individual em vaivém: passar a escada/aros com um padrão de pés, saltos a pés juntos entre cones, mudança de direção e corrida final. Cada jogador faz o seu percurso e volta ao início. Progressão: terminar com condução de bola até um cone.",
  },
  {
    chave: "p-duelo-reacao",
    titulo: "Duelo de reação a pares",
    objetivo: "Velocidade de reação e arranque",
    categoria: "Coordenação / motricidade",
    n_jogadores_min: 2, n_jogadores_max: 8, duracao_min: 8,
    escaloes: ["sub-8", "sub-9", "sub-10"],
    material: "Cones de 2 cores, 1 bola",
    descricao: "Dois jogadores lado a lado. Ao sinal do treinador (cor ou número), correm a tocar no cone certo e voltam. Variante com bola: o primeiro a chegar conduz até uma linha. Trabalha atenção e explosão sem precisar de muitos jogadores.",
  },
  {
    chave: "p-slalom-conducao",
    titulo: "Slalom de condução",
    objetivo: "Condução de bola com as duas superfícies e mudança de direção",
    categoria: "Domínio e condução de bola",
    n_jogadores_min: 1, n_jogadores_max: 8, duracao_min: 10,
    escaloes: ["sub-7", "sub-8", "sub-9", "sub-10"],
    material: "6-8 cones, 1 bola por jogador",
    descricao: "Fila de cones em slalom. Conduzir por dentro dos cones com pé direito, depois esquerdo, depois só sola. Cada jogador tem a sua bola e o seu ritmo. Progressão: cronometrar a passagem ou acabar com remate.",
  },
  {
    chave: "p-conducao-finta-1v1",
    titulo: "Condução e finta 1v1",
    objetivo: "Conduzir em drible e ultrapassar um adversário",
    categoria: "Domínio e condução de bola",
    n_jogadores_min: 2, n_jogadores_max: 6, duracao_min: 10,
    escaloes: ["sub-8", "sub-9", "sub-10"],
    material: "Cones para 2 linhas, 1 bola",
    descricao: "Um jogador conduz e tenta passar o outro até à linha de fundo; o defesa começa passivo (só acompanha) e depois ativo. Trocam de papel a cada tentativa. 1v1 real, chega com 2 jogadores.",
  },
  {
    chave: "p-passe-pares-movimento",
    titulo: "Passe a pares em movimento",
    objetivo: "Passe e receção orientada em deslocamento",
    categoria: "Passe e receção",
    n_jogadores_min: 2, n_jogadores_max: 8, duracao_min: 10,
    escaloes: ["sub-7", "sub-8", "sub-9", "sub-10"],
    material: "1 bola por par, 2 cones",
    descricao: "Dois jogadores passam a bola entre si, primeiro parados, depois a andar e a correr lado a lado ao longo do campo. Variar o pé, exigir receção orientada e passe de primeira. Base do jogo coletivo, feita a pares.",
  },
  {
    chave: "p-passe-triangulo",
    titulo: "Passe em triângulo",
    objetivo: "Passe, apoio e movimento após passe",
    categoria: "Passe e receção",
    n_jogadores_min: 3, n_jogadores_max: 6, duracao_min: 10,
    escaloes: ["sub-8", "sub-9", "sub-10"],
    material: "3 cones em triângulo, 1 bola",
    descricao: "Três cones formam um triângulo. Passa e segue para a posição seguinte (passe e vai). Trabalha receção orientada e o hábito de se movimentar depois de passar. Exatamente 3 jogadores.",
  },
  {
    chave: "p-passe-parede",
    titulo: "Passe e controlo na parede",
    objetivo: "Qualidade de passe e controlo com várias superfícies",
    categoria: "Passe e receção",
    n_jogadores_min: 1, n_jogadores_max: 6, duracao_min: 8,
    escaloes: ["sub-7", "sub-8", "sub-9", "sub-10"],
    material: "Uma parede ou baliza rebatível, 1 bola",
    descricao: "Passar a bola contra a parede e controlar o ressalto, trabalhando interior, exterior e sola. Aumentar a distância e exigir controlo em movimento. Ideal quando há só 1 ou 2 jogadores.",
  },
  {
    chave: "p-finalizacao-pares",
    titulo: "Finalização a pares",
    objetivo: "Remate após passe, com servidor",
    categoria: "Remate / finalização",
    n_jogadores_min: 2, n_jogadores_max: 6, duracao_min: 12,
    escaloes: ["sub-8", "sub-9", "sub-10"],
    material: "1 baliza (ou mini-baliza), cones, bolas",
    descricao: "Um jogador serve (passe raso ou por baixo) e o outro remata à baliza à primeira ou após um toque. Trocam de função a cada série. Se houver um terceiro, faz de guarda-redes. Realista com 2 jogadores.",
  },
  {
    chave: "p-1v1-mini-balizas",
    titulo: "1v1 para mini-balizas",
    objetivo: "Duelo ofensivo/defensivo e finalização",
    categoria: "Jogos reduzidos (SSG)",
    n_jogadores_min: 2, n_jogadores_max: 6, duracao_min: 12,
    escaloes: ["sub-7", "sub-8", "sub-9", "sub-10"],
    material: "2-4 mini-balizas (ou cones), coletes, bolas",
    descricao: "Campo pequeno, cada jogador ataca uma ou duas mini-balizas e defende a(s) sua(s). Jogo direto 1 contra 1. Chega com 2 jogadores; com 3, um descansa/serve bolas e roda.",
  },
  {
    chave: "p-2v1-superioridade",
    titulo: "2v1 para finalizar",
    objetivo: "Aproveitar superioridade numérica e decidir passe ou remate",
    categoria: "Jogos reduzidos (SSG)",
    n_jogadores_min: 3, n_jogadores_max: 6, duracao_min: 12,
    escaloes: ["sub-8", "sub-9", "sub-10"],
    material: "1 mini-baliza ou baliza, coletes, bolas",
    descricao: "Dois jogadores atacam um defesa para finalizar numa baliza. Quem perde a bola passa a defesa na jogada seguinte (rotação). Ensina a decidir entre passar e rematar. Exatamente 3 jogadores.",
  },
  {
    chave: "p-jogo-1v1-reduzido",
    titulo: "Jogo 1v1 em campo reduzido",
    objetivo: "Competir 1 contra 1 com baliza",
    categoria: "Jogo final",
    n_jogadores_min: 2, n_jogadores_max: 6, duracao_min: 12,
    escaloes: ["sub-7", "sub-8", "sub-9", "sub-10"],
    material: "2 balizas pequenas, bolas",
    descricao: "Cada jogador defende uma baliza pequena e ataca a do adversário, num campo curto. Joga-se a sério, com golos. É o 'jogo' da sessão quando há poucos jogadores. Rodar adversários se houver um terceiro.",
  },
  {
    chave: "p-jogo-2v1-rotacao",
    titulo: "Jogo 2v1 com rotação",
    objetivo: "Jogo contínuo com mudança constante de papéis",
    categoria: "Jogo final",
    n_jogadores_min: 3, n_jogadores_max: 6, duracao_min: 12,
    escaloes: ["sub-8", "sub-9", "sub-10"],
    material: "1-2 balizas pequenas, bolas",
    descricao: "Dois atacam uma baliza contra um defesa; quem perder a bola ou sofrer golo vai para a defesa e entra outro a atacar. Jogo dinâmico e competitivo com apenas 3 jogadores.",
  },
  {
    chave: "p-rouba-bola",
    titulo: "Rouba-bola (duelo de condução)",
    objetivo: "Proteção de bola e drible sob pressão, de forma lúdica",
    categoria: "Jogos lúdicos",
    n_jogadores_min: 2, n_jogadores_max: 8, duracao_min: 8,
    escaloes: ["sub-7", "sub-8", "sub-9"],
    material: "1 bola por jogador, cones a delimitar a zona",
    descricao: "Numa zona pequena, cada jogador conduz a sua bola e tenta pontapear para fora a bola dos outros, protegendo a sua ao mesmo tempo. Quem fica sem bola faz um desafio (ex.: 5 embaixadinhas) e volta. Diverte e trabalha condução com 2 ou mais.",
  },
  {
    chave: "p-espelho-pares",
    titulo: "Espelho a pares",
    objetivo: "Controlo corporal e condução imitando o par",
    categoria: "Jogos lúdicos",
    n_jogadores_min: 2, n_jogadores_max: 8, duracao_min: 6,
    escaloes: ["sub-7", "sub-8", "sub-9"],
    material: "1 bola por jogador (opcional)",
    descricao: "Um jogador lidera com movimentos (correr, parar, mudar de direção, com ou sem bola) e o par imita-o como um espelho. Ao fim de um tempo trocam. Bom como ativação ou retorno à calma, a pares.",
  },
];
