"use strict";
// Coach-entered match video moments; no automatic recognition or inference.
(function(root){
 const SCHEMA='vision-match-evidence@1';
 const CATEGORIES={goal:'Golo',goal_against:'Golo sofrido',chance:'Oportunidade',loss:'Perda',recovery:'Recuperação',attack:'Organização ofensiva',defense:'Organização defensiva',transition:'Transição',set_piece:'Bola parada',individual:'Individual',other:'Outro'};
 const STATISTICS={'goals.for':'Golos marcados','goals.against':'Golos sofridos','shots.on':'Remates à baliza','shots.off':'Remates para fora','counts.corner_for':'Cantos a favor','counts.corner_against':'Cantos contra','losses.total':'Perdas de bola','recoveries.total':'Recuperações','through_balls':'Bolas em profundidade','striker_foots':'Bolas no pé do avançado'};
 const PROBLEMS=['problems','losses','offense','defense','transitions','set_pieces','correct','next_priority'];
 const text=(v,n=2000)=>String(v??'').trim().slice(0,n),copy=x=>JSON.parse(JSON.stringify(x));
 function state(match){const old=match?.match_evidence;if(old?.schema&&old.schema!==SCHEMA)throw new Error('Atualiza a app para ler as evidências deste jogo.');const s={schema:SCHEMA,revision:0,moments:[],...(old?copy(old):{})};if(!Number.isInteger(s.revision)||s.revision<0||!Array.isArray(s.moments)||s.moments.length>1000)throw new Error('Registo de evidências inválido.');const ids=new Set();for(const saved of s.moments){if(!saved||typeof saved!=='object'||typeof saved.id!=='string'||!saved.id.trim()||saved.id.length>100||ids.has(saved.id))throw new Error('Registo de evidências inválido: identificador em falta ou repetido.');let normalized;try{normalized=moment(saved,match);}catch(_){throw new Error('Registo de evidências inválido: verifica URL, instante, categoria e descrição.');}if(saved.created_at!=null&&(typeof saved.created_at!=='string'||!Number.isFinite(Date.parse(saved.created_at))))throw new Error('Registo de evidências inválido: data de criação incorreta.');ids.add(saved.id);if(normalized.id!==saved.id)throw new Error('Registo de evidências inválido: identificador incorreto.');}return s;}
 function url(v){const s=text(v,2000);try{const u=new URL(s);if(!['http:','https:'].includes(u.protocol))throw 0;return u.href;}catch(_){throw new Error('O vídeo deve ter um link HTTP ou HTTPS válido.');}}
 function linkAtSeconds(value,seconds){const sec=Number(seconds);if(!Number.isInteger(sec)||sec<0||sec>86400)throw new Error('Indica o segundo do vídeo entre 0 e 86400.');const target=new URL(url(value));target.searchParams.set('t',sec+'s');return target.href;}
 function moment(input,match){const sec=Number(input.seconds);if(!Number.isInteger(sec)||sec<0||sec>86400)throw new Error('Indica o segundo do vídeo entre 0 e 86400.');if(!Object.hasOwn(CATEGORIES,input.category))throw new Error('Escolhe uma categoria válida.');const relationType=input.relation_type==null?'none':input.relation_type,relationRef=text(input.relation_ref,200)||null;if(!['observation','statistic','problem','none'].includes(relationType))throw new Error('Escolhe um tipo de ligação válido.');if(relationType==='none'&&relationRef||relationType!=='none'&&!relationRef)throw new Error('Indica uma origem válida para a ligação deste momento.');if(relationType==='observation'&&!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(relationRef||''))throw new Error('A observação deve usar o UUID estável remoto.');if(relationType==='statistic'&&!Object.hasOwn(STATISTICS,relationRef||''))throw new Error('Escolhe uma estatística conhecida.');if(relationType==='problem'&&(!PROBLEMS.includes(relationRef)||!root.VisionMatchAnalysis?.fromMatch(match).fields[relationRef]))throw new Error('Escolhe um problema com conteúdo na análise deste jogo.');const item={id:text(input.id,100)||crypto.randomUUID(),url:url(input.url),seconds:sec,category:input.category,player_ref:text(input.player_ref,100)||null,description:text(input.description,2000),observation:text(input.observation,1000),relation_type:relationType,relation_ref:relationRef,created_at:input.created_at||new Date().toISOString()};if(!item.description)throw new Error('Descreve o momento.');if(item.player_ref&&!/^[0-9a-f-]{36}$/i.test(item.player_ref))throw new Error('Usa o UUID estável do atleta.');return item;}
 function apply(match,command,options={}){const row=copy(match),s=state(row);if(command.expected_revision!==s.revision)throw new Error('As evidências mudaram noutro dispositivo. Atualiza antes de guardar.');if(command.type==='add'){if(s.moments.some(x=>x.id===command.item?.id))throw new Error('Este momento já existe.');s.moments.push(moment(command.item,row));}else if(command.type==='edit'){const at=s.moments.findIndex(x=>x.id===command.id);if(at<0)throw new Error('Momento inexistente ou apagado.');s.moments[at]=moment({...s.moments[at],...command.item,id:command.id},row);}else if(command.type==='delete'){if(command.confirmed!==true)throw new Error('É necessária confirmação explícita.');const at=s.moments.findIndex(x=>x.id===command.id);if(at<0)throw new Error('Momento inexistente ou apagado.');s.moments.splice(at,1);}else throw new Error('Operação de evidência desconhecida.');s.revision++;s.updated_at=new Date(options.now??Date.now()).toISOString();row.match_evidence=s;return row;}
 root.VisionMatchEvidence={schema:SCHEMA,categories:CATEGORIES,statistics:STATISTICS,problemFields:PROBLEMS,state,moment,linkAtSeconds,apply};if(typeof module!=='undefined'&&module.exports)module.exports=root.VisionMatchEvidence;
})(globalThis);
