"use strict";
// Longitudinal coach-owned development goals; never ranks athletes or infers progress.
(function(root){
 const SCHEMA='vision-player-goals@1',STATES={active:'Ativo',improved:'Melhorou',continue:'Continuar',completed:'Concluído'},UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,copy=x=>JSON.parse(JSON.stringify(x)),text=(x,n=2000)=>String(x??'').trim().slice(0,n);
 function state(player){const old=player?.development_goals;if(old?.schema&&old.schema!==SCHEMA)throw new Error('Atualiza a app antes de abrir os objetivos deste atleta.');const s={schema:SCHEMA,revision:0,items:[],...(old?copy(old):{})};if(!Number.isInteger(s.revision)||s.revision<0||!Array.isArray(s.items))throw new Error('Objetivos individuais inválidos.');return s;}
 function normalize(input,old){const id=text(input.id||old?.id,100)||crypto.randomUUID(),title=text(input.title,200),started=text(input.started_at,10);if(!UUID.test(id))throw new Error('O objetivo precisa de um UUID estável.');if(!title)throw new Error('Escreve o objetivo individual.');if(!/^\d{4}-\d{2}-\d{2}$/.test(started)||Number.isNaN(Date.parse(started)))throw new Error('Indica uma data de início válida.');const status=input.status==null&&!old?'active':input.status;if(!Object.hasOwn(STATES,status))throw new Error('Estado do objetivo inválido.');const evidence_refs=(input.evidence_refs||old?.evidence_refs||[]).map(x=>({type:x.type,id:text(x.id,100)}));if(evidence_refs.some(x=>!['match','training','observation'].includes(x.type)||!UUID.test(x.id)))throw new Error('As evidências precisam de UUID estável e origem válida.');const exercise_refs=[...new Set((input.exercise_refs||old?.exercise_refs||[]).map(x=>text(x,100)))];if(exercise_refs.some(x=>!UUID.test(x)))throw new Error('Os exercícios relacionados precisam de UUID estável.');return{id,title,started_at:started,evidence_refs:[...new Map(evidence_refs.map(x=>[x.type+':'+x.id,x])).values()],exercise_refs,notes:text(input.notes,3000),status,updated_at:new Date().toISOString(),history:old?.history||[]};}
 function apply(player,command,{now}={}){const row=copy(player),s=state(row);if(command.expected_revision!==s.revision)throw new Error('Os objetivos mudaram noutro dispositivo. Atualiza antes de guardar.');if(command.type==='save'){const i=s.items.findIndex(x=>x.id===command.goal.id),old=i<0?null:s.items[i];if(i<0&&s.items.length>=50)throw new Error('Limite de 50 objetivos ativos/históricos atingido.');const item=normalize(command.goal,old);item.updated_at=new Date(now??Date.now()).toISOString();if(old)item.history=[...old.history,{title:old.title,status:old.status,notes:old.notes,updated_at:old.updated_at}].slice(-20);if(i<0)s.items.push(item);else s.items[i]=item;}else if(command.type==='delete'){if(command.confirmed!==true)throw new Error('É necessária confirmação explícita.');const i=s.items.findIndex(x=>x.id===command.id);if(i<0)throw new Error('Objetivo inexistente ou já apagado.');s.items.splice(i,1);}else throw new Error('Operação de objetivo desconhecida.');s.revision++;s.updated_at=new Date(now??Date.now()).toISOString();row.development_goals=s;return row;}
 root.PlayerGoals={schema:SCHEMA,states:STATES,state,normalize,apply};if(typeof module!=='undefined'&&module.exports)module.exports=root.PlayerGoals;
})(globalThis);
