"use strict";
// Print-ready reports from saved local data; the browser print dialog offers Save as PDF.
(function(root){
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),date=v=>v?new Date(v+'T00:00:00').toLocaleDateString('pt-PT'):'—',dateTime=v=>v?new Date(v).toLocaleString('pt-PT'):'data não registada';
 function teamLogoSrc(){return new URL("assets/teams/14529_imgbank.png",location.href).href;} function html(title,subtitle,sections){const logo=teamLogoSrc();return '<!doctype html><html lang="pt-PT"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(title)+'</title><style>*{box-sizing:border-box}body{font:15px/1.45 Arial,sans-serif;color:#111827;margin:0;background:#fff}main{max-width:920px;margin:24px auto;padding:0 22px}header{border-bottom:3px solid #c8102e;padding-bottom:14px;margin-bottom:18px}.team-crest{display:block;width:72px;height:72px;object-fit:contain;background:#0b1220;border:2px solid #c8102e;border-radius:10px;margin:0 0 10px}h1{font-size:28px;margin:0 0 5px}h2{font-size:19px;margin:0 0 8px;color:#991b1b}section{margin:18px 0}.meta{color:#475569}ul{padding-left:20px}.block{border:1px solid #e2e8f0;border-radius:8px;padding:12px;margin:12px 0;break-inside:avoid}.block img{display:block;max-width:100%;height:auto;max-height:520px;object-fit:contain;margin:10px auto}.actions{display:flex;gap:12px;margin:18px 0}.actions button{padding:12px 18px;min-height:44px;font-size:16px}@media print{body{font-size:11pt}main{max-width:none;margin:0;padding:0}header{margin-bottom:12px}.actions{display:none}a{color:inherit;text-decoration:none}section{break-inside:auto}h2{break-after:avoid}li{break-inside:avoid}.block{break-inside:avoid}img{max-height:650px}@page{size:A4;margin:16mm 16mm 20mm;@bottom-right{content:"Página " counter(page) " de " counter(pages);font:9pt Arial,sans-serif;color:#475569}}}</style><main><header>'+(logo?'<img class="team-crest" src="'+esc(logo)+'" alt="Emblema do Sub-8 de Figueiró">':'')+'<h1>'+esc(title)+'</h1><div class="meta">'+esc(subtitle)+'</div></header><div class="actions"><button onclick="window.print()">Imprimir / Guardar como PDF</button><button onclick="window.close()">Fechar</button></div>'+sections.join('')+'</main></html>';}
 const section=(title,body)=>'<section><h2>'+esc(title)+'</h2>'+body+'</section>',items=xs=>'<ul>'+xs.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>',para=x=>x?'<p>'+esc(x).replace(/\n/g,'<br>')+'</p>':'<p class="meta">Não registado.</p>',countLabel=(count,singular,plural)=>count+' '+(count===1?singular:plural);
 async function training(id){
  const raw=await DB.obter('treinos',Number(id));if(!raw)throw new Error('Treino indisponível.');
  const t=TrainingPlanner.normalizeTraining(raw),ex=await DB.porIndice('exercicios','team_id',DEFAULT_TEAM_ID),players=await DB.porIndice('jogadores','team_id',DEFAULT_TEAM_ID),byRef=new Map(ex.map(e=>[String(e.sync_id||e.id),e])),playersByRef=new Map(players.map(p=>[String(p.sync_id),p])),summary=VisionTrainingSession.summary(t.session||{});
  const orderedBlocks=(t.blocos||[]).slice().sort((a,b)=>(a.order||0)-(b.order||0));
  const exerciseForBlock=b=>(b.exercise_snapshot?TrainingPlanner.exerciseFromSnapshot(b.exercise_snapshot,b.exercise_ref,b.exercise_name):null)||byRef.get(String(b.exercise_ref))||{};
  const exercisesToResolve=orderedBlocks.map(exerciseForBlock).filter(e=>e.visual_storage_path&&!e.visual_removed);
  if(exercisesToResolve.length) await globalThis.VisionExerciseImageStorage?.resolve(exercisesToResolve);
  const blocks=orderedBlocks.map((b,i)=>{const e=exerciseForBlock(b),visual=VisionExerciseVisuals.source(e),src=visual?new URL(visual.src,location.href).href:null,missingPrivate=Boolean(e.visual_storage_path&&!e.visual_removed&&!src);return '<article class="block"><h3>'+(i+1)+'. '+esc(e.nome||b.exercise_name||'Exercício')+' · '+Number(b.duration_min||0)+' min</h3><p class="meta">'+esc(b.phase||'')+(e.objetivo?' · '+esc(e.objetivo):'')+'</p><h4>Montagem</h4>'+para(e.montagem||e.organizacao)+'<h4>Passo a passo</h4>'+para(e.passos)+'<h4>Notas deste bloco</h4>'+para(b.notes)+' '+(src?'<img src="'+esc(src)+'" alt="Imagem original aprovada do exercício">':missingPrivate?'<p class="meta">Imagem original aprovada indisponível; verifica a ligação e volta a exportar.</p>':'')+'</article>';});
  const roster=(t.session?.attendance||[]).map(a=>(playersByRef.get(String(a.player_ref))?.nome||a.name||'Atleta')+' · '+(VisionTrainingSession.attendance[a.status]||a.status));
  return html('Plano de treino',date(t.data)+(t.hora?' · '+t.hora:'')+' · '+t.duracao_min+' min',[section('Objetivo',para(t.objetivo)),section('Presenças registadas',roster.length?items(roster):'<p class="meta">Ainda sem convocatória/presenças associadas.</p>'),section('Sequência e montagem',blocks.join('')||'<p>Sem blocos no plano.</p>'),section('Notas',para(t.notas)),section('Execução registada',summary.marked?items(['Estado: '+summary.status,'Participantes presentes/atrasados: '+summary.participants,'Tempo executado: '+VisionTrainingSession.format(summary.actual_ms)]):'<p class="meta">Sem execução iniciada; este documento mostra o plano.</p>')]);
 }
 async function matchReport(id,kind){
  const m=await DB.obter('jogos',Number(id));if(!m)throw new Error('Jogo indisponível.');
  const all=await DB.porIndice('jogadores','team_id',DEFAULT_TEAM_ID),byRef=new Map(all.map(p=>[String(p.sync_id),p])),historicalByRef=new Map((m.visual_match?.roster||[]).map(p=>[String(p.ref),{sync_id:p.ref,nome:p.name,numero:p.number??null,historical:true}])),refs=m.callup?.player_ids||[],called=refs.map(ref=>byRef.get(String(ref))||historicalByRef.get(String(ref))||{sync_id:ref,nome:'Atleta sem perfil atual · UUID '+String(ref),numero:null,historical:true}),unavailable=all.filter(p=>PlayerStatus.inRoster(p)&&!PlayerStatus.isAvailable(p)),lineup=m.lineup||{},slotsByRole=m.visual_match?.initial_slots||lineup.positions||{},slotRefs=Object.values(slotsByRole).filter(Boolean),slotPlayers=Object.entries(slotsByRole).map(([role,ref])=>({role,player:byRef.get(String(ref))||historicalByRef.get(String(ref))})).filter(x=>x.player),bench=called.filter(p=>!slotRefs.map(String).includes(String(p.sync_id))),team=await HeadCoachMemory.ensureTeam(),summary='Adversário: '+(m.adversario||'—')+' · '+date(m.data)+' · '+(m.hora||'hora por definir')+' · '+(m.local||'local por definir');
  if(kind==='match-sheet'){
   const styleLabels={posse:'Posse',direto:'Jogo direto',pressao_alta:'Pressão alta',bloco_baixo:'Bloco baixo',transicoes:'Transições'},pre=m.pre_game||{},opponentFacts=[pre.adversario_sistema?'Sistema observado: '+pre.adversario_sistema:null,pre.adversario_estilo?'Estilo observado: '+(styleLabels[pre.adversario_estilo]||pre.adversario_estilo):null,...(pre.adversario_pontos_fortes||[]).map(x=>'Ponto forte observado: '+x),...(pre.adversario_vulnerabilidades||[]).map(x=>'Vulnerabilidade observada: '+x)];
   return html('Ficha de jogo',summary,[section('Contexto',items(['Casa/Fora: '+(m.casa_fora||'—'),'Competição: '+(m.competicao||team.competicao||'—'),'Estado: '+(m.estado||'—'),'Objetivo: '+(pre.objetivo_principal||'—')])),section('Convocatória',called.length?items(called.map(p=>'#'+(p.numero??'—')+' '+p.nome+(p.historical?' · registo histórico':''))):para('Sem convocatória')),section('Indisponíveis no plantel atual',unavailable.length?items(unavailable.map(p=>p.nome+' · '+PlayerStatus.label(p.estado_disponibilidade))):'<p class="meta">Sem atletas indisponíveis sinalizados no plantel atual.</p>'),section('Alinhamento inicial · '+(lineup.system||'1-2-1'),slotPlayers.length?items(slotPlayers.map(x=>'#'+(x.player.numero??'—')+' '+x.player.nome+(x.player.historical?' · registo histórico':'')+' · '+(VisionMatchVisual.roles[x.role]||x.role))):para('Sem alinhamento guardado')),section('Banco',bench.length?items(bench.map(p=>'#'+(p.numero??'—')+' '+p.nome+(p.historical?' · registo histórico':''))):para('Sem suplentes registados')),section('Observação do adversário',opponentFacts.some(Boolean)?items(opponentFacts.filter(Boolean)):para('Ainda sem observações estruturadas')),section('Notas táticas',para([pre.plano_jogo,pre.adversario_notas].filter(Boolean).join('\n\n')))]);
  }
  const events=VisionMatchEvents.state(m).events,stats=VisionMatchEvents.stats(m),possession=stats.possession,usage=m.visual_match?.started_at?VisionMatchVisual.replay(m):null,a=VisionMatchAnalysis.fromMatch(m),moments=VisionMatchEvidence.state(m).moments,historicalPlayers=new Map((m.visual_match?.roster||[]).map(p=>[String(p.ref),p.name])),playerName=ref=>historicalPlayers.get(String(ref))||byRef.get(String(ref))?.nome||'Atleta não identificado',linkedMemories=moments.some(x=>x.relation_type==='observation')?await HeadCoachMemory.list(DEFAULT_TEAM_ID,{subjectType:'match',subjectId:m.sync_id||m.id}):[],memoryByRef=new Map(linkedMemories.map(x=>[String(x.sync_id),x]));
  const tallyRows=(label,counts,names)=>Object.entries(counts||{}).filter(([,n])=>n>0).map(([key,n])=>label+': '+(names[key]||'Não especificado')+' · '+n);
  const detailStats=stats.events_available?[...tallyRows('Perdas por motivo',stats.losses.by_reason,{'none':'Motivo não registado',...VisionMatchEvents.lossReasons}),...tallyRows('Perdas por zona',stats.losses.by_zone,VisionMatchEvents.zones),...tallyRows('Recuperações por zona',stats.recoveries.by_zone,VisionMatchEvents.zones)]:[];
  const statistics=stats.events_available?items(['Origem: contada nos acontecimentos registados','Golos contados '+stats.goals.for+'–'+stats.goals.against,'Remates à baliza '+stats.shots.on,'Remates para fora '+stats.shots.off,'Cantos a favor/contra '+stats.counts.corner_for+'/'+stats.counts.corner_against,'Perdas '+stats.losses.total,'Recuperações '+stats.recoveries.total,'Bolas em profundidade '+stats.through_balls,'Bolas no pé do avançado '+stats.striker_foots,...detailStats]):para('Sem registo de lances; estatísticas desconhecidas, não equivalem a zero');
  const possessionText=VisionMatchEvents.possessionKinds[possession.kind]+(possession.value!=null?' · '+possession.value+'%':' · sem valor registado')+(possession.kind==='estimated'?' · estimativa introduzida pelo treinador':possession.kind==='measured'?' · valor marcado como medido pelo treinador':''),eventRows=events.map(e=>{const minute=Math.floor(e.at_ms/60000)+':'+String(Math.floor(e.at_ms/1000)%60).padStart(2,'0');return [minute,VisionMatchEvents.types[e.type],e.side&&VisionMatchEvents.sides[e.side],e.player_ref&&playerName(e.player_ref),e.opponent_player_name&&'Adversário: '+e.opponent_player_name,e.zone&&VisionMatchEvents.zones[e.zone],e.reason&&VisionMatchEvents.lossReasons[e.reason],e.note].filter(Boolean).join(' · ');});
  const movements=(m.visual_match?.events||[]).filter(e=>!e.voided_at&&e.type==='substitute').sort((x,y)=>x.at_ms-y.at_ms),movementRows=movements.map(e=>Math.floor(e.at_ms/60000)+':'+String(Math.floor(e.at_ms/1000)%60).padStart(2,'0')+' · sai '+playerName(e.out_ref)+' · entra '+playerName(e.in_ref)),causeRows=Object.entries(a.goals_conceded).filter(([,text])=>String(text||'').trim()).map(([eventId,text])=>{const event=events.find(e=>String(e.id)===String(eventId));if(!event)return 'Golo sofrido associado a lance já não disponível · '+text;return Math.floor(event.at_ms/60000)+':'+String(Math.floor(event.at_ms/1000)%60).padStart(2,'0')+' · '+(event.opponent_player_name?'marcador adversário: '+event.opponent_player_name:playerName(event.player_ref))+' · causa provável: '+text;});
  const momentLinks=moments.length?'<ul>'+moments.map(x=>{const url=new URL(VisionMatchEvidence.linkAtSeconds(x.url,x.seconds)),relation=x.relation_type==='observation'?(memoryByRef.get(String(x.relation_ref))?'Observação: '+memoryByRef.get(String(x.relation_ref)).title:'Observação · referência histórica (origem removida): '+x.relation_ref):x.relation_type==='statistic'?'Estatística: '+(VisionMatchEvidence.statistics[x.relation_ref]||x.relation_ref):x.relation_type==='problem'?(a.fields[x.relation_ref]?'Problema: ':'Problema · referência histórica (já não consta da análise): ')+(VisionMatchAnalysis.fields[x.relation_ref]||x.relation_ref):'';return '<li><a href="'+esc(url.href)+'" target="_blank" rel="noopener">'+Math.floor(x.seconds/60)+':'+String(x.seconds%60).padStart(2,'0')+' · '+esc(VisionMatchEvidence.categories[x.category])+' · '+esc(x.description)+'</a>'+(x.player_ref?' · '+esc(playerName(x.player_ref)):'')+(relation?' · '+esc(relation):'')+'</li>';}).join('')+'</ul>':para('Sem momentos ligados');
  return html('Relatório pós-jogo',summary,[section('Resultado registado pelo treinador',m.golos_favor!=null&&m.golos_contra!=null?'<p>'+esc(m.golos_favor)+'–'+esc(m.golos_contra)+' · introduzido manualmente</p>':'<p class="meta">Resultado não registado.</p>'),section('Estatísticas contadas',statistics),section('Posse de bola',para(possessionText)),section('Acontecimentos registados',eventRows.length?items(eventRows):para('Sem lances registados')),section('Utilização registada',usage?items(usage.players.map(p=>p.name+' · '+VisionMatchVisual.format(p.elapsed_ms)+' · GR '+VisionMatchVisual.format(p.keeper_ms))):para('Sem minutos registados')),section('Histórico de substituições registadas',movementRows.length?items(movementRows):para('Sem substituições registadas')),section('Análise do treinador',Object.entries(VisionMatchAnalysis.fields).map(([k,label])=>a.fields[k]?'<h3>'+esc(label)+'</h3>'+para(a.fields[k]):'').join('')||'<p class="meta">Sem análise estruturada.</p>'),section('Causas prováveis de golos sofridos',causeRows.length?items(causeRows):para('Sem causas registadas')),section('Evidências de vídeo',momentLinks)]);}
 async function teamReport(seasonId){
  const [team,trainings,matches,players,exercises,docs,memories]=await Promise.all([HeadCoachMemory.ensureTeam(),DB.porIndice('treinos','team_id',DEFAULT_TEAM_ID),DB.porIndice('jogos','team_id',DEFAULT_TEAM_ID),DB.porIndice('jogadores','team_id',DEFAULT_TEAM_ID),DB.porIndice('exercicios','team_id',DEFAULT_TEAM_ID),WorkspaceStore.listDocuments(DEFAULT_TEAM_ID,{includeArchived:true}),HeadCoachMemory.list(DEFAULT_TEAM_ID,{includeArchived:true})]);
  const seasons=VisionSeasons.state(docs.find(d=>d.type==='season_index')),requestedSeasonId=seasonId||seasons.active_id,season=seasons.items.find(x=>x.id===requestedSeasonId)||null;if(requestedSeasonId&&!season)throw new Error('A época selecionada já não existe neste workspace. Atualiza a lista antes de exportar.');
  const inPeriod=row=>!season||VisionSeasons.includes(season,row.data),memoryInPeriod=m=>!season||VisionSeasons.includes(season,m.occurred_at),periodTrainings=trainings.filter(inPeriod),periodMatches=matches.filter(inPeriod),periodMemories=memories.filter(m=>m.status==='active'&&memoryInPeriod(m));
  const teamPlayers=season?season.roster.map(x=>players.find(p=>p.sync_id===x.ref)||{sync_id:x.ref,nome:x.name,numero:x.number}):players.filter(PlayerStatus.inRoster),allGoals=docs.filter(d=>d.type==='team_goal').map(doc=>({doc,value:TeamDevelopment.teamGoal(doc)})),goalLinkedToPeriod=g=>[...(g.sessions||[]),...(g.worked_sessions||[]),...(g.evidence||[])].some(ref=>ref.type==='training'?trainings.some(row=>String(row.sync_id)===String(ref.id)&&inPeriod(row)):ref.type==='match'?matches.some(row=>String(row.sync_id)===String(ref.id)&&inPeriod(row)):ref.type==='memory'?memories.some(row=>String(row.sync_id)===String(ref.id)&&memoryInPeriod(row)):false),goals=allGoals.filter(({doc,value})=>!season||VisionSeasons.includes(season,value.identified_at||doc.target_date||doc.created_at?.slice(0,10))||goalLinkedToPeriod(value)),weeks=docs.filter(d=>d.type==='weekly_plan'&&(!season||VisionSeasons.includes(season,d.target_date||d.created_at?.slice(0,10)))).map(d=>({doc:d,value:TeamDevelopment.week(d)}));
  const minutes=new Map(),playersWithRecordedUsage=new Set();for(const m of periodMatches)if(m.visual_match?.started_at)for(const player of VisionMatchVisual.replay(m).players){playersWithRecordedUsage.add(String(player.ref));minutes.set(String(player.ref),(minutes.get(String(player.ref))||0)+player.elapsed_ms);}
  const activeGoals=goals.filter(x=>x.doc.status!=='archived'&&x.value.agent_proposal?.status!=='proposed'),archivedGoals=goals.filter(x=>x.doc.status==='archived'),pendingGoalProposals=goals.filter(x=>x.doc.status!=='archived'&&x.value.agent_proposal?.status==='proposed'),weeksWithEvaluation=weeks.filter(x=>String(x.value.evaluation.summary||'').trim()),weeksPendingEvaluation=weeks.filter(x=>!String(x.value.evaluation.summary||'').trim());
  const matchEventStats=periodMatches.map(m=>({match:m,stats:VisionMatchEvents.stats(m)})),countedMatches=matchEventStats.filter(x=>x.stats.events_available),unknownEventMatches=periodMatches.length-countedMatches.length,eventTotals=countedMatches.reduce((sum,item)=>{const s=item.stats;for(const k of ['shots.on','shots.off','counts.corner_for','counts.corner_against','losses.total','recoveries.total','through_balls','striker_foots','goals.for','goals.against']){const value=k.split('.').reduce((v,key)=>v?.[key],s);sum[k]=(sum[k]||0)+(Number(value)||0);}return sum;},{}),provenance='Contagens somadas apenas a partir dos lances registados; jogos sem registo têm estatísticas desconhecidas.',eventCoverage=periodMatches.length?'Registo de lances em '+countedMatches.length+' de '+periodMatches.length+' jogos; '+unknownEventMatches+' sem registo (contagens desconhecidas).':'Sem jogos neste período; estatísticas de jogo indisponíveis.',possessionRows=matchEventStats.map(({match,stats})=>{const value=stats.possession||{kind:'unknown',value:null},label=VisionMatchEvents.possessionKinds[value.kind]||'Desconhecida',provenance=value.kind==='measured'?' · valor introduzido pelo treinador como medido':value.kind==='estimated'?' · estimativa introduzida pelo treinador':'';return date(match.data)+' · '+(match.adversario||'Adversário')+' · '+label+(value.value!=null?' · '+value.value+'%':' · sem valor registado')+provenance;});
  const matchRows=periodMatches.slice().sort((a,b)=>String(a.data).localeCompare(String(b.data))).map(m=>date(m.data)+' · '+(m.adversario||'Adversário')+' · '+(m.golos_favor!=null&&m.golos_contra!=null?m.golos_favor+'–'+m.golos_contra+' (introduzido manualmente)':'resultado não registado'));
  const playerRows=teamPlayers.filter(p=>playersWithRecordedUsage.has(String(p.sync_id))).map(p=>({p,ms:minutes.get(String(p.sync_id))})).sort((a,b)=>String(a.p.nome||'').localeCompare(String(b.p.nome||''),'pt-PT')).map(x=>x.p.nome+' · '+VisionMatchVisual.format(x.ms)+' registados');
  const sessionLabel=(type,ref)=>{const all=type==='training'?trainings:matches,row=all.find(x=>String(x.sync_id)===String(ref));if(!row)return'Fonte não disponível neste dispositivo (UUID '+ref+')';return date(row.data)+' · '+(type==='training'?(row.objetivo||row.escalao||'Treino'):'Jogo vs '+(row.adversario||'adversário'))+(!inPeriod(row)?' · fora do período':'');};
  const resolveWeekRef=(input,type)=>{const ref=typeof input==='object'?input.id:input,kind=type||(typeof input==='object'?input.type:null);if(kind==='training')return'Treino · '+sessionLabel('training',ref);if(kind==='match')return'Jogo · '+sessionLabel('match',ref);if(kind==='memory'){const memory=memories.find(x=>String(x.sync_id)===String(ref));return memory?'Observação · '+date(memory.occurred_at)+' · '+(memory.title||'sem título')+(memory.status==='archived'?' · arquivada':'')+(!memoryInPeriod(memory)?' · fora do período':'')+(memory.content?' · excerto (máx. 500 caracteres): '+String(memory.content).slice(0,500):''):'Fonte não disponível neste dispositivo (UUID '+ref+')';}if(kind==='exercise'){const exercise=exercises.find(x=>String(x.sync_id||x.id)===String(ref));return exercise?'Exercício · '+(exercise.nome||exercise.objetivo||'sem título'):'Fonte não disponível neste dispositivo (UUID '+ref+')';}const training=trainings.find(x=>String(x.sync_id)===String(ref));if(training)return'Treino · '+sessionLabel('training',ref);const match=matches.find(x=>String(x.sync_id)===String(ref));if(match)return'Jogo · '+sessionLabel('match',ref);const memory=memories.find(x=>String(x.sync_id)===String(ref));if(memory)return'Observação · '+date(memory.occurred_at)+' · '+(memory.title||'sem título')+(memory.status==='archived'?' · arquivada':'')+(!memoryInPeriod(memory)?' · fora do período':'')+(memory.content?' · excerto (máx. 500 caracteres): '+String(memory.content).slice(0,500):'');const exercise=exercises.find(x=>String(x.sync_id||x.id)===String(ref));if(exercise)return'Exercício · '+(exercise.nome||exercise.objetivo||'sem título');return'Fonte não disponível neste dispositivo (UUID '+ref+')';};
  const sessionLabelForRef=ref=>{const training=trainings.find(x=>String(x.sync_id)===String(ref));if(training)return'Treino · '+sessionLabel('training',ref);const match=matches.find(x=>String(x.sync_id)===String(ref));if(match)return'Jogo · '+sessionLabel('match',ref);return resolveWeekRef(ref);};
  const goalsBody=goals.length?goals.map(({doc,value:g})=>{const sessions=g.sessions.length?g.sessions.map(ref=>resolveWeekRef(ref)).join('; '):'nenhuma associada',worked=g.worked_sessions===null?'não detalhadas no registo antigo':g.worked_sessions.length?g.worked_sessions.map(ref=>resolveWeekRef(ref)).join('; '):'nenhuma assinalada',goalExercises=g.exercises.length?g.exercises.map(ref=>resolveWeekRef(ref)).join('; '):'nenhum associado',evidence=g.evidence.length?g.evidence.map(ref=>resolveWeekRef(ref)).join('; '):'nenhuma associada',title=g.title+' · '+(doc.status==='archived'?'Arquivado':g.agent_proposal?.status==='proposed'?'Proposta do Head Coach · por rever':'Ativo')+' · '+TeamDevelopment.labels[g.stage]+' · identificado '+date(g.identified_at);return'<article class="team-goal-report" style="break-inside:auto;margin:12px 0"><h3 style="break-after:avoid;margin:10px 0 4px">'+esc(title)+'</h3>'+items(['Sessões associadas: '+sessions,'Sessões assinaladas como trabalhadas: '+worked,'Exercícios: '+goalExercises,'Evidências: '+evidence,'Facto/observação: '+(g.observations||'não registado'),'Interpretação: '+(g.interpretation||'não registada'),'Hipótese: '+(g.hypothesis||'não registada'),'Avaliação do treinador: '+(g.evaluation||'não registada'),'Decisão do treinador: '+(g.coach_decision||'não registada')])+'</article>';}).join(''):para('Sem objetivos de equipa neste período');
  const weekBody=weeks.length?items(weeks.map(({value:w})=>{const slots=[[w.training1,'Treino 1'],[w.training2,'Treino 2'],[w.match,'Jogo']].filter(x=>x[0]),sessions=slots.map(([ref,label])=>label+': '+sessionLabel(label==='Jogo'?'match':'training',ref)),relations=(w.links||[]).map(link=>{const from=slots.find(x=>String(x[0])===String(link.from))?.[1]||sessionLabelForRef(link.from),to=slots.find(x=>String(x[0])===String(link.to))?.[1]||sessionLabelForRef(link.to);return from+' → '+to+(link.note?' · '+link.note:'');}),evidence=(w.evaluation?.evidence||[]).map(ref=>resolveWeekRef(ref));return date(w.week_start)+' · '+(w.objective||'Objetivo não registado')+' · '+(sessions.length?sessions.join(' · '):'Sessões não associadas')+(relations.length?' · Relação entre sessões: '+relations.join('; '):'')+(w.evaluation.summary?' · avaliação do treinador: '+w.evaluation.summary:' · avaliação pendente')+(evidence.length?' · Evidências: '+evidence.join('; '):' · sem evidências associadas');})):para('Sem planeamento semanal neste período');
  const priorities=periodMatches.map(m=>({m,a:VisionMatchAnalysis.fromMatch(m)})).filter(x=>x.a.fields.next_priority).map(x=>date(x.m.data)+' · '+x.m.adversario+': '+x.a.fields.next_priority);
  const period=season?season.name+' · '+date(season.start_date)+' – '+date(season.end_date):'Todo o histórico guardado (sem época selecionada)';
  return html('Relatório de equipa · '+team.nome,period,[section('Resumo',items([team.clube||team.nome,periodTrainings.length+' treinos registados',periodMatches.length+' jogos registados',countLabel(activeGoals.length,'objetivo de equipa ativo','objetivos de equipa ativos'),countLabel(archivedGoals.length,'objetivo de equipa arquivado','objetivos de equipa arquivados'),countLabel(pendingGoalProposals.length,'proposta do Head Coach por rever','propostas do Head Coach por rever'),countLabel(weeksWithEvaluation.length,'avaliação semanal concluída','avaliações semanais concluídas'),countLabel(weeksPendingEvaluation.length,'avaliação semanal pendente','avaliações semanais pendentes'),periodMemories.length+' observações na memória do período'])),section('Jogos',matchRows.length?items(matchRows):para('Sem jogos registados')),section('Estatísticas de jogo · '+provenance,countedMatches.length?items([eventCoverage,'Golos registados '+(eventTotals['goals.for']||0)+'–'+(eventTotals['goals.against']||0),'Remates à baliza '+(eventTotals['shots.on']||0),'Remates para fora '+(eventTotals['shots.off']||0),'Cantos a favor/contra '+(eventTotals['counts.corner_for']||0)+'/'+(eventTotals['counts.corner_against']||0),'Perdas '+(eventTotals['losses.total']||0),'Recuperações '+(eventTotals['recoveries.total']||0),'Bolas em profundidade '+(eventTotals.through_balls||0),'Bolas no pé do avançado '+(eventTotals.striker_foots||0)]):para(eventCoverage+' Sem lances registados; estatísticas indisponíveis.')),section('Posse de bola por jogo · sem média entre origens diferentes',possessionRows.length?items(possessionRows):para('Sem jogos neste período; posse desconhecida')),section('Utilização registada · informação para o treinador',playerRows.length?'<p class="meta">Minutos de atletas incluídos em jogos com registo de utilização, por ordem alfabética. Atletas sem registo de minutos neste período não são listados; estes valores não constituem uma classificação.</p>'+items(playerRows):para('Sem registos de utilização neste período; os minutos não são conhecidos')),section('Objetivos da equipa',goalsBody),section('Planeamento e avaliação semanal',weekBody),section('Prioridades registadas para próximos treinos',priorities.length?items(priorities):para('Sem prioridades de jogo registadas')),section('Observações do período',periodMemories.length?items(periodMemories.slice().sort((a,b)=>String(a.occurred_at).localeCompare(String(b.occurred_at))).map(m=>date(m.occurred_at)+' · '+m.title+': '+m.content)):para('Sem observações na memória'))]);
 }
 async function playerReport(id,seasonId){
  const p=await DB.obter('jogadores',Number(id));if(!p)throw new Error('Atleta indisponível.');const allGoals=PlayerGoals.state(p).items,trainings=await DB.porIndice('treinos','team_id',DEFAULT_TEAM_ID),matches=await DB.porIndice('jogos','team_id',DEFAULT_TEAM_ID),seasonDocs=await WorkspaceStore.listDocuments(DEFAULT_TEAM_ID,{includeArchived:true}),seasonState=VisionSeasons.state(seasonDocs.find(d=>d.type==='season_index')),requestedSeasonId=seasonId||seasonState.active_id,season=seasonState.items.find(x=>x.id===requestedSeasonId)||null;if(requestedSeasonId&&!season)throw new Error('A época selecionada já não existe neste workspace. Atualiza a lista antes de exportar.');
  const periodMatches=season?matches.filter(m=>VisionSeasons.includes(season,m.data)):matches,periodTrainings=season?trainings.filter(t=>VisionSeasons.includes(season,t.data)):trainings,callups=periodMatches.filter(m=>(m.callup?.player_ids||[]).map(String).includes(String(p.sync_id))),startedMatches=periodMatches.filter(m=>!!VisionMatchVisual.state(m).started_at),starts=startedMatches.filter(m=>Object.values(VisionMatchVisual.state(m).initial_slots||VisionMatchVisual.initialSlots(m)).map(String).includes(String(p.sync_id))),startRefs=new Set(starts.map(m=>String(m.sync_id)));
  const trainingRecords=periodTrainings.map(t=>({t,a:(t.session?.attendance||[]).find(a=>String(a.player_ref)===String(p.sync_id))})).filter(x=>x.a&&x.a.status!=='unknown'),trainingRows=trainingRecords.map(({t,a})=>date(t.data)+' · '+(VisionTrainingSession.attendance[a.status]||a.status)+' · '+(VisionTrainingContinuity.effectiveReview(t).status==='done'?'avaliação registada':'avaliação por preencher')),trainingPresenceCount=trainingRecords.filter(x=>['present','late'].includes(x.a.status)).length;
  const playerMemories=await HeadCoachMemory.list(DEFAULT_TEAM_ID,{subjectType:'player',subjectId:id}),periodMemories=season?playerMemories.filter(m=>VisionSeasons.includes(season,m.occurred_at)):playerMemories,periodMatchRefs=new Set(periodMatches.map(m=>String(m.sync_id)).filter(Boolean)),periodTrainingRefs=new Set(periodTrainings.map(t=>String(t.sync_id)).filter(Boolean)),periodMemoryRefs=new Set(periodMemories.map(m=>String(m.sync_id)).filter(Boolean));
  const goals=allGoals.filter(g=>!season||VisionSeasons.includes(season,g.started_at)||g.evidence_refs.some(ref=>ref.type==='match'?periodMatchRefs.has(String(ref.id)):ref.type==='training'?periodTrainingRefs.has(String(ref.id)):ref.type==='observation'&&periodMemoryRefs.has(String(ref.id))));
  let totalMinutes=0,recordedMinuteMatches=0,substituteEntries=0,substituteExits=0;
  const matchRows=callups.map(m=>{const usage=VisionMatchVisual.state(m).started_at?VisionMatchVisual.replay(m).players.find(x=>String(x.ref)===String(p.sync_id)):null,known=!!usage,participated=known&&(usage.elapsed_ms>0||startRefs.has(String(m.sync_id))||(m.visual_match?.events||[]).some(ev=>!ev.voided_at&&ev.type==='substitute'&&String(ev.in_ref)===String(p.sync_id))),positions=participated?VisionMatchVisual.positionsPlayed(m,p.sync_id).map(role=>VisionMatchVisual.roles[role]):[],movementEvents=(m.visual_match?.events||[]).filter(ev=>!ev.voided_at&&ev.type==='substitute'),entries=movementEvents.filter(ev=>String(ev.in_ref)===String(p.sync_id)),exits=movementEvents.filter(ev=>String(ev.out_ref)===String(p.sync_id));if(known){totalMinutes+=usage.elapsed_ms;recordedMinuteMatches++;}substituteEntries+=entries.length;substituteExits+=exits.length;const time=known?(usage.elapsed_ms?VisionMatchVisual.format(usage.elapsed_ms)+' utilizados':participated?'00:00 registados':'00:00 registados · não utilizado'):'convocado, minutos desconhecidos';return date(m.data)+' · '+m.adversario+' · '+time+(startRefs.has(String(m.sync_id))?' · titular':'')+(entries.length?' · entradas: '+entries.map(ev=>Math.floor(ev.at_ms/60000)+' min').join(', '):'')+(exits.length?' · saídas: '+exits.map(ev=>Math.floor(ev.at_ms/60000)+' min').join(', '):'')+(positions.length?' · posições: '+positions.join(', '):'');});
  const allRefs=[...matches.map(m=>({type:'match',row:m})),...trainings.map(t=>({type:'training',row:t})),...playerMemories.map(m=>({type:'observation',row:{sync_id:m.sync_id,data:m.occurred_at,title:m.title}}))],evidenceLabel=new Map(allRefs.map(x=>[x.type+':'+String(x.row.sync_id),date(x.row.data)+' · '+(x.row.adversario||x.row.objetivo||x.row.title||x.type)])),exercises=await DB.porIndice('exercicios','team_id',DEFAULT_TEAM_ID),exerciseNames=new Map(exercises.map(x=>[String(x.sync_id),x.nome]));
  const objectiveRows=goals.flatMap(g=>{const evidence=g.evidence_refs.map(ref=>{const label=evidenceLabel.get(ref.type+':'+ref.id)||ref.type+' · '+ref.id,inside=ref.type==='match'?periodMatchRefs.has(String(ref.id)):ref.type==='training'?periodTrainingRefs.has(String(ref.id)):ref.type==='observation'&&periodMemoryRefs.has(String(ref.id));return label+(season&&!inside?' · fora do período':'');}),related=g.exercise_refs.map(x=>exerciseNames.get(x)||x),current=g.title+' · desde '+date(g.started_at)+' · estado atual: '+PlayerGoals.states[g.status]+(g.notes?' · '+g.notes:'')+' · Evidências: '+(evidence.join('; ')||'nenhuma')+' · Exercícios: '+(related.join('; ')||'nenhum'),history=(g.history||[]).map(h=>g.title+' · evolução anterior em '+dateTime(h.updated_at)+' · '+(h.title&&h.title!==g.title?'objetivo: '+h.title+' · ':'')+'estado: '+(PlayerGoals.states[h.status]||h.status||'não registado')+(h.notes?' · '+h.notes:''));return[current,...history];});
  const rosterMember=season?.roster.some(x=>x.ref===p.sync_id),periodLabel=season?season.name+' · '+date(season.start_date)+' – '+date(season.end_date):'Período completo registado (sem época definida)',unknownMinuteMatches=callups.length-recordedMinuteMatches,minutesSummary=recordedMinuteMatches?VisionMatchVisual.format(totalMinutes)+' · '+recordedMinuteMatches+' jogo(s) com utilização registada':'desconhecidos · sem utilização registada';
  return html('Relatório do atleta',p.nome+' · '+(p.posicao||'posição não definida')+' · '+periodLabel,[...(season&&!rosterMember?[section('Nota de período','<p class="meta">Atleta fora do plantel arquivado desta época; os registos encontrados dentro das datas são apresentados.</p>')]:[]),section('Participação e utilização',items(['Convocatórias: '+callups.length,'Titularidades registadas: '+starts.length,'Treinos com estado de presença registado: '+trainingRows.length,'Presenças/atrasos registados: '+trainingPresenceCount,'Jogos com minutos registados: '+recordedMinuteMatches,'Convocatórias com minutos desconhecidos: '+unknownMinuteMatches,'Minutos totais registados: '+minutesSummary,'Entradas como suplente registadas: '+substituteEntries,'Saídas registadas: '+substituteExits])),section('Histórico de treinos',trainingRows.length?items(trainingRows):para('Sem estados de presença registados')),section('Histórico de jogos',matchRows.length?items(matchRows):para('Sem convocatórias registadas')),section('Objetivos individuais e evolução',objectiveRows.length?items(objectiveRows):para(season?'Sem objetivos identificados nesta época ou ligados a evidências do período':'Sem objetivos individuais')),section('Observações da memória',para(periodMemories.map(m=>date(m.occurred_at)+' · '+m.title+': '+m.content).join('\n')||'Sem observações na memória'))]);
 }
 async function render(kind,id,context){if(kind==='training')return training(id);if(kind==='match-sheet'||kind==='match-report')return matchReport(id,kind);if(kind==='player')return playerReport(id,context?.seasonId);if(kind==='team')return teamReport(context?.seasonId);throw new Error('Tipo de relatório desconhecido.');}
 async function open(kind,id,context){const win=window.open('about:blank','_blank');if(!win)throw new Error('Permite abrir o separador de impressão para exportar.');win.document.write('<!doctype html><title>A preparar relatório…</title><p>A preparar dados guardados…</p>');try{const content=await render(kind,id,context);win.document.open();win.document.write(content);win.document.close();win.focus();}catch(error){win.close();throw error;}}
 root.ReportExporter={render,open};
})(globalThis);
