"use strict";
// Season index snapshots roster membership and keeps all event history in place.
(function(root){
 const SCHEMA='vision-seasons@1',txt=(v,n=500)=>String(v??'').trim().slice(0,n),copy=x=>JSON.parse(JSON.stringify(x));
 function state(doc){let raw={};try{raw=JSON.parse(doc?.body||'{}');}catch{}if(raw.schema&&raw.schema!==SCHEMA)throw new Error('Atualiza a app antes de editar épocas.');const s={schema:SCHEMA,revision:0,active_id:null,items:[],history:[],...(raw||{})};if(!Number.isInteger(s.revision)||!Array.isArray(s.items))throw new Error('Arquivo de épocas inválido.');return s;}
 async function stableIndexId(teamId){const ns=Uint8Array.from('352928ef96fd4be388cb189623f66a21'.match(/../g),x=>parseInt(x,16)),bytes=new TextEncoder().encode('vision-season-index:'+teamId),input=new Uint8Array(16+bytes.length);input.set(ns);input.set(bytes,16);const out=new Uint8Array(await crypto.subtle.digest('SHA-1',input)).slice(0,16);out[6]=(out[6]&15)|80;out[8]=(out[8]&63)|128;const h=[...out].map(x=>x.toString(16).padStart(2,'0')).join('');return h.slice(0,8)+'-'+h.slice(8,12)+'-'+h.slice(12,16)+'-'+h.slice(16,20)+'-'+h.slice(20);}
 function validDate(x){if(!/^\d{4}-\d\d-\d\d$/.test(x))return false;const d=new Date(x+'T12:00:00Z');return!Number.isNaN(d.valueOf())&&d.toISOString().slice(0,10)===x;}
 function save(doc,input,{expected_revision,now=new Date().toISOString()}={}){const prev=state(doc);if(prev.revision!==expected_revision)throw new Error('O arquivo de épocas mudou noutro dispositivo. Atualiza e compara antes de guardar.');const name=txt(input.name,60),start=txt(input.start_date,10),end=txt(input.end_date,10);if(!name)throw new Error('Indica o nome da época.');if(!validDate(start)||!validDate(end)||start>end)throw new Error('Indica um intervalo de datas válido.');const rosterInput=Array.isArray(input.roster)?input.roster:[];if(rosterInput.length>100)throw new Error('O plantel da época não pode exceder 100 atletas.');const normalizedRoster=rosterInput.map(p=>({ref:txt(p.ref,100),name:txt(p.name,120),number:p.number==null?null:Number(p.number)})),uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;if(normalizedRoster.some(p=>!uuid.test(p.ref)||!p.name||(p.number!=null&&!Number.isInteger(p.number))))throw new Error('O plantel da época precisa de UUIDs válidos, nomes e dorsais inteiros.');const roster=[...new Map(normalizedRoster.map(p=>[p.ref,p])).values()];const id=input.id||crypto.randomUUID();if(!uuid.test(id))throw new Error('A época precisa de um UUID estável.');const at=prev.items.findIndex(x=>x.id===id);if(prev.items.some((x,i)=>i!==at&&x.name.toLowerCase()===name.toLowerCase()))throw new Error('Já existe uma época com este nome.');const old=at>=0?prev.items[at]:null,item={id,name,start_date:start,end_date:end,roster,created_at:old?.created_at||now,updated_at:now};const items=prev.items.slice();if(at<0)items.push(item);else items[at]=item;const active=input.activate===true?id:prev.active_id;return{schema:SCHEMA,revision:prev.revision+1,active_id:active,items:items.map(x=>({...x,state:x.id===active?'active':'archived'})),history:[...prev.history,{revision:prev.revision,active_id:prev.active_id,updated_at:prev.updated_at||null}].slice(-40),updated_at:now};}
 function activate(doc,id,{expected_revision,now=new Date().toISOString()}={}){const prev=state(doc);if(prev.revision!==expected_revision)throw new Error('O arquivo de épocas mudou noutro dispositivo. Atualiza antes de alterar a época ativa.');if(!prev.items.some(x=>x.id===id))throw new Error('Época não encontrada.');return{...prev,revision:prev.revision+1,active_id:id,items:prev.items.map(x=>({...x,state:x.id===id?'active':'archived',updated_at:x.id===id?now:x.updated_at})),history:[...prev.history,{revision:prev.revision,active_id:prev.active_id,updated_at:prev.updated_at||null}].slice(-40),updated_at:now};}
 function includes(season,date){const d=String(date||'').slice(0,10);return !!d&&d>=season.start_date&&d<=season.end_date;}
 root.VisionSeasons={schema:SCHEMA,state,save,activate,includes,stableIndexId};if(typeof module!=='undefined'&&module.exports)module.exports=root.VisionSeasons;
})(globalThis);
