"use strict";
// Coach-owned weekly plans and team development goals. Progress is always explicit.
(function(root){
 const WEEK_SCHEMA='vision-week-plan@1',GOAL_SCHEMA='vision-team-goal@1';
 const STAGES=['identified','planned','worked','observed','evaluated','improved','continue'];
 const LABELS={identified:'Identificado',planned:'Planeado',worked:'Trabalhado',observed:'Observado',evaluated:'Avaliado',improved:'Melhorou',continue:'Continua'};
 const txt=(v,n=2000)=>String(v??'').trim().slice(0,n),clone=x=>JSON.parse(JSON.stringify(x));
 const uuid=()=>crypto.randomUUID();
 function refs(xs){return [...new Map((Array.isArray(xs)?xs:[]).map(x=>({type:txt(x.type,30),id:txt(x.id,100)})).filter(x=>['training','match','memory','exercise'].includes(x.type)&&/^[0-9a-f-]{36}$/i.test(x.id)).map(x=>[x.type+':'+x.id,x])).values()];}
 function monday(date){const d=new Date(date+'T12:00:00Z');if(!/^\d{4}-\d\d-\d\d$/.test(date)||Number.isNaN(d.valueOf()))throw new Error('Indica uma data válida para a semana.');d.setUTCDate(d.getUTCDate()-((d.getUTCDay()+6)%7));return d.toISOString().slice(0,10);}
 function read(doc,schema){try{const v=JSON.parse(doc?.body||'{}');if(v.schema&&v.schema!==schema)throw new Error('Atualiza a app antes de editar este registo.');return v;}catch(e){if(e.message.startsWith('Atualiza'))throw e;return {};}}
 function week(doc){const v=read(doc,WEEK_SCHEMA);return{schema:WEEK_SCHEMA,revision:0,objective:'',training1:null,training2:null,match:null,links:[],evaluation:{summary:'',evidence:[]},...v};}
 function saveWeek(old,input,{expected_revision,now=new Date().toISOString()}={}){const prev=week(old);if(expected_revision!==prev.revision)throw new Error('O plano semanal mudou noutro dispositivo. Atualiza e compara antes de guardar.');const week_start=monday(txt(input.week_start,10));const slot=x=>x&&/^[0-9a-f-]{36}$/i.test(String(x))?String(x):null;const next={schema:WEEK_SCHEMA,revision:prev.revision+1,week_start,objective:txt(input.objective,1000),training1:slot(input.training1),training2:slot(input.training2),match:slot(input.match),links:(input.links||[]).map(x=>({from:slot(x.from),to:slot(x.to),note:txt(x.note,500)})).filter(x=>x.from&&x.to),evaluation:{summary:txt(input.evaluation?.summary,3000),evidence:refs(input.evaluation?.evidence)},updated_at:now,history:[...(prev.history||[]),{revision:prev.revision,objective:prev.objective,updated_at:prev.updated_at||null}]};return next;}
 function teamGoal(doc){const v=read(doc,GOAL_SCHEMA);return{schema:GOAL_SCHEMA,revision:0,stage:'identified',evidence:[],sessions:[],exercises:[],observations:'',interpretation:'',hypothesis:'',evaluation:'',coach_decision:'',agent_proposal:null,...v};}
 function proposalRefs(xs){return [...new Map((Array.isArray(xs)?xs:[]).map(x=>({type:txt(x.type,30),id:txt(x.id,100),field:txt(x.field,100),event_ref:txt(x.event_ref,100)||null,quote:txt(x.quote,5000),record_updated_at:txt(x.record_updated_at,80)})).filter(x=>['training','match'].includes(x.type)&&/^[0-9a-f-]{36}$/i.test(x.id)&&x.field).map(x=>[x.type+':'+x.id+':'+x.field+':'+(x.event_ref||''),x])).values()];}
 function saveGoal(old,input,{expected_revision,now=new Date().toISOString()}={}){const prev=teamGoal(old);if(expected_revision!==prev.revision)throw new Error('O objetivo da equipa mudou noutro dispositivo. Atualiza e compara antes de guardar.');if(!STAGES.includes(input.stage))throw new Error('Estado de evolução inválido.');const title=txt(input.title,200);if(!title)throw new Error('Escreve o objetivo da equipa.');const proposal=input.agent_proposal===undefined?prev.agent_proposal:input.agent_proposal,next={schema:GOAL_SCHEMA,revision:prev.revision+1,title,identified_at:input.identified_at||now.slice(0,10),stage:input.stage,evidence:refs(input.evidence),sessions:refs(input.sessions).filter(x=>x.type==='training'||x.type==='match'),exercises:refs(input.exercises).filter(x=>x.type==='exercise'),observations:txt(input.observations,3000),interpretation:txt(input.interpretation,3000),hypothesis:txt(input.hypothesis,3000),evaluation:txt(input.evaluation??prev.evaluation,3000),coach_decision:txt(input.coach_decision,3000),agent_proposal:proposal?{...proposal,status:['proposed','accepted','dismissed'].includes(proposal.status)?proposal.status:'proposed',evidence_refs:proposalRefs(proposal.evidence_refs),rationale:txt(proposal.rationale,3000),prepared_by:txt(proposal.prepared_by,100),prepared_at:proposal.prepared_at||now}:null,updated_at:now,history:[...(prev.history||[]),{stage:prev.stage,title:prev.title,identified_at:prev.identified_at,observations:prev.observations,interpretation:prev.interpretation,hypothesis:prev.hypothesis,evaluation:prev.evaluation||'',coach_decision:prev.coach_decision||'',agent_proposal:clone(prev.agent_proposal),sessions:clone(prev.sessions||[]),evidence:clone(prev.evidence||[]),updated_at:prev.updated_at||null}]};if(['improved','continue','evaluated'].includes(next.stage)&&!next.coach_decision)throw new Error('Regista a decisão explícita do treinador antes de avaliar a evolução.');if(['improved','continue','evaluated'].includes(next.stage)&&!next.evaluation)throw new Error('Regista a avaliação do treinador antes de marcar o objetivo como avaliado.');if(['worked','observed','evaluated','improved','continue'].includes(next.stage)&&!next.sessions.length)throw new Error('Associa pelo menos um treino ou jogo realmente trabalhado.');if(next.agent_proposal?.status==='accepted'&&!next.coach_decision)throw new Error('A aceitação da proposta requer uma decisão explícita do treinador.');return next;}
 root.TeamDevelopment={week,saveWeek,teamGoal,saveGoal,proposalRefs,stages:STAGES,labels:LABELS,monday,schemas:{week:WEEK_SCHEMA,goal:GOAL_SCHEMA}};
 if(typeof module!=='undefined'&&module.exports)module.exports=root.TeamDevelopment;
})(globalThis);
