const {test,expect}=require('@playwright/test');

test.use({serviceWorkers:'block'});

for(const width of [390,1440])test(`jogo termina sem cronómetro e recebe resultado, lance e análise depois · ${width}px`,async({page,context})=>{
 await page.setViewportSize({width,height:844});
 await page.goto('/#/calendario');
 await page.waitForFunction(()=>typeof DB!=='undefined'&&typeof VisionMatchEvents!=='undefined'&&typeof go==='function');
 const fixture=await page.evaluate(async()=>{
  RemoteWorkspace.scheduleSync=()=>{};
  const refs=[],playerIds=[];
  for(let i=0;i<5;i++){const ref=crypto.randomUUID();refs.push(ref);playerIds.push(await DB.criar('jogadores',{team_id:DEFAULT_TEAM_ID,sync_id:ref,nome:'Jogador '+(i+1),numero:i+1,plantel_ativo:true,estado_disponibilidade:'disponivel'}));}
  const id=await DB.criar('jogos',{team_id:DEFAULT_TEAM_ID,sync_id:crypto.randomUUID(),data:'2026-09-26',adversario:'Pós-jogo sem relógio',estado:'agendado',callup:{player_ids:refs,notes:'Convocatória guardada'},lineup:{system:'1-2-1',goalkeeper_id:refs[0],starters:refs.slice(1),substitutes:[]}});
  go('#/equipa/jogo/'+id);return{id,refs,playerIds};
 });
 await expect(page.getByRole('button',{name:'Dar jogo como terminado'})).toBeVisible();
 await context.setOffline(true);
 page.on('dialog',dialog=>dialog.accept());
 await page.getByRole('button',{name:'Dar jogo como terminado'}).click();
 await expect(page).toHaveURL(/focus=players/);
 const beforeResult=await page.evaluate(id=>DB.obter('jogos',id),fixture.id);
 expect(beforeResult.estado).toBe('concluido');
 expect(beforeResult.visual_match?.started_at).toBeFalsy();
 expect(beforeResult.callup.player_ids).toEqual(fixture.refs);
 expect(beforeResult.lineup.goalkeeper_id).toBe(fixture.refs[0]);
 const reports=page.locator('#match-player-reports');
 await expect(reports).toContainText('0 de 5 concluídos · 5 por preencher');
 await expect(reports.locator('[data-match-player-report]')).toHaveCount(5);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 const firstReport=reports.locator('[data-match-player-report]').first();
 await expect(firstReport).toHaveAttribute('open','');
 await firstReport.locator('[name="observation"]').fill('Criou apoio após passe.');
 await firstReport.getByRole('button',{name:'Guardar relatório'}).click();
 await expect(reports).toContainText('1 de 5 concluídos · 4 por preencher');
 const secondReport=reports.locator('[data-match-player-report]').nth(1);
 await expect(secondReport).toHaveAttribute('open','');
 await secondReport.getByRole('button',{name:'Não observado'}).click();
 await expect(reports).toContainText('2 de 5 concluídos · 3 por preencher');
 const savedReports=await page.evaluate(id=>DB.obter('jogos',id),fixture.id);
 expect(savedReports.post_game.player_reports.items).toMatchObject([{player_ref:fixture.refs[0],status:'reported',observation:'Criou apoio após passe.'},{player_ref:fixture.refs[1],status:'not_observed'}]);
 await context.setOffline(false);
 await page.reload();
 await context.setOffline(true);
 await expect(reports).toContainText('2 de 5 concluídos · 3 por preencher');
 const result=page.locator('form[data-form="match-result"]');
 await result.locator('[name="golos_favor"]').fill('2');
 await result.locator('[name="golos_contra"]').fill('1');
 await result.locator('[name="notas"]').fill('A equipa reagiu bem.');
 await result.getByRole('button',{name:'Guardar resultado e notas'}).click();
 await expect(result.locator('[name="golos_favor"]')).toHaveValue('2');
 const events=page.locator('[data-post-match-events]');
 await events.locator('summary').click();
 await events.getByRole('button',{name:'Golo a favor',exact:true}).click();
 const eventForm=events.locator('[data-event-form="record"]');
 await expect(eventForm.locator('[name="at_min"]')).toHaveValue('');
 await eventForm.locator('[name="note"]').fill('Golo visto pelo treinador');
 await eventForm.getByRole('button',{name:'Registar lance'}).click();
 await expect(events.locator('[data-event-feedback]')).toHaveText('Lance guardado neste dispositivo.');
 const saved=await page.evaluate(id=>DB.obter('jogos',id),fixture.id);
 expect(saved.match_events.events[0]).toMatchObject({type:'goal_for',at_ms:null,recorded_post_match:true});
 expect(saved.golos_favor).toBe(2);expect(saved.golos_contra).toBe(1);
 expect(saved.visual_match?.started_at).toBeFalsy();
 await expect(events).toContainText('Minuto não indicado');
 const analysis=page.locator('form[data-form="match-analysis"]');
 await analysis.locator('[name="field_observations"]').fill('Observei apoio após passe no segundo tempo.');
 await analysis.getByRole('button',{name:'Guardar análise',exact:true}).click();
 await expect.poll(()=>page.evaluate(id=>DB.obter('jogos',id).then(row=>row.post_game.analysis?.fields?.observations),fixture.id)).toContain('apoio após passe');
 const report=await page.evaluate(id=>ReportExporter.render('match-report',id),fixture.id);
 expect(report).toContain('Minuto não indicado');
 expect(report).toContain('Criou apoio após passe.');
 expect(report).toContain('Não observado pelo treinador');
 const playerReport=await page.evaluate(id=>ReportExporter.render('player',id),fixture.playerIds[0]);
 expect(playerReport).toContain('Criou apoio após passe.');
 expect(report).toContain('Sem minutos registados');
 expect(report).not.toContain('0:00 · Golo a favor');
 await context.setOffline(false);
});

test('concluir jogo pelo formulário também abre os relatórios dos convocados',async({page})=>{
 await page.goto('/#/calendario');
 await page.waitForFunction(()=>typeof DB!=='undefined'&&typeof go==='function');
 const id=await page.evaluate(async()=>{RemoteWorkspace.scheduleSync=()=>{};const ref=crypto.randomUUID();await DB.criar('jogadores',{team_id:DEFAULT_TEAM_ID,sync_id:ref,nome:'Convocado formulário',plantel_ativo:true,estado_disponibilidade:'disponivel'});const id=await DB.criar('jogos',{team_id:DEFAULT_TEAM_ID,sync_id:crypto.randomUUID(),data:'2026-09-27',adversario:'Fecho no formulário',estado:'agendado',callup:{player_ids:[ref]}});go('#/equipa/jogo/'+id+'/editar');return id;});
 const form=page.locator('form[data-form="match"]');
 await expect(form).toBeVisible();
 await form.locator('[name="estado"]').selectOption('concluido');
 await form.getByRole('button',{name:'Guardar jogo'}).click();
 await expect(page).toHaveURL(new RegExp(`equipa/jogo/${id}\\?focus=players`));
 await expect(page.locator('#match-player-reports')).toContainText('0 de 1 concluídos · 1 por preencher');
 await expect(page.locator('#match-player-reports')).toContainText('Convocado formulário');
});

test('relatório de convocado eliminado usa nome do arquivo da mesma equipa sem cronómetro',async({page})=>{
 await page.goto('/#/calendario');
 await page.waitForFunction(()=>typeof DB!=='undefined'&&typeof deletePlayerPermanently==='function');
 const fixture=await page.evaluate(async()=>{
  RemoteWorkspace.scheduleSync=()=>{};
  const ref=crypto.randomUUID(),playerId=await DB.criar('jogadores',{team_id:DEFAULT_TEAM_ID,sync_id:ref,nome:'Convocado arquivado',plantel_ativo:true,estado_disponibilidade:'disponivel'});
  const matchId=await DB.criar('jogos',{team_id:DEFAULT_TEAM_ID,sync_id:crypto.randomUUID(),data:'2026-09-27',adversario:'Histórico sem relógio',estado:'concluido',callup:{player_ids:[ref]}});
  await deletePlayerPermanently(playerId);
  const foreignArchive=PlayerArchive.snapshot({sync_id:ref,nome:'Nome de outra equipa'},{teamId:'other-team'});
  await DB.criar('workspace_documents',{team_id:'other-team',type:'player_archive',title:'Arquivo externo',body:JSON.stringify(foreignArchive),status:'archived',sync_id:crypto.randomUUID()});
  go('#/equipa/jogo/'+matchId+'?focus=players');
  return{matchId,ref,playerId};
 });
 const report=page.locator('[data-match-player-report="'+fixture.ref+'"]');
 await expect(report.locator('summary strong')).toHaveText('Convocado arquivado');
 await expect(report).not.toContainText('Nome de outra equipa');
 await expect(report).not.toContainText(fixture.ref);
 await expect(page.locator('#match-player-reports')).toContainText('0 de 1 concluídos · 1 por preencher');
 const printable=await page.evaluate(async id=>({sheet:await ReportExporter.render('match-sheet',id),report:await ReportExporter.render('match-report',id)}),fixture.matchId);
 expect(printable.sheet).toContain('Convocado arquivado');
 expect(printable.report).toContain('Convocado arquivado · Por preencher');
 expect(printable.sheet).not.toContain('Nome de outra equipa');
 expect(printable.report).not.toContain('Atleta · '+fixture.ref);
 await expect.poll(()=>page.evaluate(id=>DB.obter('jogadores',id),fixture.playerId)).toBeUndefined();
 page.on('dialog',dialog=>dialog.accept());
 await report.getByRole('button',{name:'Não observado'}).click();
 await expect.poll(()=>page.evaluate(id=>DB.obter('jogos',id).then(row=>row.post_game.player_reports.items[0]),fixture.matchId)).toMatchObject({player_ref:fixture.ref,status:'not_observed'});
});
