const {test,expect}=require('@playwright/test');test.use({serviceWorkers:'block'});
test('season archive streams and projects historical matches and trainings without retaining their large payloads',async({page})=>{
 await page.goto('/');await page.waitForFunction(()=>typeof VisionSeasons!=='undefined'&&typeof router==='function');
 await page.evaluate(async()=>{RemoteWorkspace.scheduleSync=()=>{};const season=VisionSeasons.save(null,{name:'Época carga leve',start_date:'2026-08-01',end_date:'2026-09-30',roster:[],activate:true},{expected_revision:0}),sync=await VisionSeasons.stableIndexId(DEFAULT_TEAM_ID);await DB.criar('workspace_documents',{team_id:DEFAULT_TEAM_ID,type:'season_index',title:'Épocas',body:JSON.stringify(season),status:'ready',sync_id:sync,external_key:'season-index-light-e2e'});const payload=Array.from({length:100},(_,i)=>({minute:i,note:'heavy history payload should not enter the season view '.repeat(4)}));for(let i=0;i<40;i++){const date=new Date(Date.UTC(2026,7,1+i)).toISOString().slice(0,10);await DB.criar('treinos',{team_id:DEFAULT_TEAM_ID,sync_id:crypto.randomUUID(),data:date,objetivo:'Arquivo treino '+i,session:{events:payload},blocos:payload});await DB.criar('jogos',{team_id:DEFAULT_TEAM_ID,sync_id:crypto.randomUUID(),data:date,adversario:'Arquivo jogo '+i,visual_match:{events:payload},notas:'heavy history payload'});}window.seasonCursorCounts={trainings:0,matches:0};const cursor=DB.percorrerIndice.bind(DB);DB.percorrerIndice=function(store,...args){return cursor(store,...args).then(count=>{if(store==='treinos')window.seasonCursorCounts.trainings=count;if(store==='jogos')window.seasonCursorCounts.matches=count;return count;});};const read=DB.porIndice.bind(DB);DB.porIndice=function(store,...args){if(store==='treinos'||store==='jogos')throw new Error('A época tentou materializar o histórico '+store);return read(store,...args);};location.hash='#/epocas';});
 const card=page.locator('.list-item').filter({hasText:'Época carga leve'});await expect(card).toContainText('40 treinos · 40 jogos');await expect(card.getByRole('link',{name:'01/08/2026 · Arquivo treino 0'})).toBeVisible();await expect(card.getByRole('link',{name:'09/09/2026 · vs Arquivo jogo 39'})).toBeVisible();await expect(page.getByText('heavy history payload',{exact:false})).toHaveCount(0);const counts=await page.evaluate(()=>window.seasonCursorCounts);expect(counts.trainings).toBeGreaterThanOrEqual(40);expect(counts.matches).toBeGreaterThanOrEqual(40);
});
test('season archive shows linked training, matches, objectives and weekly evaluation inside the period',async({page})=>{
 await page.goto('/#/epocas');await page.waitForFunction(()=>typeof VisionSeasons!=='undefined'&&typeof TeamDevelopment!=='undefined');
 const refs=await page.evaluate(async()=>{RemoteWorkspace.scheduleSync=()=>{};const player=crypto.randomUUID(),season=VisionSeasons.save(null,{name:'Época detalhe',start_date:'2026-09-01',end_date:'2026-09-30',roster:[{ref:player,name:'Atleta arquivo'}],activate:true},{expected_revision:0}),seasonSync=await VisionSeasons.stableIndexId(DEFAULT_TEAM_ID);await DB.criar('jogadores',{team_id:DEFAULT_TEAM_ID,sync_id:player,nome:'Atleta arquivo'});await DB.criar('workspace_documents',{team_id:DEFAULT_TEAM_ID,type:'season_index',title:'Épocas',body:JSON.stringify(season),status:'ready',sync_id:seasonSync,external_key:'season-index-detail'});const trainingRef=crypto.randomUUID(),matchRef=crypto.randomUUID(),trainingId=await DB.criar('treinos',{team_id:DEFAULT_TEAM_ID,sync_id:trainingRef,data:'2026-09-10',objetivo:'Apoio após passe'}),matchId=await DB.criar('jogos',{team_id:DEFAULT_TEAM_ID,sync_id:matchRef,data:'2026-09-20',adversario:'Jogo do arquivo',golos_favor:2,golos_contra:1}),goal=TeamDevelopment.saveGoal(null,{title:'Pressão após perda',identified_at:'2026-08-20',stage:'worked',sessions:[{type:'training',id:trainingRef}],worked_sessions:[{type:'training',id:trainingRef}],evidence:[{type:'training',id:trainingRef}],evaluation:'Recuperámos mais depressa.'},{expected_revision:0}),week=TeamDevelopment.saveWeek(null,{week_start:'2026-09-07',objective:'Apoiar na construção',training1:trainingRef,match:matchRef,evaluation:{summary:'Apoio observado no jogo.'}},{expected_revision:0});await DB.criar('workspace_documents',{team_id:DEFAULT_TEAM_ID,type:'team_goal',title:goal.title,body:JSON.stringify(goal),status:'ready',external_key:'goal-season-detail'});await DB.criar('workspace_documents',{team_id:DEFAULT_TEAM_ID,type:'weekly_plan',title:'Semana arquivo',body:JSON.stringify(week),status:'ready',external_key:'week-season-detail'});await router();return{trainingId,matchId};});
 const seasonCard=page.locator('.list-item').filter({hasText:'Época detalhe'});await expect(seasonCard).toContainText('1 treinos · 1 jogos · 1 objetivos');await expect(seasonCard.getByRole('link',{name:'10/09/2026 · Apoio após passe'})).toHaveAttribute('href',`#/consulta/${refs.trainingId}`);await expect(seasonCard.getByRole('link',{name:'20/09/2026 · vs Jogo do arquivo · 2–1'})).toHaveAttribute('href',`#/equipa/jogo/${refs.matchId}`);await expect(seasonCard.getByRole('link',{name:'Pressão após perda'})).toBeVisible();await expect(seasonCard.getByRole('link',{name:'07/09/2026 · Apoiar na construção'})).toBeVisible();await expect(seasonCard).toContainText('Apoio observado no jogo.');
});
test('season archive includes a goal tied to an in-period worked session alone',async({page})=>{
 await page.goto('/#/epocas');await page.waitForFunction(()=>typeof VisionSeasons!=='undefined'&&typeof TeamDevelopment!=='undefined');
 await page.evaluate(async()=>{RemoteWorkspace.scheduleSync=()=>{};const season=VisionSeasons.save(null,{name:'Época da sessão trabalhada',start_date:'2026-09-01',end_date:'2026-09-30',roster:[],activate:true},{expected_revision:0}),sync=await VisionSeasons.stableIndexId(DEFAULT_TEAM_ID);await DB.criar('workspace_documents',{team_id:DEFAULT_TEAM_ID,type:'season_index',title:'Épocas',body:JSON.stringify(season),status:'ready',sync_id:sync,external_key:'season-index-worked-only'});const training=crypto.randomUUID();await DB.criar('treinos',{team_id:DEFAULT_TEAM_ID,sync_id:training,data:'2026-09-17',objetivo:'Trabalho explicitamente assinalado',status:'completed',session:{status:'completed'}});const goal=TeamDevelopment.saveGoal(null,{title:'Apoio após passe',identified_at:'2026-08-20',stage:'worked',sessions:[],worked_sessions:[{type:'training',id:training}],evidence:[],evaluation:'Trabalhado nesta época.'},{expected_revision:0});await DB.criar('workspace_documents',{team_id:DEFAULT_TEAM_ID,type:'team_goal',title:goal.title,body:JSON.stringify(goal),status:'ready',external_key:'team-goal-worked-only'});await router();});
 const seasonCard=page.locator('.list-item').filter({hasText:'Época da sessão trabalhada'});await expect(seasonCard).toContainText('1 objetivos');await expect(seasonCard.getByRole('link',{name:'Apoio após passe'})).toBeVisible();
});
test('season archive snapshots roster, activates without deleting history, and exports within its date range',async({page,context})=>{
 await page.goto('/#/epocas');await page.waitForFunction(()=>typeof VisionSeasons!=='undefined'&&typeof router==='function');
 const playerId=await page.evaluate(async()=>{RemoteWorkspace.scheduleSync=()=>{};return DB.criar('jogadores',{team_id:DEFAULT_TEAM_ID,sync_id:crypto.randomUUID(),nome:'Atleta Época',numero:8,posicao:'Ala',ativo:true});});
 await page.evaluate(()=>router());await context.setOffline(true);const form=page.locator('form[data-form="season"]');await form.locator('[name="name"]').fill('Época E2E');await form.locator('[name="start_date"]').fill('2026-08-01');await form.locator('[name="end_date"]').fill('2027-07-31');await expect(form.getByLabel('Atleta Época · #8')).toBeChecked();await form.getByRole('button',{name:'Guardar época'}).click();await expect(page.getByText('Época E2E · Ativa')).toBeVisible();
 const linkedActivity=await page.evaluate(async()=>{const document=(await WorkspaceStore.listDocuments(DEFAULT_TEAM_ID,{includeArchived:true})).find(x=>x.type==='season_index');const activity=(await WorkspaceStore.listActivity(DEFAULT_TEAM_ID,100)).find(x=>x.action==='updated_seasons');return{entityId:activity?.entity_id,documentSyncId:document?.sync_id};});expect(linkedActivity.entityId).toBe(linkedActivity.documentSyncId);expect(linkedActivity.entityId).not.toBe('season-index:default');
 const dataset=await page.evaluate(async(playerId)=>{const p=await DB.obter('jogadores',playerId),season=VisionSeasons.state((await WorkspaceStore.listDocuments(DEFAULT_TEAM_ID,{includeArchived:true})).find(d=>d.type==='season_index')).items[0],inRef=crypto.randomUUID(),outRef=crypto.randomUUID();const inSeason=await DB.criar('treinos',{team_id:DEFAULT_TEAM_ID,sync_id:inRef,data:'2026-09-02',objetivo:'Época treino',session:{attendance:[{player_ref:p.sync_id,status:'present'}]}});await DB.criar('treinos',{team_id:DEFAULT_TEAM_ID,sync_id:crypto.randomUUID(),data:'2026-09-03',objetivo:'Estado por marcar',session:{attendance:[{player_ref:p.sync_id,status:'unknown'}]}});const outside=await DB.criar('treinos',{team_id:DEFAULT_TEAM_ID,sync_id:outRef,data:'2026-07-02',objetivo:'Anterior treino',session:{attendance:[{player_ref:p.sync_id,status:'present'}]}});let goals=PlayerGoals.apply(p,{type:'save',expected_revision:0,goal:{id:crypto.randomUUID(),title:'Objetivo da época',started_at:'2026-09-01',status:'active',evidence_refs:[{type:'training',id:inRef},{type:'training',id:outRef}],exercise_refs:[],notes:''}});goals=PlayerGoals.apply(goals,{type:'save',expected_revision:1,goal:{id:crypto.randomUUID(),title:'Objetivo anterior',started_at:'2026-07-01',status:'completed',evidence_refs:[],exercise_refs:[],notes:''}});await DB.modificar('jogadores',playerId,current=>({...current,development_goals:goals.development_goals}));return{ref:p.sync_id,season,training:inSeason,outside};},playerId);
 await page.evaluate(()=>router());
 const report=await page.evaluate(async({id,seasonId})=>ReportExporter.render('player',id,{seasonId}),{id:playerId,seasonId:dataset.season.id});expect(report).toContain('Época E2E');expect(report).toContain('02/09/2026 · Presente');expect(report).toContain('Treinos com estado de presença registado: 1');expect(report).toContain('Presenças/atrasos registados: 1');expect(report).toContain('Objetivo da época');expect(report).toContain('02/07/2026 · Anterior treino · fora do período');expect(report).not.toContain('Objetivo anterior');expect(report).not.toContain('Estado por marcar');expect(report).not.toContain('Presente · Estado');
 await context.setOffline(false);
});

test('editing a season preserves a permanently removed athlete and exports the archived player report',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/#/epocas');await page.waitForFunction(()=>typeof VisionSeasons!=='undefined'&&typeof PlayerArchive!=='undefined'&&typeof ReportExporter!=='undefined');
 const refs=await page.evaluate(async()=>{RemoteWorkspace.scheduleSync=()=>{};const playerRef=crypto.randomUUID(),playerId=await DB.criar('jogadores',{team_id:DEFAULT_TEAM_ID,sync_id:playerRef,nome:'Atleta removido',numero:9,escalao:'Sub-8',ativo:true}),player=await DB.obter('jogadores',playerId),seasonId=crypto.randomUUID(),seasonIndex=VisionSeasons.save(null,{id:seasonId,name:'Época a preservar',start_date:'2026-08-01',end_date:'2027-07-31',roster:[{ref:playerRef,name:player.nome,number:player.numero}],activate:true},{expected_revision:0}),seasonSync=await VisionSeasons.stableIndexId(DEFAULT_TEAM_ID),stamp='2026-09-22T10:00:00.000Z';await DB.criar('workspace_documents',{team_id:DEFAULT_TEAM_ID,type:'season_index',title:'Arquivo de épocas',body:JSON.stringify(seasonIndex),status:'ready',external_key:'season-index:archive-player-e2e',sync_id:seasonSync,created_at:stamp,updated_at:stamp});const matchRef=crypto.randomUUID(),trainingRef=crypto.randomUUID(),goals=PlayerGoals.apply(player,{type:'save',expected_revision:0,goal:{id:crypto.randomUUID(),title:'Objetivo histórico',started_at:'2026-09-02',status:'active',evidence_refs:[],exercise_refs:[],notes:'Registo do treinador'}});await DB.modificar('jogadores',playerId,current=>({...current,development_goals:goals.development_goals}));const current=await DB.obter('jogadores',playerId),archive=PlayerArchive.snapshot(current,{teamId:DEFAULT_TEAM_ID,teamName:'Equipa de teste',archivedAt:stamp}),archiveSync=await PlayerArchive.stableId(DEFAULT_TEAM_ID,playerRef);await DB.criarWorkspaceDocumentSeAusente({team_id:DEFAULT_TEAM_ID,type:'player_archive',title:'Histórico · Atleta removido',body:JSON.stringify(archive),status:'archived',external_key:'player-archive:'+DEFAULT_TEAM_ID+':'+playerRef,sync_id:archiveSync});await DB.criar('treinos',{team_id:DEFAULT_TEAM_ID,sync_id:trainingRef,data:'2026-09-05',objetivo:'Passe e apoio',session:{attendance:[{player_ref:playerRef,status:'present'}]}});await DB.criar('jogos',{team_id:DEFAULT_TEAM_ID,sync_id:matchRef,data:'2026-09-10',adversario:'Rivais',callup:{player_ids:[playerRef]},visual_match:{schema:'vision-match-visual@1',revision:0,status:'not_started',period:1,elapsed_ms:0,roster:[],events:[]}});await DB.apagar('jogadores',playerId);await router();return{playerRef,seasonId};});
 const card=page.locator('.list-item').filter({hasText:'Época a preservar'});await expect(card).toContainText('Atleta removido');await card.getByRole('button',{name:'Editar'}).click();const form=page.locator('form[data-form="season"]');await expect(form.getByLabel('Atleta removido · #9 · registo histórico arquivado')).toBeChecked();await form.locator('[name="name"]').fill('Época editada');await form.getByRole('button',{name:'Guardar época'}).click();
 const edited=page.locator('.list-item').filter({hasText:'Época editada'});await expect(edited).toContainText('Plantel da época: Atleta removido');const saved=await page.evaluate(async id=>{const doc=(await WorkspaceStore.listDocuments(DEFAULT_TEAM_ID,{includeArchived:true})).find(x=>x.type==='season_index');return VisionSeasons.state(doc).items.find(x=>x.id===id);},refs.seasonId);expect(saved.roster).toEqual([{ref:refs.playerRef,name:'Atleta removido',number:9}]);
 const popupPromise=page.waitForEvent('popup');await edited.getByRole('button',{name:/Relatório · Atleta removido/}).click();const popup=await popupPromise;await expect(popup.locator('h1')).toHaveText('Relatório do atleta');await expect(popup.getByText('Origem histórica')).toBeVisible();await expect(popup.getByText('Convocatórias: 1')).toBeVisible();await expect(popup.getByText('Presenças/atrasos registados: 1')).toBeVisible();await expect(popup.getByText('Objetivo histórico')).toBeVisible();await popup.close();
});

test('season page exposes complete prior date and roster snapshots after an edit',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/#/epocas');await page.waitForFunction(()=>typeof VisionSeasons!=='undefined'&&typeof router==='function');
 await page.evaluate(async()=>{RemoteWorkspace.scheduleSync=()=>{};const ref=crypto.randomUUID(),first=VisionSeasons.save(null,{name:'Época anterior recuperável',start_date:'2025-08-01',end_date:'2026-07-31',roster:[{ref,name:'Atleta versão antiga',number:7}],activate:true},{expected_revision:0,now:'2025-08-01T10:00:00Z'}),sync=await VisionSeasons.stableIndexId(DEFAULT_TEAM_ID),id=await DB.criar('workspace_documents',{team_id:DEFAULT_TEAM_ID,type:'season_index',title:'Épocas',body:JSON.stringify(first),status:'ready',sync_id:sync,external_key:'season-index-full-history-e2e'}),doc=await DB.obter('workspace_documents',id),next=VisionSeasons.save(doc,{id:first.items[0].id,name:'Época atualizada',start_date:'2025-09-01',end_date:'2026-06-30',roster:[{ref,name:'Atleta versão nova',number:8}]},{expected_revision:1,now:'2025-09-01T10:00:00Z'});await DB.modificar('workspace_documents',id,current=>({...current,body:JSON.stringify(next),updated_at:'2025-09-01T10:00:00Z'}));await router();});
 const history=page.locator('details').filter({hasText:'Versões anteriores do arquivo · 2'});await expect(history).toHaveCount(1);await history.locator('summary').click();await expect(history).toContainText('01/08/2025');await expect(history).toContainText('31/07/2026');await expect(history).toContainText('Atleta versão antiga');await expect(history).not.toContainText('Atleta versão nova');
});
