const {test,expect}=require('@playwright/test');test.use({serviceWorkers:'block'});
test('season archive snapshots roster, activates without deleting history, and exports within its date range',async({page,context})=>{
 await page.goto('/#/epocas');await page.waitForFunction(()=>typeof VisionSeasons!=='undefined'&&typeof router==='function');
 const playerId=await page.evaluate(async()=>{RemoteWorkspace.scheduleSync=()=>{};return DB.criar('jogadores',{team_id:DEFAULT_TEAM_ID,sync_id:crypto.randomUUID(),nome:'Atleta Época',numero:8,posicao:'Ala',ativo:true});});
 await page.evaluate(()=>router());await context.setOffline(true);const form=page.locator('form[data-form="season"]');await form.locator('[name="name"]').fill('Época E2E');await form.locator('[name="start_date"]').fill('2026-08-01');await form.locator('[name="end_date"]').fill('2027-07-31');await expect(form.getByLabel('Atleta Época · #8')).toBeChecked();await form.getByRole('button',{name:'Guardar época'}).click();await expect(page.getByText('Época E2E · Ativa')).toBeVisible();
 const dataset=await page.evaluate(async(playerId)=>{const p=await DB.obter('jogadores',playerId),season=VisionSeasons.state((await WorkspaceStore.listDocuments(DEFAULT_TEAM_ID,{includeArchived:true})).find(d=>d.type==='season_index')).items[0],inRef=crypto.randomUUID(),outRef=crypto.randomUUID();const inSeason=await DB.criar('treinos',{team_id:DEFAULT_TEAM_ID,sync_id:inRef,data:'2026-09-02',objetivo:'Época treino',session:{attendance:[{player_ref:p.sync_id,status:'present'}]}});await DB.criar('treinos',{team_id:DEFAULT_TEAM_ID,sync_id:crypto.randomUUID(),data:'2026-09-03',objetivo:'Estado por marcar',session:{attendance:[{player_ref:p.sync_id,status:'unknown'}]}});const outside=await DB.criar('treinos',{team_id:DEFAULT_TEAM_ID,sync_id:outRef,data:'2026-07-02',objetivo:'Anterior treino',session:{attendance:[{player_ref:p.sync_id,status:'present'}]}});let goals=PlayerGoals.apply(p,{type:'save',expected_revision:0,goal:{id:crypto.randomUUID(),title:'Objetivo da época',started_at:'2026-09-01',status:'active',evidence_refs:[{type:'training',id:inRef},{type:'training',id:outRef}],exercise_refs:[],notes:''}});goals=PlayerGoals.apply(goals,{type:'save',expected_revision:1,goal:{id:crypto.randomUUID(),title:'Objetivo anterior',started_at:'2026-07-01',status:'completed',evidence_refs:[],exercise_refs:[],notes:''}});await DB.modificar('jogadores',playerId,current=>({...current,development_goals:goals.development_goals}));return{ref:p.sync_id,season,training:inSeason,outside};},playerId);
 await page.evaluate(()=>router());
 const report=await page.evaluate(async({id,seasonId})=>ReportExporter.render('player',id,{seasonId}),{id:playerId,seasonId:dataset.season.id});expect(report).toContain('Época E2E');expect(report).toContain('02/09/2026 · Presente');expect(report).toContain('Treinos com estado de presença registado: 1');expect(report).toContain('Presenças/atrasos registados: 1');expect(report).toContain('Objetivo da época');expect(report).toContain('02/07/2026 · Anterior treino · fora do período');expect(report).not.toContain('Objetivo anterior');expect(report).not.toContain('Estado por marcar');expect(report).not.toContain('Presente · Estado');
 await context.setOffline(false);
});
