const {test,expect}=require('@playwright/test');test.use({serviceWorkers:'block'});
test('team development projects historical match and training records through cursors',async({page})=>{
 await page.goto('/');await page.waitForFunction(()=>typeof router==='function'&&typeof TeamDevelopment!=='undefined');
 await page.evaluate(async()=>{RemoteWorkspace.scheduleSync=()=>{};const payload=Array.from({length:80},(_,i)=>({event:i,note:'large evolution payload should not stay in memory '.repeat(4)}));for(let i=0;i<50;i++){const date=new Date(Date.UTC(2034,0,1+i)).toISOString().slice(0,10);await DB.criar('treinos',{team_id:DEFAULT_TEAM_ID,sync_id:crypto.randomUUID(),data:date,objetivo:'Evolução treino '+i,blocos:payload,session:{status:i===49?'completed':'not_started',events:payload},status:i===49?'completed':'ready'});await DB.criar('jogos',{team_id:DEFAULT_TEAM_ID,sync_id:crypto.randomUUID(),data:date,adversario:'Evolução jogo '+i,visual_match:{status:i===49?'completed':'not_started',events:payload},notas:JSON.stringify(payload),estado:i===49?'concluido':'agendado'});}window.evolutionCursorCounts={trainings:0,matches:0};const cursor=DB.percorrerIndice.bind(DB);DB.percorrerIndice=function(store,...args){return cursor(store,...args).then(count=>{if(store==='treinos')window.evolutionCursorCounts.trainings=count;if(store==='jogos')window.evolutionCursorCounts.matches=count;return count;});};const read=DB.porIndice.bind(DB);DB.porIndice=function(store,...args){if(store==='treinos'||store==='jogos')throw new Error('A evolução tentou carregar o histórico completo: '+store);return read(store,...args);};location.hash='#/evolucao';});
 const trainingInputs=page.locator('form[data-form="team-goal"] input[name="session_refs"][value^="training:"]'),matchInputs=page.locator('form[data-form="team-goal"] input[name="session_refs"][value^="match:"]');await expect(trainingInputs).toHaveCount(50);await expect(matchInputs).toHaveCount(50);await expect(page.locator('form[data-form="team-goal"] input[name="worked_session_refs"][value^="training:"]')).toHaveCount(1);await expect(page.locator('form[data-form="team-goal"] input[name="worked_session_refs"][value^="match:"]')).toHaveCount(1);await expect(page.getByText('large evolution payload',{exact:false})).toHaveCount(0);const counts=await page.evaluate(()=>window.evolutionCursorCounts);expect(counts.trainings).toBeGreaterThanOrEqual(50);expect(counts.matches).toBeGreaterThanOrEqual(50);
});
test('weekly plans render newest first and identify the current week',async({page})=>{
 await page.goto('/#/evolucao');await page.waitForFunction(()=>typeof TeamDevelopment!=='undefined'&&typeof RemoteWorkspace!=='undefined');
 const expected=await page.evaluate(async()=>{RemoteWorkspace.scheduleSync=()=>{};const current=TeamDevelopment.monday(new Date().toISOString().slice(0,10)),shift=(value,days)=>{const d=new Date(value+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);},weeks=[[shift(current,-14),'Semana antiga'],[shift(current,7),'Semana seguinte'],[current,'Semana atual']];for(const [start,title] of weeks){const value=TeamDevelopment.saveWeek(null,{week_start:start,objective:title,links:[],evaluation:{}},{expected_revision:0});await DB.criar('workspace_documents',{team_id:DEFAULT_TEAM_ID,type:'weekly_plan',title,body:JSON.stringify(value),status:'ready',external_key:'week-sort:'+start,sync_id:crypto.randomUUID(),updated_at:'week-sort-v1'});}
 await router();return{titles:[`Semana de ${fmtDate(weeks[1][0])} · Próxima`,`Semana de ${fmtDate(weeks[2][0])} · Esta semana`,`Semana de ${fmtDate(weeks[0][0])} · Anterior`]};});
 const titles=page.locator('section.section').filter({has:page.getByRole('heading',{name:'Planos semanais'})}).locator('.list-item .title');await expect(titles).toHaveText(expected.titles);
});
test('editing a weekly plan changes its identity and refuses an occupied week',async({page})=>{
 await page.goto('/#/evolucao');await page.waitForFunction(()=>typeof TeamDevelopment!=='undefined'&&typeof RemoteWorkspace!=='undefined');
 const ids=await page.evaluate(async()=>{RemoteWorkspace.scheduleSync=()=>{};const make=async(start,title)=>{const value=TeamDevelopment.saveWeek(null,{week_start:start,objective:title},{expected_revision:0}),id=await DB.criar('workspace_documents',{team_id:DEFAULT_TEAM_ID,type:'weekly_plan',title,body:JSON.stringify(value),status:'ready',target_date:value.week_start,external_key:'team-week:'+value.week_start,sync_id:crypto.randomUUID(),updated_at:'weekly-v1'});return id;};const first=await make('2026-09-21','Semana A'),second=await make('2026-09-28','Semana B');await router();return{first,second};});
 const edit=page.locator('[data-action="edit-team-record"][data-kind="week"][data-id="'+ids.first+'"]');await edit.click();const form=page.locator('form[data-form="team-week"]');await expect(form.locator('[name="doc_id"]')).toHaveValue(String(ids.first));await expect(form.locator('[name="week_start"]')).toHaveValue('2026-09-21');await form.locator('[name="week_start"]').fill('2026-09-14');await form.locator('[name="objective"]').fill('Semana A movida');await form.getByRole('button',{name:'Guardar semana'}).click();
 await expect.poll(()=>page.evaluate(async id=>{const doc=await DB.obter('workspace_documents',id);return doc.external_key;},ids.first)).toBe('team-week:2026-09-14');
 await page.waitForFunction(()=>typeof routerRunning==='boolean'&&!routerRunning);
 await page.locator('[data-action="edit-team-record"][data-kind="week"][data-id="'+ids.first+'"]').click();await expect(form.locator('[name="doc_id"]')).toHaveValue(String(ids.first));await expect(form.locator('[name="week_start"]')).toHaveValue('2026-09-14');await form.locator('[name="week_start"]').fill('2026-09-28');await form.locator('[name="objective"]').fill('Semana A em conflito');await form.getByRole('button',{name:'Guardar semana'}).click();await expect(form.locator('[data-team-feedback]')).toContainText('Já existe um plano para esta semana');
 const rows=await page.evaluate(async()=>DB.porIndice('workspace_documents','team_id',DEFAULT_TEAM_ID).then(xs=>xs.filter(x=>x.type==='weekly_plan').map(x=>({id:x.id,key:x.external_key,target_date:x.target_date,week_start:JSON.parse(x.body).week_start,objective:JSON.parse(x.body).objective}))));expect(rows).toHaveLength(2);expect(rows.find(x=>x.id===ids.first)).toMatchObject({key:'team-week:2026-09-14',target_date:'2026-09-14',week_start:'2026-09-14',objective:'Semana A movida'});expect(rows.find(x=>x.id===ids.second).key).toBe('team-week:2026-09-28');
});
test('weekly progression proposals require coach action and revalidate current evidence in the app',async({page})=>{
 await page.goto('/#/evolucao');await page.waitForFunction(()=>typeof TeamDevelopment!=='undefined'&&typeof RemoteWorkspace!=='undefined');
 const ids=await page.evaluate(async()=>{RemoteWorkspace.scheduleSync=()=>{};RemoteWorkspace.status=async()=>({configured:false});window.__weeklyDialogs=[];window.confirm=message=>{window.__weeklyDialogs.push({type:'confirm',message});return true;};window.alert=message=>window.__weeklyDialogs.push({type:'alert',message});const make=async(ref,date)=>{const trainingId=crypto.randomUUID(),training={team_id:DEFAULT_TEAM_ID,sync_id:trainingId,data:date,objetivo:'Apoio após passe',updated_at:'source-v1',review:{status:'done',continua:'Apoio irregular'},session:{status:'completed'}};const localTrainingId=await DB.criar('treinos',training),savedTraining=await DB.obter('treinos',localTrainingId);const value=TeamDevelopment.saveWeek(null,{week_start:date,objective:'Manter passe e introduzir oposição',relation_note:'Aumentar pressão',agent_proposal:{status:'proposed',proposal_key:ref,rationale:'O apoio continua irregular segundo a avaliação registada.',hypothesis:'Verificar se permanece disponível sob oposição.',prepared_by:'Head Coach',evidence_refs:[{type:'training',id:trainingId,field:'review.continua',quote:'Apoio irregular',record_updated_at:savedTraining.updated_at}]}},{expected_revision:0});const id=await DB.criar('workspace_documents',{team_id:DEFAULT_TEAM_ID,type:'weekly_plan',title:'Proposta semanal',target_date:value.week_start,body:JSON.stringify(value),status:'ready',external_key:'team-week:'+value.week_start,sync_id:crypto.randomUUID(),created_by:'agent',updated_at:'doc-v1'});return{id,trainingId};};const current=TeamDevelopment.monday(new Date().toISOString().slice(0,10)),later=new Date(current+'T12:00:00Z');later.setUTCDate(later.getUTCDate()+7);const stale=await make('stale',current),approved=await make('approved',later.toISOString().slice(0,10)),staleTrainingId=stale.trainingId;await DB.modificar('treinos',(await DB.porIndice('treinos','team_id',DEFAULT_TEAM_ID)).find(x=>x.sync_id===stale.trainingId).id,row=>({...row,updated_at:'source-v2',review:{status:'done',continua:'Apoio observado como melhorado'}}));const changed=await DB.porIndice('treinos','team_id',DEFAULT_TEAM_ID);await router();return{stale:stale.id,approved:approved.id,staleTraining:changed.find(x=>x.sync_id===staleTrainingId),trainingCount:changed.length};});
 expect(ids.staleTraining.updated_at).not.toBe('source-v1');expect(ids.staleTraining.review.continua).toBe('Apoio observado como melhorado');await expect(page.getByRole('heading',{name:'Propostas do Head Coach · por rever'})).toBeVisible();await expect(page.getByText('A proposta ainda não foi aprovada e não criou treinos.').first()).toBeVisible();
 await page.locator('[data-action="accept-weekly-plan-proposal"][data-id="'+ids.stale+'"]').click();await expect.poll(()=>page.evaluate(()=>window.__weeklyDialogs.length)).toBe(2);const staleResult=await page.evaluate(async id=>({status:TeamDevelopment.week(await DB.obter('workspace_documents',id)).agent_proposal.status,dialogs:window.__weeklyDialogs}),ids.stale);expect(staleResult.dialogs.at(-1).message).toContain('Uma evidência da proposta já não corresponde');expect(staleResult.status).toBe('proposed');
 await page.locator('[data-action="accept-weekly-plan-proposal"][data-id="'+ids.approved+'"]').click();await expect.poll(()=>page.evaluate(async id=>TeamDevelopment.week(await DB.obter('workspace_documents',id)).agent_proposal.status==='accepted'||window.__weeklyDialogs.length>=4,ids.approved)).toBe(true);const approvalResult=await page.evaluate(async id=>({value:TeamDevelopment.week(await DB.obter('workspace_documents',id)),dialogs:window.__weeklyDialogs}),ids.approved);await expect.poll(()=>page.evaluate(async id=>TeamDevelopment.week(await DB.obter('workspace_documents',id)).agent_proposal.status,ids.approved)).toBe('accepted');expect(approvalResult.value.agent_proposal.coach_decision).toContain('explicitamente');expect(await page.evaluate(()=>DB.porIndice('treinos','team_id',DEFAULT_TEAM_ID).then(rows=>rows.length))).toBe(ids.trainingCount);
});
test('malformed saved weekly reference stays visible and requires explicit replacement or removal',async({page})=>{
 await page.goto('/#/evolucao');await page.waitForFunction(()=>typeof TeamDevelopment!=='undefined'&&typeof RemoteWorkspace!=='undefined');
 const fixture=await page.evaluate(async()=>{RemoteWorkspace.scheduleSync=()=>{};const value={schema:TeamDevelopment.schemas.week,revision:2,week_start:'2026-09-21',objective:'Plano legado com ligação inválida',training1:'local-id-from-old-browser',training2:null,match:null,links:[],evaluation:{summary:'',evidence:[]}};const id=await DB.criar('workspace_documents',{team_id:DEFAULT_TEAM_ID,type:'weekly_plan',title:'Semana · 21/09/2026',body:JSON.stringify(value),status:'ready',target_date:value.week_start,external_key:'team-week:2026-09-21',sync_id:crypto.randomUUID(),updated_at:'weekly-legacy-v1'});await router();return id;});
 await page.locator('[data-action="edit-team-record"][data-kind="week"][data-id="'+fixture+'"]').click();const form=page.locator('form[data-form="team-week"]'),training1=form.locator('[name="training1"]');await expect(training1).toHaveValue('local-id-from-old-browser');await expect(training1.locator('option:checked')).toContainText('Referência guardada indisponível');
 await form.getByRole('button',{name:'Guardar semana'}).click();await expect(form.locator('[data-team-feedback]')).toContainText('não é um UUID válido');let stored=await page.evaluate(async()=>{const doc=await DB.porIndice('workspace_documents','team_id',DEFAULT_TEAM_ID).then(rows=>rows.find(row=>row.external_key==='team-week:2026-09-21'));return{body:JSON.parse(doc.body),updated_at:doc.updated_at};});expect(stored.body.training1).toBe('local-id-from-old-browser');expect(stored.updated_at).toBe('weekly-legacy-v1');
 await training1.selectOption('');await expect(training1).toHaveValue('');await form.getByRole('button',{name:'Guardar semana'}).click();await expect(form.locator('[data-team-feedback]')).toBeHidden();await expect(page.getByText('Plano legado com ligação inválida')).toBeVisible();stored=await page.evaluate(async()=>{const doc=await DB.porIndice('workspace_documents','team_id',DEFAULT_TEAM_ID).then(rows=>rows.find(row=>row.external_key==='team-week:2026-09-21'));return{body:JSON.parse(doc.body),updated_at:doc.updated_at};});expect(stored.body.training1).toBe(null);expect(stored.updated_at).not.toBe('weekly-legacy-v1');
});
test('malformed team-goal references stay visible until the coach explicitly removes them',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/#/evolucao');await page.waitForFunction(()=>typeof TeamDevelopment!=='undefined'&&typeof RemoteWorkspace!=='undefined');
 const fixture=await page.evaluate(async()=>{RemoteWorkspace.scheduleSync=()=>{};const value={schema:TeamDevelopment.schemas.goal,revision:1,title:'Objetivo com referências corrompidas',identified_at:'2026-09-20',stage:'identified',sessions:[{type:'training',id:'local-goal-session'}],worked_sessions:[{type:'match',id:'local-goal-worked'}],evidence:[{type:'memory',id:'local-goal-evidence'}],exercises:[{type:'exercise',id:'local-goal-exercise'}],observations:'Facto preservado',interpretation:'',hypothesis:'',evaluation:'',coach_decision:'',history:[]};const id=await DB.criar('workspace_documents',{team_id:DEFAULT_TEAM_ID,type:'team_goal',title:value.title,body:JSON.stringify(value),status:'ready',target_date:value.identified_at,external_key:'team-goal:malformed-reference-e2e',sync_id:crypto.randomUUID(),updated_at:'team-goal-legacy-v1'});await router();return id;});
 await page.locator('[data-action="edit-team-record"][data-kind="goal"][data-id="'+fixture+'"]').click();const form=page.locator('form[data-form="team-goal"]');for(const [name,value] of [['session_refs','training:local-goal-session'],['worked_session_refs','match:local-goal-worked'],['evidence_refs','memory:local-goal-evidence'],['exercise_refs','local-goal-exercise']]){const input=form.locator('[name="'+name+'"][value="'+value+'"]');await expect(input).toBeChecked();await expect(input.locator('xpath=..')).toContainText('Ligação guardada sem origem disponível');}expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await form.getByRole('button',{name:'Guardar objetivo'}).click();await expect(form.locator('[data-team-feedback]')).toContainText('Só podes contar sessões concluídas');let stored=await page.evaluate(async()=>{const doc=await DB.porIndice('workspace_documents','team_id',DEFAULT_TEAM_ID).then(rows=>rows.find(row=>row.external_key==='team-goal:malformed-reference-e2e'));return{body:JSON.parse(doc.body),updated_at:doc.updated_at};});expect(stored.body.sessions[0].id).toBe('local-goal-session');expect(stored.body.worked_sessions[0].id).toBe('local-goal-worked');expect(stored.body.evidence[0].id).toBe('local-goal-evidence');expect(stored.body.exercises[0].id).toBe('local-goal-exercise');expect(stored.updated_at).toBe('team-goal-legacy-v1');
 for(const name of ['session_refs','worked_session_refs','evidence_refs','exercise_refs'])await form.locator('[name="'+name+'"][data-unavailable-reference="true"]').setChecked(false,{force:true});await form.getByRole('button',{name:'Guardar objetivo'}).click();await expect(form.locator('[data-team-feedback]')).toBeHidden();stored=await page.evaluate(async()=>{const doc=await DB.porIndice('workspace_documents','team_id',DEFAULT_TEAM_ID).then(rows=>rows.find(row=>row.external_key==='team-goal:malformed-reference-e2e'));return{body:JSON.parse(doc.body),updated_at:doc.updated_at};});expect(stored.body.sessions).toEqual([]);expect(stored.body.worked_sessions).toEqual([]);expect(stored.body.evidence).toEqual([]);expect(stored.body.exercises).toEqual([]);expect(stored.body.history[0].title).toBe('Objetivo com referências corrompidas');expect(stored.updated_at).not.toBe('team-goal-legacy-v1');
});
test('editing an old team goal preserves unknown worked-session history',async({page})=>{
 await page.goto('/#/evolucao');await page.waitForFunction(()=>typeof TeamDevelopment!=='undefined'&&typeof RemoteWorkspace!=='undefined');
 const id=await page.evaluate(async()=>{RemoteWorkspace.scheduleSync=()=>{};const value={schema:TeamDevelopment.schemas.goal,revision:2,title:'Objetivo histórico',identified_at:'2026-09-01',stage:'planned',sessions:[{type:'training',id:'11111111-1111-4111-8111-111111111111'}],worked_sessions:null,evidence:[],exercises:[],observations:'Facto original',interpretation:'',hypothesis:'',evaluation:'',coach_decision:'',history:[]};return DB.criar('workspace_documents',{team_id:DEFAULT_TEAM_ID,type:'team_goal',title:value.title,body:JSON.stringify(value),status:'ready',target_date:value.identified_at,external_key:'team-goal:legacy-worked-history-e2e',sync_id:crypto.randomUUID(),updated_at:'team-goal-legacy-history-v1'}).then(async id=>{await router();return id;});});
 await page.locator('[data-action="edit-team-record"][data-kind="goal"][data-id="'+id+'"]').click();const form=page.locator('form[data-form="team-goal"]'),observations=form.locator('[name="observations"]');await expect(form.locator('[name="doc_id"]')).toHaveValue(String(id));await observations.fill('Facto atualizado pelo treinador.');await expect(observations).toHaveValue('Facto atualizado pelo treinador.');expect(await form.evaluate(form=>new FormData(form).get('observations'))).toBe('Facto atualizado pelo treinador.');await form.getByRole('button',{name:'Guardar objetivo'}).click();await expect.poll(async()=>page.evaluate(async id=>JSON.parse((await DB.obter('workspace_documents',id)).body).observations,id)).toBe('Facto atualizado pelo treinador.');const saved=await page.evaluate(async id=>{const row=await DB.obter('workspace_documents',id),value=JSON.parse(row.body);return{value,updated_at:row.updated_at};},id);expect(saved.value.worked_sessions).toBe(null);expect(saved.value.history[0].worked_sessions).toBe(null);expect(saved.updated_at).not.toBe('team-goal-legacy-history-v1');
});
test('weekly plan and team goal save offline, retain references, and only advance by coach input',async({page,context})=>{
 await page.goto('/#/evolucao');await page.waitForFunction(()=>typeof TeamDevelopment!=='undefined'&&typeof RemoteWorkspace!=='undefined');
 const ids=await page.evaluate(async()=>{RemoteWorkspace.scheduleSync=()=>{};const t=await DB.criar('treinos',{team_id:DEFAULT_TEAM_ID,sync_id:crypto.randomUUID(),data:'2026-09-21',objetivo:'Apoiar após passe',status:'completed',session:{status:'completed'}});const m=await DB.criar('jogos',{team_id:DEFAULT_TEAM_ID,sync_id:crypto.randomUUID(),data:'2026-09-26',adversario:'Equipa E2E',estado:'agendado'});const e=await DB.criar('exercicios',{team_id:DEFAULT_TEAM_ID,sync_id:crypto.randomUUID(),nome:'Apoio após passe'});const memoryId=await HeadCoachMemory.create({team_id:DEFAULT_TEAM_ID,kind:'observation',title:'Apoio observado',content:'Observação independente do objetivo.',occurred_at:'2026-09-22',source:{type:'coach',label:'Treinador'}}),memory=await DB.obter('memory_items',memoryId);return{training:(await DB.obter('treinos',t)).sync_id,match:(await DB.obter('jogos',m)).sync_id,exercise:(await DB.obter('exercicios',e)).sync_id,memory:memory.sync_id};});
 await page.evaluate(()=>router());await context.setOffline(true);const week=page.locator('form[data-form="team-week"]');await week.locator('[name="week_start"]').fill('2026-09-23');await week.locator('[name="objective"]').fill('Apoio após passe');await week.locator('[name="training1"]').selectOption(ids.training);await week.locator('[name="match"]').selectOption(ids.match);await week.locator('[name="relation_note"]').fill('Consolidar no jogo.');await week.getByRole('button',{name:'Guardar semana'}).click();await expect(page.getByText('Semana de 21/09/2026')).toBeVisible();await expect(page.getByRole('link',{name:'Treino · Apoiar após passe'})).toBeVisible();await expect(page.getByRole('link',{name:'Jogo · Equipa E2E'})).toBeVisible();await expect(page.getByText('Consolidar no jogo.')).toBeVisible();
 const row=await page.evaluate(async()=>{const d=(await DB.porIndice('workspace_documents','team_id',DEFAULT_TEAM_ID)).find(x=>x.type==='weekly_plan');return{d,w:TeamDevelopment.week(d)}});expect(row.w.training1).toBe(ids.training);expect(row.w.match).toBe(ids.match);expect(row.d.external_key).toBe('team-week:2026-09-21');
 await page.setViewportSize({width:390,height:844});const goal=page.locator('form[data-form="team-goal"]');await goal.locator('[name="title"]').fill('Apoio na construção');await goal.locator('[name="stage"]').selectOption('worked');await goal.locator('[name="session_refs"][value="training:'+ids.training+'"]').locator('xpath=..').click();await goal.locator('[name="session_refs"][value="match:'+ids.match+'"]').locator('xpath=..').click();await goal.getByRole('button',{name:'Guardar objetivo'}).click();await expect(goal.locator('[data-team-feedback]')).toContainText('seleciona uma sessão concluída');expect(await page.evaluate(()=>DB.porIndice('workspace_documents','team_id',DEFAULT_TEAM_ID).then(xs=>xs.filter(x=>x.type==='team_goal').length))).toBe(0);await goal.locator('[name="worked_session_refs"][value="training:'+ids.training+'"]').locator('xpath=..').click();await goal.locator('[name="evidence_refs"][value="memory:'+ids.memory+'"]').locator('xpath=..').click();await goal.locator('[name="exercise_refs"]').locator('xpath=..').click();await goal.locator('[name="observations"]').fill('O apoio apareceu em vários blocos.');await goal.locator('[name="evaluation"]').fill('O princípio foi observado em treino e jogo.');await goal.getByRole('button',{name:'Guardar objetivo'}).click();await expect(page.getByText(/Trabalhado · identificado .* · 2 sessão\(ões\) relacionadas · 1 sessão\(ões\) trabalhadas · 1 exercício/)).toBeVisible();const goalCard=page.locator('.list-item').filter({hasText:'Apoio na construção'});await expect(goalCard.getByRole('link',{name:'Treino · Apoiar após passe'})).toBeVisible();await expect(goalCard.getByRole('link',{name:'Jogo · Equipa E2E'})).toBeVisible();await expect(goalCard.getByRole('link',{name:'Exercício · Apoio após passe'})).toHaveAttribute('href',/\/exercicios\//);await expect(goalCard.getByRole('link',{name:'Observação · Apoio observado'})).toBeVisible();await expect(goalCard.getByText('O princípio foi observado em treino e jogo.')).toBeVisible();await expect(goalCard.getByRole('heading',{name:'Evidências'})).toBeVisible();
 const goalRow=await page.evaluate(async()=>{const d=(await DB.porIndice('workspace_documents','team_id',DEFAULT_TEAM_ID)).find(x=>x.type==='team_goal');return TeamDevelopment.teamGoal(d)});expect(goalRow.stage).toBe('worked');expect(goalRow.sessions).toHaveLength(2);expect(goalRow.worked_sessions).toEqual([{type:'training',id:ids.training}]);expect(goalRow.sessions).toContainEqual({type:'training',id:ids.training});expect(goalRow.sessions).toContainEqual({type:'match',id:ids.match});expect(goalRow.exercises).toContainEqual({type:'exercise',id:ids.exercise});
 await page.locator('[data-action="edit-team-record"][data-kind="goal"]').click();await expect(goal.locator('[name="doc_id"]')).not.toHaveValue('');await expect(goal.locator('[name="expected_revision"]')).toHaveValue('1');await goal.locator('[name="observations"]').fill('Apoio apareceu em vários blocos e no jogo.');await goal.getByRole('button',{name:'Guardar objetivo'}).click();await expect.poll(async()=>page.evaluate(async()=>{const d=(await DB.porIndice('workspace_documents','team_id',DEFAULT_TEAM_ID)).find(x=>x.type==='team_goal');return TeamDevelopment.teamGoal(d).revision;})).toBe(2);
 const edited=await page.evaluate(async()=>{const d=(await DB.porIndice('workspace_documents','team_id',DEFAULT_TEAM_ID)).find(x=>x.type==='team_goal');return TeamDevelopment.teamGoal(d)});expect(edited.sessions).toHaveLength(2);expect(edited.worked_sessions).toEqual([{type:'training',id:ids.training}]);expect(edited.exercises).toContainEqual({type:'exercise',id:ids.exercise});expect(edited.evidence).toContainEqual({type:'memory',id:ids.memory});expect(edited.evaluation).toBe('O princípio foi observado em treino e jogo.');expect(edited.history.at(-1).observations).toBe('O apoio apareceu em vários blocos.');expect(edited.history.at(-1).evidence).toContainEqual({type:'memory',id:ids.memory});await context.setOffline(false);
});
test('Head Coach priority proposal shows evidence, stays editable, and needs explicit coach decision',async({page})=>{
 await page.goto('/#/evolucao');await page.waitForFunction(()=>typeof TeamDevelopment!=='undefined'&&typeof RemoteWorkspace!=='undefined');
 const proposalId=await page.evaluate(async()=>{RemoteWorkspace.scheduleSync=()=>{};const t=await DB.criar('treinos',{team_id:DEFAULT_TEAM_ID,sync_id:crypto.randomUUID(),data:'2026-09-22',objetivo:'Apoio'}),training=(await DB.obter('treinos',t)).sync_id,value=TeamDevelopment.saveGoal(null,{title:'Apoio após passe',stage:'identified',sessions:[{type:'training',id:training}],evidence:[{type:'training',id:training}],interpretation:'O apoio pode estar distante.',hypothesis:'Confirmar sob pressão.',coach_decision:'',agent_proposal:{status:'proposed',rationale:'A avaliação do treino regista apoio irregular.',prepared_by:'Head Coach',prepared_at:'2026-09-23T10:00:00Z',evidence_refs:[{type:'training',id:training,field:'review.continua',quote:'Apoio irregular',record_updated_at:'source-v1'}]}},{expected_revision:0}),id=await DB.criar('workspace_documents',{team_id:DEFAULT_TEAM_ID,type:'team_goal',title:value.title,body:JSON.stringify(value),status:'ready',external_key:'proposal-e2e',sync_id:crypto.randomUUID(),created_by:'agent',created_by_label:'Head Coach',updated_at:'doc-v1'});await router();return id;});
 await expect(page.getByText('Proposta do Head Coach · por rever')).toBeVisible();await expect(page.getByText('Apoio irregular')).toBeVisible();const sourceHref=await page.evaluate(async()=>{const goal=(await DB.porIndice('workspace_documents','team_id',DEFAULT_TEAM_ID)).find(x=>x.type==='team_goal'),ref=TeamDevelopment.teamGoal(goal).agent_proposal.evidence_refs[0],training=(await DB.porIndice('treinos','team_id',DEFAULT_TEAM_ID)).find(x=>x.sync_id===ref.id);return '#/consulta/'+training.id;});await expect(page.getByRole('link',{name:'Treino · review.continua'})).toHaveAttribute('href',sourceHref);page.once('dialog',d=>d.dismiss());await page.getByRole('button',{name:'Aceitar como objetivo'}).click();
 await page.locator('[data-action="edit-team-record"][data-kind="goal"]').click();const form=page.locator('form[data-form="team-goal"]');await expect(form.locator('[name="doc_id"]')).not.toHaveValue('');await expect(form.locator('[name="expected_revision"]')).toHaveValue('1');await form.locator('[name="title"]').fill('Apoio após passe revisto');await expect(form.locator('[name="title"]')).toHaveValue('Apoio após passe revisto');await form.locator('[name="coach_decision"]').fill('Aceito trabalhar o apoio após passe.');await form.getByRole('button',{name:'Guardar objetivo'}).click();await expect.poll(async()=>page.evaluate(async id=>TeamDevelopment.teamGoal(await DB.obter('workspace_documents',id)),proposalId)).toMatchObject({title:'Apoio após passe revisto',coach_decision:'Aceito trabalhar o apoio após passe.'});await expect(page.getByText('Apoio após passe revisto')).toBeVisible();await expect(page.getByText('Proposta do Head Coach · por rever')).toBeVisible();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Aceitar como objetivo'}).click();await expect(page.getByText('Proposta do Head Coach · por rever')).toHaveCount(0);
 const state=await page.evaluate(async id=>{const doc=await DB.obter('workspace_documents',id);return TeamDevelopment.teamGoal(doc);},proposalId);expect(state.agent_proposal.status).toBe('accepted');expect(state.coach_decision).toBe('Aceito trabalhar o apoio após passe.');const rejectedId=await page.evaluate(async()=>{const training=(await DB.porIndice('treinos','team_id',DEFAULT_TEAM_ID))[0],value=TeamDevelopment.saveGoal(null,{title:'Pressão após perda',stage:'identified',sessions:[{type:'training',id:training.sync_id}],evidence:[{type:'training',id:training.sync_id}],interpretation:'Proposta por rever.',agent_proposal:{status:'proposed',rationale:'Sinal para analisar.',prepared_by:'Head Coach',evidence_refs:[{type:'training',id:training.sync_id,field:'review.continua',quote:'Apoio irregular',record_updated_at:'source-v1'}]}},{expected_revision:0});return DB.criar('workspace_documents',{team_id:DEFAULT_TEAM_ID,type:'team_goal',title:value.title,body:JSON.stringify(value),status:'ready',external_key:'proposal-reject-e2e',sync_id:crypto.randomUUID(),created_by:'agent',created_by_label:'Head Coach',updated_at:'doc-v1'});});await page.evaluate(()=>router());await expect(page.getByText(/Proposta do Head Coach · por rever/)).toBeVisible();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Rejeitar proposta'}).click();await expect(page.getByText(/Proposta rejeitada pelo treinador/)).toBeVisible();const dismissed=await page.evaluate(async id=>TeamDevelopment.teamGoal(await DB.obter('workspace_documents',id)),rejectedId);expect(dismissed.agent_proposal.status).toBe('dismissed');expect(await page.evaluate(()=>DB.porIndice('treinos','team_id',DEFAULT_TEAM_ID).then(x=>x.length))).toBe(1);
});
