const {test,expect}=require('@playwright/test');
test.use({serviceWorkers:'block'});
async function seed(page){
 await page.goto('/#/treinos');await expect(page.getByRole('heading',{name:'Planeador de treino'})).toBeVisible();
 return page.evaluate(async()=>{RemoteWorkspace.scheduleSync=()=>{};const ex=crypto.randomUUID();await DB.criar('exercicios',{team_id:DEFAULT_TEAM_ID,workspace_v2:true,sync_id:ex,external_key:'exercise-ativacao-conduzir-passar-dar-opcao',status:'active',nome:'Apoio de teste',objetivo:'Dar opção',duracao_total_min:10,series:1,duracao_serie_min:10});const id=await DB.criar('treinos',{team_id:DEFAULT_TEAM_ID,sync_id:crypto.randomUUID(),data:'2026-09-21',hora:'19:15',status:'ready',objetivo:'Continuidade E2E',blocos:[{order:0,exercise_ref:ex,exercise_name:'Apoio de teste',phase:'principal',duration_min:10,notes:'Preservar'}],review:{status:'pending'}});go('#/treinos/'+id);return id;});
}
async function review(page){const form=page.locator('[data-form="training-review"]');await form.locator('[name="melhorou"]').fill('Qualidade do passe');await form.locator('[name="continua"]').fill('Dar apoio depois de passar');await form.getByRole('button',{name:'Guardar avaliação',exact:true}).click();await expect(page.getByText('Avaliação registada',{exact:true})).toBeVisible();}
async function propose(page){await page.getByRole('link',{name:'Avaliação → próximo treino',exact:true}).click();await page.getByRole('button',{name:'Gerar proposta de continuidade',exact:true}).click();await expect(page.locator('[data-continuity-form]')).toBeVisible();}
async function fill(page){const form=page.locator('[data-continuity-form]');await form.locator('[name="success_criterion"]').fill('Observar apoios sem indicação');await form.locator('[name="date"]').fill('2026-09-24');await form.getByRole('button',{name:'Guardar ajustes da proposta',exact:true}).click();await expect(page.locator('[data-continuity-feedback]')).toContainText('Proposta guardada');}
for(const viewport of [{width:390,height:844},{width:1440,height:900}])test('review to memory to approved follow-up '+viewport.width,async({page,context})=>{
 await page.setViewportSize(viewport);const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());const id=await seed(page);await review(page);
 let mem=await page.evaluate(()=>DB.listar('memory_items'));expect(mem).toHaveLength(1);expect(mem[0].content).toContain('Dar apoio depois de passar');const memId=mem[0].sync_id;
 await page.locator('[data-form="training-review"] [name="proxima_acao"]').fill('Passar e dar opção');await page.getByRole('button',{name:'Guardar avaliação',exact:true}).click();await expect.poll(()=>page.evaluate(()=>DB.listar('memory_items').then(x=>x[0].content))).toContain('Passar e dar opção');
 mem=await page.evaluate(()=>DB.listar('memory_items'));expect(mem).toHaveLength(1);expect(mem[0].sync_id).toBe(memId);
 await propose(page);expect((await page.evaluate(()=>DB.listar('treinos'))).length).toBe(1);await fill(page);
 await context.setOffline(true);await page.getByRole('button',{name:'Aprovar e criar treino',exact:true}).click();await expect(page.getByRole('link',{name:'Abrir treino seguinte',exact:true})).toBeVisible();
 const rows=await page.evaluate(()=>DB.listar('treinos')),source=rows.find(x=>x.id===id),target=rows.find(x=>x.id!==id);expect(rows).toHaveLength(2);expect(target.source_training_ref).toBe(source.sync_id);expect(target.continuity_origin.evidence.length).toBeGreaterThan(0);expect(target.session).toBeUndefined();expect(target.sync_dirty).toBe(true);
 await page.getByRole('link',{name:'Abrir treino seguinte',exact:true}).click();await expect(page.getByText('Como avaliar: Observar apoios sem indicação',{exact:true})).toBeVisible();
 await page.locator('[data-form="training-review"] [name="melhorou"]').fill('Apoios surgem sem indicação');await page.locator('[name="focus_outcome"]').selectOption('improved');await page.getByRole('button',{name:'Guardar avaliação',exact:true}).click();await expect.poll(()=>page.evaluate(()=>DB.listar('treinos').then(rows=>rows.find(t=>t.source_training_ref)?.review.focus_outcome))).toBe('improved');
 await page.evaluate(id=>go('#/continuidade/'+id),id);await expect(page.getByText('Resultado indicado: Melhorou',{exact:true})).toBeVisible();expect(errors).toEqual([]);await context.setOffline(false);
});
test('approval refuses unsaved edits and stale review, never loses typed adjustments',async({page})=>{const id=await seed(page);await review(page);await propose(page);await fill(page);await page.locator('[name="objective"]').fill('Ajuste ainda não guardado');await page.getByRole('button',{name:'Aprovar e criar treino',exact:true}).click();await expect(page.locator('[data-continuity-feedback]')).toContainText('Guarda primeiro');expect((await page.evaluate(()=>DB.listar('treinos'))).length).toBe(1);await page.evaluate(async id=>{await DB.modificar('treinos',id,t=>({...t,review:{...t.review,continua:'Outra observação'}}));window.dispatchEvent(new CustomEvent('visioncoach:sync-complete'));},id);await expect(page.locator('[name="objective"]')).toHaveValue('Ajuste ainda não guardado');await page.getByRole('button',{name:'Guardar ajustes da proposta',exact:true}).click();await expect(page.locator('[data-continuity-feedback]')).toContainText('mudou');});
test('clear review archives same memory and invalidates draft; dismiss keeps exercises',async({page})=>{page.on('dialog',d=>d.accept());const id=await seed(page);await review(page);await propose(page);await page.getByRole('button',{name:'Apagar proposta',exact:true}).click();await expect(page.getByRole('button',{name:'Gerar novamente a proposta',exact:true})).toBeVisible();await page.evaluate(id=>go('#/treinos/'+id),id);await page.getByRole('button',{name:'Apagar avaliação',exact:true}).click();await expect.poll(()=>page.evaluate(()=>DB.listar('memory_items').then(x=>x[0].status))).toBe('archived');expect((await page.evaluate(()=>DB.listar('memory_items'))).length).toBe(1);expect((await page.evaluate(()=>DB.listar('exercicios'))).length).toBe(1);});
test('parallel local approval creates one child; deleted child is not resurrected',async({page})=>{const id=await seed(page);await review(page);await propose(page);await fill(page);const result=await page.evaluate(async id=>{const r=await DB.obter('treinos',id),rev=r.continuity.revision;const ops=await Promise.allSettled([1,2].map(()=>TrainingContinuityStore.commit(id,'approve',{expected_revision:rev,confirmed:true})));const rows=await DB.listar('treinos'),target=rows.find(t=>t.id!==id);await DB.apagar('treinos',target.id);let blocked=false;try{await TrainingContinuityStore.commit(id,'approve',{confirmed:true});}catch(_){blocked=true;}return {fulfilled:ops.filter(o=>o.status==='fulfilled').length,children:rows.length-1,blocked,remaining:(await DB.listar('treinos')).length};},id);expect(result.children).toBe(1);expect(result.fulfilled).toBeGreaterThan(0);expect(result.blocked).toBe(true);expect(result.remaining).toBe(1);});
test('deleted managed memory is not recreated when saving review',async({page})=>{const id=await seed(page);await review(page);await page.evaluate(async()=>{const [m]=await DB.listar('memory_items');await DB.apagar('memory_items',m.id);});await page.locator('[data-form="training-review"] [name="continua"]').fill('Nova observação');await page.getByRole('button',{name:'Guardar avaliação',exact:true}).click();await expect(page.locator('[data-review-feedback]')).toContainText('não foi recriada');expect((await page.evaluate(()=>DB.listar('memory_items'))).length).toBe(0);});
