const {test,expect}=require('@playwright/test');test.use({serviceWorkers:'block'});
test('cross-workspace search filters observations and opens the stored source on mobile',async({page,context})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');await page.waitForFunction(()=>typeof router==='function');
 const memoryId=await page.evaluate(()=>{RemoteWorkspace.scheduleSync=()=>{};return WorkspaceStore.captureObservation({team_id:DEFAULT_TEAM_ID,title:'Apoio na saída',content:'O ala ofereceu linha de passe depois da recuperação.',occurred_at:'2026-09-23',refs:[]});});
 await page.goto('/#/pesquisa');await expect(page.getByRole('heading',{name:'Encontra o registo e abre a sua origem.'})).toBeVisible();const form=page.locator('form[data-form="workspace-search"]');await form.locator('[name="q"]').fill('linha recuperação');await form.locator('[name="kind"]').selectOption('observation');await form.getByRole('button',{name:'Pesquisar'}).click();await expect(page.getByRole('link',{name:/Apoio na saída/})).toBeVisible();await page.getByRole('link',{name:/Apoio na saída/}).click();await expect(page).toHaveURL(new RegExp('timeline/memory/'+memoryId));await expect(page.getByText('O ala ofereceu linha de passe depois da recuperação.')).toBeVisible();await context.setOffline(false);
});
test('search follows linked match origins and limits individual goals to the archived roster',async({page})=>{
 await page.goto('/#/calendario');await page.waitForFunction(()=>typeof VisionSeasons!=='undefined'&&typeof PlayerGoals!=='undefined'&&typeof HeadCoachMemory!=='undefined');
 const data=await page.evaluate(async()=>{RemoteWorkspace.scheduleSync=()=>{};const inRef=crypto.randomUUID(),outRef=crypto.randomUUID(),matchRef=crypto.randomUUID(),trainingRef=crypto.randomUUID(),inside=await DB.criar('jogadores',{team_id:DEFAULT_TEAM_ID,sync_id:inRef,nome:'Atleta Dentro',plantel_ativo:true}),outside=await DB.criar('jogadores',{team_id:DEFAULT_TEAM_ID,sync_id:outRef,nome:'Atleta Fora',plantel_ativo:true}),match=await DB.criar('jogos',{team_id:DEFAULT_TEAM_ID,sync_id:matchRef,data:'2026-09-12',adversario:'Origem da observação',estado:'agendado'}),training=await DB.criar('treinos',{team_id:DEFAULT_TEAM_ID,sync_id:trainingRef,data:'2026-09-13',objetivo:'Treino ligado à observação'}),officialExercise=await DB.criar('exercicios',{team_id:DEFAULT_TEAM_ID,sync_id:crypto.randomUUID(),external_key:'search-current-exercise',workspace_v2:true,nome:'Exercício de pesquisa atual',objetivo:'Condução com progressão'}),legacyExercise=await DB.criar('exercicios',{team_id:DEFAULT_TEAM_ID,nome:'Exercício de pesquisa antigo'});for(const id of [inside,outside])await DB.modificar('jogadores',id,p=>PlayerGoals.apply(p,{type:'save',expected_revision:0,goal:{title:'Apoio de setembro',started_at:'2026-09-04',status:'active'}},{now:'2026-09-04T12:00:00Z'}));const value=VisionSeasons.save(null,{name:'Época Pesquisa',start_date:'2026-09-01',end_date:'2026-09-30',roster:[{ref:inRef,name:'Atleta Dentro'}],activate:true},{expected_revision:0,now:'2026-09-01T12:00:00Z'});await DB.criar('workspace_documents',{team_id:DEFAULT_TEAM_ID,type:'season_index',title:'Arquivo de épocas',body:JSON.stringify(value),status:'ready',target_date:'2026-09-01',external_key:'season-index:'+DEFAULT_TEAM_ID,sync_id:await VisionSeasons.stableIndexId(DEFAULT_TEAM_ID)});await HeadCoachMemory.create({team_id:DEFAULT_TEAM_ID,kind:'observation',title:'Pressão na saída',content:'A pressão começou após passe lateral.',occurred_at:'2026-09-12',source:{type:'match',label:'Jogo',ref_type:'match',ref_id:matchRef},subject_refs:[{type:'match',id:matchRef,relation:'observed_in'}]});await HeadCoachMemory.create({team_id:DEFAULT_TEAM_ID,kind:'observation',title:'Apoio na sessão',content:'O ala ofereceu apoio depois de passar.',occurred_at:'2026-09-13',source:{type:'training',label:'Treino',ref_type:'training',ref_id:trainingRef},subject_refs:[{type:'training',id:trainingRef,relation:'observed_in'}]});return{inside,outside,match,training,officialExercise,legacyExercise,seasonId:value.items[0].id};});
 await page.goto('/#/pesquisa');const form=page.locator('form[data-form="workspace-search"]');await form.locator('[name="q"]').fill('Apoio de setembro');await form.locator('[name="kind"]').selectOption('objective');await form.locator('[name="season"]').selectOption(data.seasonId);await form.getByRole('button',{name:'Pesquisar'}).click();const goals=page.getByRole('link',{name:/Apoio de setembro/});await expect(goals).toHaveCount(1);await goals.click();await expect(page).toHaveURL(new RegExp('/equipa/jogador/'+data.inside+'$'));
 await page.goto('/#/pesquisa');const search=page.locator('form[data-form="workspace-search"]');await search.locator('[name="q"]').fill('Pressão na saída');await search.locator('[name="kind"]').selectOption('observation');await search.getByRole('button',{name:'Pesquisar'}).click();await page.getByRole('link',{name:/Pressão na saída/}).click();await expect(page).toHaveURL(new RegExp('/equipa/jogo/'+data.match+'$'));
 await page.goto('/#/pesquisa');const linkedTraining=page.locator('form[data-form="workspace-search"]');await linkedTraining.locator('[name="q"]').fill('Apoio na sessão');await linkedTraining.locator('[name="kind"]').selectOption('observation');await linkedTraining.getByRole('button',{name:'Pesquisar'}).click();await page.getByRole('link',{name:/Apoio na sessão/}).click();await expect(page).toHaveURL(new RegExp('/treinos/'+data.training+'$'));await expect(page.getByText('Treino ligado à observação')).toBeVisible();
 await page.goto('/#/pesquisa');const exerciseSearch=page.locator('form[data-form="workspace-search"]');await exerciseSearch.locator('[name="q"]').fill('Condução com progressão');await exerciseSearch.locator('[name="kind"]').selectOption('exercise');await exerciseSearch.getByRole('button',{name:'Pesquisar'}).click();await page.getByRole('link',{name:/Exercício de pesquisa atual/}).click();await expect(page).toHaveURL(new RegExp('/exercicios/'+data.officialExercise+'$'));await expect(page.locator('#app').getByRole('heading',{name:'Exercício de pesquisa atual'})).toBeVisible();
 await page.goto('/#/pesquisa');const legacySearch=page.locator('form[data-form="workspace-search"]');await legacySearch.locator('[name="q"]').fill('Exercício de pesquisa antigo');await legacySearch.locator('[name="kind"]').selectOption('exercise');await legacySearch.getByRole('button',{name:'Pesquisar'}).click();await expect(page.getByRole('heading',{name:'Resultados · 0'})).toBeVisible();
});
test('an unavailable season filter returns no records instead of widening the search',async({page})=>{await page.goto('/#/pesquisa?season=11111111-1111-4111-8111-111111111111');await page.waitForFunction(()=>typeof router==='function');const season=page.locator('form[data-form="workspace-search"] [name="season"]');await expect(season).toHaveValue('11111111-1111-4111-8111-111111111111');await expect(season.locator('option:checked')).toHaveText('Época indisponível');await expect(page.getByRole('heading',{name:'Resultados · 0'})).toBeVisible();await expect(page.getByText('Sem resultados para estes filtros.')).toBeVisible();});
