const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
let api,cli;
test.before(async()=>{api=await import('../supabase/functions/vision-coach-mcp/image_uploads.mjs');cli=await import('../scripts/publish-exercise-images.mjs');});
const original=()=>new Uint8Array(fs.readFileSync(path.join(__dirname,'../assets/exercises/approved-20260922/01_ativacao_conduzir_passar_dar_opcao.png')));
const secret='test-only-signing-material-not-a-credential-123456';
const c={id:'connector-test',team_id:'team-test',scopes:['read','write','media']};
function fixture(){
  const rows=[{id:'exercise-test',team_id:c.team_id,kind:'exercise',deleted_at:null,updated_at:'2026-09-22T12:00:00.000Z',payload:{nome:'Original test',external_key:'exact-test',notas:'keep me',visual_url:'https://example.org/old.png'}}];
  const objects=new Map(),audits=[];let version=0;
  const admin={from(){const predicates=[];return {select(){return this;},eq(k,v){predicates.push(r=>(k==='payload->>external_key'?r.payload.external_key:r[k])===v);return this;},is(k,v){return this.eq(k,v);},then(resolve){return Promise.resolve({data:rows.filter(r=>predicates.every(p=>p(r))).map(r=>structuredClone(r)),error:null}).then(resolve);}}},
    storage:{from(){return {async createSignedUploadUrl(p,options){assert.equal(options.upsert,false);return {data:{signedUrl:'https://test.supabase.co/storage/v1/object/upload/sign/team-media/'+p+'?token=TEST'}};},async createSignedUrl(p){return {data:{signedUrl:'https://test.supabase.co/storage/v1/object/sign/team-media/'+p+'?token=TEST'}};}}}},
    async rpc(name,args){assert.equal(name,'head_coach_put_record');const row=rows.find(r=>r.id===args.p_record_id&&r.team_id===args.p_team_id);if(!row||row.deleted_at||row.updated_at!==args.p_expected_updated_at)return {error:new Error('record_conflict')};row.payload=structuredClone(args.p_payload);row.updated_at='version-'+(++version);audits.push(args);return {data:{ok:true}};}
  };
  const oldFetch=global.fetch;
  global.fetch=async(url,options={})=>{const u=new URL(url),p=decodeURIComponent(u.pathname.split('/team-media/')[1]);if(options.method==='PUT'){objects.set(p,new Uint8Array(options.body));return new Response('{}');}const bytes=objects.get(p);return bytes?new Response(bytes,{headers:{'content-type':'image/png'}}):new Response('',{status:404});};
  return {admin,rows,objects,audits,restore(){global.fetch=oldFetch;},call:(name,args)=>api.executeImageTool(admin,c,name,args,secret)};
}
async function metadata(){const b=original();return {...api.imageInfo(b),sha256:await api.imageHash(b),file_name:'original.png'};}
async function prepare(f,extra={}){return f.call('prepare_exercise_image_upload',{id:'exercise-test',approved:true,expected_updated_at:f.rows[0].updated_at,...await metadata(),...extra});}
async function upload(f,start,bytes=original()){const t=await api.verifyImageTicket(start.ticket,secret,c);f.objects.set(t.path,bytes);return t;}
test('image inspector reads original dimensions, does not re-encode bytes',async()=>{const b=original();assert.deepEqual(api.imageInfo(b),{width:1448,height:1086,mime_type:'image/png',size_bytes:b.length});assert.equal(await api.imageHash(b),'8a82ac2a8b9f519320160de9b0a4319d1f78b501babbc8f1e6197b8da47f817b');});
test('rejects SVG, truncated PNG and oversized images',()=>{assert.throws(()=>api.imageInfo(new TextEncoder().encode('<svg>'+'.'.repeat(50)+'</svg>')));assert.throws(()=>api.imageInfo(original().subarray(0,50)));assert.throws(()=>api.imageInfo(new Uint8Array(api.IMAGE_LIMIT+1)));});
test('tickets cannot be forged, reused across accounts, teams or expiry',async()=>{const t={version:1,connector:c.id,team:c.team_id,id:'e',path:c.team_id+'/exercise-images/e/file.png',expires:Date.now()+10000};const signed=await api.signImageTicket(t,secret);assert.equal((await api.verifyImageTicket(signed,secret,c)).id,'e');for(const [ticket,who,when] of [[signed.slice(0,-4)+'abcd',c,Date.now()],[signed,{...c,id:'another'},Date.now()],[signed,{...c,team_id:'another'},Date.now()],[signed,c,t.expires+1]])await assert.rejects(api.verifyImageTicket(ticket,secret,who,when));});
test('complete flow preserves other fields, private path and audit; replay is idempotent',async()=>{const f=fixture();try{const s=await prepare(f);assert.equal(f.rows[0].payload.visual_url,'https://example.org/old.png');const t=await upload(f,s);const result=await f.call('complete_exercise_image_upload',{ticket:s.ticket});assert.equal(result.verified,true);assert.equal(f.rows.length,1);assert.equal(f.rows[0].payload.notas,'keep me');assert.equal(f.rows[0].payload.visual_storage_path,t.path);assert.equal(f.rows[0].payload.visual_url,undefined);assert.equal(f.audits.length,1);assert.equal((await f.call('complete_exercise_image_upload',{ticket:s.ticket})).already_linked,true);assert.equal((await prepare(f)).already_linked,true);assert.equal(f.audits.length,1);}finally{f.restore();}});
test('checksum mismatch never replaces an existing image',async()=>{const f=fixture();try{const s=await prepare(f);const bytes=original();bytes[70]^=1;await upload(f,s,bytes);await assert.rejects(f.call('complete_exercise_image_upload',{ticket:s.ticket}),/mismatch/);assert.equal(f.audits.length,0);assert.equal(f.rows[0].payload.visual_url,'https://example.org/old.png');}finally{f.restore();}});
test('dimension and MIME mismatch prevent association',async()=>{const f=fixture();try{for(const extra of [{width:1000},{mime_type:'image/jpeg'}]){const s=await prepare(f,extra);await upload(f,s);await assert.rejects(f.call('complete_exercise_image_upload',{ticket:s.ticket}),/mismatch/);}assert.equal(f.audits.length,0);}finally{f.restore();}});
test('stale versions and remotely deleted exercises are protected',async()=>{const f=fixture();try{await assert.rejects(prepare(f,{expected_updated_at:'old'}),/conflict/);const s=await prepare(f);await upload(f,s);f.rows[0].updated_at='changed';await assert.rejects(f.call('complete_exercise_image_upload',{ticket:s.ticket}),/conflict/);f.rows[0].deleted_at='now';await assert.rejects(f.call('complete_exercise_image_upload',{ticket:s.ticket}),/not_found/);assert.equal(f.audits.length,0);}finally{f.restore();}});
test('missing permission, approval or ambiguous identifier is refused',async()=>{const f=fixture();try{await assert.rejects(prepare(f,{approved:false}),/approval/);await assert.rejects(f.call('get_exercise_image',{id:'exercise-test',external_key:'exact-test'}),/exactly_one/);await assert.rejects(api.executeImageTool(f.admin,{...c,team_id:'another'},'get_exercise_image',{id:'exercise-test'},secret),/not_found/);await assert.rejects(api.executeImageTool(f.admin,{...c,scopes:['read']},'prepare_exercise_image_upload',{},secret),/scope_write/);f.rows.push({...f.rows[0],id:'duplicate'});await assert.rejects(f.call('get_exercise_image',{external_key:'exact-test'}),/ambiguous/);}finally{f.restore();}});
test('image can be unlinked without deleting exercise and old approved fallback stays disabled',async()=>{const f=fixture();try{const s=await prepare(f);await upload(f,s);await f.call('complete_exercise_image_upload',{ticket:s.ticket});await assert.rejects(f.call('remove_exercise_image',{id:'exercise-test',confirmed:false}),/confirmation/);const out=await f.call('remove_exercise_image',{id:'exercise-test',expected_updated_at:f.rows[0].updated_at,confirmed:true});assert.equal(out.removed,true);assert.equal(f.rows[0].payload.visual_removed,true);assert.equal(f.rows[0].payload.visual_storage_path,undefined);assert.equal(f.rows[0].payload.notas,'keep me');}finally{f.restore();}});
test('publisher automates read, upload, complete and independent download verification',async()=>{const f=fixture();try{const input={selector:{id:'exercise-test'},bytes:original(),meta:await metadata()};const out=await cli.publishInputs([input],f.call);assert.equal(out.ok,true);assert.equal(out.images[0].verified,true);assert.equal(JSON.stringify(out).includes('token='),false);assert.equal((await cli.publishInputs([input],f.call)).images[0].already_linked,true);}finally{f.restore();}});
test('private path never falls back to old public or tiny approved image',()=>{const visuals=require('../js/exercise_visuals.js');assert.equal(visuals.source({external_key:visuals.approved[0].key,visual_storage_path:'private/new.png',visual_url:'https://example.org/old.png'}),null);assert.equal(visuals.safeSource('blob:https://example.org/arbitrary'),null);});
test('CLI refuses credential redirection and unknown arguments',()=>{assert.throws(()=>cli.rpcClient('https://attacker.example/mcp','vcmcp_dummy'),/untrusted/);assert.throws(()=>cli.parseOptions(['--token','secret']),/invalid/);});
