const test=require('node:test'),assert=require('node:assert/strict');
const M=require('../js/match_visual.js');
const refs=Array.from({length:7},(_,i)=>'00000000-0000-4000-8000-'+String(i+1).padStart(12,'0'));
const roster=()=>refs.map((sync_id,i)=>({sync_id,nome:'Atleta '+(i+1),numero:i+1,plantel_ativo:true,estado_disponibilidade:'disponivel'}));
const plan=()=>({id:4,sync_id:'00000000-0000-4000-8000-999999999999',estado:'agendado',golos_favor:2,post_game:{conclusoes:'Preservar'},callup:{player_ids:refs},lineup:{system:'1-2-1',goalkeeper_id:refs[0],starters:refs.slice(1,5),substitutes:refs.slice(5)}});
const act=(r,type,now=0,args={},opts={})=>M.apply(r,{type,expected_revision:M.state(r).revision,...args},{now,controller_id:'phone',players:roster(),...opts});
const start=()=>act(plan(),'start',0,{confirmed:true});
test('legacy lineup becomes 5v5 without changing any records or creating minutes',()=>{const r=plan(),before=JSON.stringify(r),v=M.replay(r);assert.equal(v.slots.gr,refs[0]);assert.deepEqual(Object.values(v.slots),refs.slice(0,5));assert.equal(v.players.length,0);assert.equal(JSON.stringify(r),before);});
test('lineup rejects duplicates, unavailable/non-callup players and incomplete start',()=>{const r=plan(),slots=M.initialSlots(r);slots.front=refs[0];assert.throws(()=>act(r,'save_lineup',0,{slots}),/uma posição/);const p=roster();p[1].estado_disponibilidade='lesionado';assert.throws(()=>act(r,'start',0,{confirmed:true},{players:p}),/disponíveis/);r.lineup.starters=[];assert.throws(()=>act(r,'start',0,{confirmed:true}),/quatro/);});
test('planned lineup saves and clears only its fields, keeps callup and analysis',()=>{const r=plan(),slots=M.initialSlots(r);slots.front=refs[5];const out=act(r,'save_lineup',0,{slots});assert.equal(out.lineup.positions.front,refs[5]);assert.ok(out.lineup.substitutes.includes(refs[4]));assert.deepEqual(out.callup,r.callup);assert.deepEqual(out.post_game,r.post_game);const cleared=act(out,'clear_lineup',0,{confirmed:true});assert.equal(cleared.lineup.starters.length,0);assert.equal(cleared.visual_match.status,'not_started');});
test('explicit start freezes roster without photos or health details and does not fill scores',()=>{const r=plan(),p=roster();p[0].foto='secret-local-data';const out=act(r,'start',0,{confirmed:true},{players:p});assert.equal(out.visual_match.roster.length,7);assert.equal(out.visual_match.roster[0].foto,undefined);assert.equal(out.golos_favor,2);assert.equal(out.estado,'agendado');assert.throws(()=>act(r,'start'),/confirmação/);for(const estado of ['cancelado','concluido'])assert.throws(()=>act({...r,estado},'start',0,{confirmed:true}),/retroativos/);});
test('minutes replay correctly across entry, re-entry, role swap, pauses and end',()=>{
 let r=start();r=act(r,'substitute',300000,{id:'sub1',out_ref:refs[1],in_ref:refs[5],confirmed:true});r=act(r,'pause',600000);
 assert.equal(M.replay(r,900000).total_ms,600000);r=act(r,'swap',900000,{id:'swap1',role_a:'gr',role_b:'left',confirmed:true});r=act(r,'resume',900000);
 r=act(r,'substitute',1200000,{id:'sub2',out_ref:refs[5],in_ref:refs[1],confirmed:true});r=act(r,'finish',1500000,{confirmed:true});
 const v=M.replay(r,2000000),get=i=>v.players.find(p=>p.ref===refs[i]);assert.equal(v.total_ms,1200000);assert.equal(get(1).elapsed_ms,600000);assert.equal(get(5).elapsed_ms,600000);assert.equal(get(6).elapsed_ms,0);assert.equal(get(0).keeper_ms,600000);assert.equal(get(2).keeper_ms,600000);assert.equal(get(1).entries,2);assert.equal(v.players.reduce((n,p)=>n+p.elapsed_ms,0),v.total_ms*5);assert.equal(v.status,'completed');
});
test('saved timestamps survive reload; ticks never write revisions',()=>{const r=JSON.parse(JSON.stringify(start()));assert.equal(M.replay(r,125000).total_ms,125000);assert.equal(r.visual_match.revision,1);assert.equal(M.replay(r,-100).total_ms,0);});
test('substitution must be field to bench and incoming player still available',()=>{const r=start();for(const c of [{out_ref:refs[6],in_ref:refs[5]},{out_ref:refs[1],in_ref:refs[0]}])assert.throws(()=>act(r,'substitute',1,{id:'a',...c,confirmed:true}),/suplente/);const p=roster();p[5].plantel_ativo=false;assert.throws(()=>act(r,'substitute',1,{id:'a',out_ref:refs[1],in_ref:refs[5],confirmed:true},{players:p}),/disponível/);assert.throws(()=>act(r,'substitute',1,{id:'a',out_ref:refs[1],in_ref:refs[5]}),/confirmação/);});
test('a retired outgoing player can leave; historical minutes stay after roster deletion',()=>{const r=start(),p=roster().filter(p=>p.sync_id!==refs[1]);const out=act(r,'substitute',60000,{id:'a',out_ref:refs[1],in_ref:refs[5],confirmed:true},{players:p});assert.equal(M.replay(out,120000).players.find(p=>p.ref===refs[1]).elapsed_ms,60000);});
test('rotations are plans only and execute at actual time, never planned time',()=>{let r=act(plan(),'save_rotation',0,{id:'rotation1',out_ref:refs[1],in_ref:refs[5],at_min:5,note:'Rodar'});r=act(r,'start',0,{confirmed:true});assert.equal(M.replay(r,600000).slots.def,refs[1]);r=act(r,'substitute',660000,{id:'a',out_ref:refs[1],in_ref:refs[5],rotation_id:'rotation1',confirmed:true});assert.equal(r.visual_match.events[0].at_ms,660000);assert.equal(M.replay(r,660000).rotations[0].applied,true);assert.throws(()=>act(r,'delete_rotation',660000,{id:'rotation1',confirmed:true}),/realizada/);});
test('rotation edits/removal are explicit and do not create timeline events',()=>{let r=act(plan(),'save_rotation',0,{id:'r',out_ref:refs[1],in_ref:refs[5],at_min:5});r=act(r,'save_rotation',0,{id:'r',out_ref:refs[2],in_ref:refs[6],at_min:8});assert.equal(r.visual_match.rotations.length,1);assert.throws(()=>act(r,'delete_rotation',0,{id:'r'}),/confirmação/);r=act(r,'delete_rotation',0,{id:'r',confirmed:true});assert.equal(M.replay(r).rotations.length,0);assert.equal(r.visual_match.events.length,0);});
test('controller and stale revisions protected, paused explicit takeover works',()=>{let r=start();assert.throws(()=>act(r,'pause',1000,{}, {controller_id:'pc'}),/Outro dispositivo/);assert.throws(()=>act(r,'pause',1000,{expected_revision:0}),/mudou/);assert.throws(()=>act(r,'take_control',1000,{confirmed:true},{controller_id:'pc'}),/pausa/);r=act(r,'pause',1000);r=act(r,'take_control',2000,{confirmed:true},{controller_id:'pc'});r=act(r,'resume',3000,{}, {controller_id:'pc'});assert.equal(r.visual_match.controller_id,'pc');});
test('late callup changes cannot overwrite planned lineup and live plan remains immutable',()=>{const r=plan();assert.throws(()=>act(r,'save_lineup',0,{slots:M.initialSlots(r),expected_plan_key:'outdated'}),/convocatória/);assert.throws(()=>act(start(),'save_lineup',1,{slots:M.initialSlots(r)}),/preservado/);});
test('undo corrects only latest motion, retains audit and recomputes minutes',()=>{let r=start();r=act(r,'substitute',60000,{id:'a',out_ref:refs[1],in_ref:refs[5],confirmed:true});assert.throws(()=>act(r,'undo_last',120000,{confirmed:true}),/Pausa/);r=act(r,'pause',120000);r=act(r,'undo_last',120001,{confirmed:true});const v=M.replay(r);assert.equal(v.slots.def,refs[1]);assert.equal(v.players.find(p=>p.ref===refs[5]).elapsed_ms,0);assert.equal(v.players.find(p=>p.ref===refs[1]).elapsed_ms,120000);assert.ok(r.visual_match.events[0].voided_at);});
test('reset usage keeps match, original plan, layout and rotations',()=>{let r=start();assert.throws(()=>act(r,'reset_recording',0,{confirmed:true}),/Pausa/);r=act(r,'pause',1000);const out=act(r,'reset_recording',1000,{confirmed:true});assert.equal(out.visual_match.status,'not_started');assert.deepEqual(out.lineup,r.lineup);assert.equal(out.golos_favor,r.golos_favor);assert.deepEqual(out.post_game,r.post_game);assert.equal(out.visual_match.events.length,0);});
test('moving a pawn is a visual edit, not a position swap or change in participation',()=>{const r=start(),out=act(r,'position',1000,{role:'gr',x:.2,y:.8});assert.deepEqual(out.visual_match.layout.gr,{x:.2,y:.8});assert.equal(out.visual_match.events.length,0);assert.deepEqual(M.replay(out,1000).slots,M.replay(r,1000).slots);for(const x of [NaN,Infinity,-1,1.5,'x'])assert.throws(()=>act(r,'position',1000,{role:'gr',x,y:.5}));});
test('malformed future states and duplicate event IDs rejected instead of inventing minutes',()=>{assert.throws(()=>M.state({visual_match:{schema:'future'}}));const r=act(start(),'substitute',1000,{id:'event',out_ref:refs[1],in_ref:refs[5],confirmed:true});assert.throws(()=>act(r,'substitute',1000,{id:'event',out_ref:refs[2],in_ref:refs[6],confirmed:true}),/repetido/);assert.equal(M.format(3661000),'61:01');});

test('remote payload round trip preserves UUIDs, clock and movements without browser IDs',()=>{
 const {remotePayload}=require('../js/remote_workspace.js');let r=start();r=act(r,'substitute',60000,{id:'roundtrip',out_ref:refs[1],in_ref:refs[5],confirmed:true});r=act(r,'pause',120000);
 const payload=remotePayload({...r,sync_dirty:true,remote_updated_at:'before'});const other={...payload,id:987,sync_id:r.sync_id,team_id:'default'};
 assert.equal(payload.id,undefined);assert.deepEqual(M.replay(other),M.replay(r));assert.equal(M.state(other).controller_id,'phone');
});
