const test=require('node:test'),assert=require('node:assert/strict'),R=require('../js/match_player_reports.js');
const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222',other='33333333-3333-4333-8333-333333333333';
const match=()=>({estado:'concluido',callup:{player_ids:[a,b]},post_game:{status:'pending'}});

test('cada convocado começa por preencher, sem observações criadas automaticamente',()=>{const m=match();assert.deepEqual(R.pending(m),[a,b]);assert.equal(R.state(m).items.length,0);assert.equal(m.post_game.player_reports,undefined);});
test('relatório escrito preserva UUID, revisão, histórico e restantes dados do jogo',()=>{const original=match(),first=R.apply(original,{type:'save',player_ref:a,expected_revision:0,observation:'Apoiou após passe.'},{now:'2026-09-26T10:00:00Z'});assert.deepEqual(R.pending(first),[b]);assert.equal(first.post_game.status,'pending');assert.equal(original.post_game.player_reports,undefined);const updated=R.apply(first,{type:'save',player_ref:a,expected_revision:1,positives:'Criou linha de passe.'},{now:'2026-09-26T11:00:00Z'});assert.equal(R.entry(updated,a).history[0].observation,'Apoiou após passe.');assert.equal(R.entry(updated,a).positives,'Criou linha de passe.');assert.equal(R.state(updated).revision,2);});
test('não observado e limpar exigem confirmação e preservam versões',()=>{const first=R.apply(match(),{type:'save',player_ref:a,expected_revision:0,observation:'Pressionou.'});assert.throws(()=>R.apply(first,{type:'not_observed',player_ref:a,expected_revision:1}),/Confirma/);const second=R.apply(first,{type:'not_observed',player_ref:a,expected_revision:1,confirmed:true});assert.equal(R.entry(second,a).status,'not_observed');assert.equal(R.entry(second,a).history[0].observation,'Pressionou.');assert.throws(()=>R.apply(second,{type:'clear',player_ref:a,expected_revision:2}),/Confirma/);const cleared=R.apply(second,{type:'clear',player_ref:a,expected_revision:2,confirmed:true});assert.deepEqual(R.pending(cleared),[a,b]);assert.equal(R.entry(cleared,a).history.length,2);});
test('impede sobrescrita por revisão antiga, outro atleta e jogo por terminar',()=>{const first=R.apply(match(),{type:'save',player_ref:a,expected_revision:0,observation:'Apoio.'});assert.throws(()=>R.apply(first,{type:'save',player_ref:b,expected_revision:0,observation:'Pressão.'}),/noutro dispositivo/);assert.throws(()=>R.apply(first,{type:'save',player_ref:other,expected_revision:1,observation:'Texto.'}),/convocatória/);assert.throws(()=>R.apply({...match(),estado:'agendado'},{type:'save',player_ref:a,expected_revision:0,observation:'Texto.'}),/Conclui/);assert.throws(()=>R.apply(match(),{type:'save',player_ref:a,expected_revision:0}),/Escreve/);});
test('relatórios atravessam o payload de sincronização pelo UUID sem ID local',()=>{const {remotePayload}=require('../js/remote_workspace.js'),saved=R.apply({...match(),sync_id:other,team_id:'default',id:17},{type:'save',player_ref:a,expected_revision:0,observation:'Apoiou.'});const payload=remotePayload({...saved,sync_dirty:true,remote_updated_at:'previous'});const mobile={...payload,id:892};assert.equal(R.entry(mobile,a).observation,'Apoiou.');assert.equal(R.state(mobile).revision,1);assert.equal(R.pending(mobile)[0],b);});
