const test=require('node:test'),assert=require('node:assert/strict');let api;
test.before(async()=>{api=await import('../supabase/functions/vision-coach-mcp/match_visual.mjs');});
const c={id:'connector',team_id:'team',scopes:['read','write']};
const refs=Array.from({length:7},(_,i)=>'00000000-0000-4000-8000-'+String(i+1).padStart(12,'0'));
function fixture(){const match={id:'match',team_id:'team',kind:'match',updated_at:'v0',deleted_at:null,payload:{estado:'agendado',adversario:'Teste',callup:{player_ids:refs},lineup:{goalkeeper_id:refs[0],starters:refs.slice(1,5)}}};
 const rows=[match,...refs.map((id,i)=>({id,team_id:'team',kind:'player',deleted_at:null,payload:{nome:'Atleta '+i,numero:i+1,estado_disponibilidade:'disponivel',foto:'private-photo-not-to-expose'}}))],calls=[];
 const admin={from(){const filters=[];return {select(){return this;},eq(k,v){filters.push(r=>(k==='payload->>external_key'?r.payload.external_key:r[k])===v);return this;},is(k,v){return this.eq(k,v);},then(resolve){return Promise.resolve({data:rows.filter(r=>filters.every(f=>f(r))).map(r=>structuredClone(r))}).then(resolve);}}},async rpc(name,args){assert.equal(name,'head_coach_put_record');assert.equal(args.p_kind,'match');assert.equal(args.p_team_id,'team');assert.equal(args.p_record_id,'match');assert.equal(args.p_expected_updated_at,match.updated_at);calls.push(args);match.payload=structuredClone(args.p_payload);match.updated_at='v'+calls.length;return {data:{ok:true}};}};
 const call=(name,args={})=>api.executeMatchVisualTool(admin,c,name,{id:'match',expected_updated_at:match.updated_at,expected_revision:match.payload.visual_match?.revision||0,...args});return {match,rows,calls,admin,call};
}
test('seven tools and side-effect-free read; no private photos in result',async()=>{const f=fixture(),out=await f.call('get_match_visual');assert.equal(api.MATCH_VISUAL_TOOLS.length,7);assert.equal(out.usage.players.length,0);assert.equal(out.eligible_called.length,7);assert.equal(JSON.stringify(out).includes('private-photo'),false);assert.equal(f.calls.length,0);});
test('MCP team, exact identifier and scopes enforced',async()=>{const f=fixture();await assert.rejects(api.executeMatchVisualTool(f.admin,{...c,team_id:'other'},'get_match_visual',{id:'match'}),/not_found/);await assert.rejects(api.executeMatchVisualTool(f.admin,{...c,scopes:['read']},'control_match_usage',{id:'match'}),/scope_write/);await assert.rejects(f.call('get_match_visual',{external_key:'x'}),/exactly_one/);});
test('MCP initial lineup, rotations, clock and movement use same model with audited writes',async()=>{const f=fixture();await f.call('save_match_rotation',{rotation_id:'r',out_ref:refs[1],in_ref:refs[5],at_min:5});assert.equal(f.match.payload.visual_match.status,'not_started');await f.call('control_match_usage',{action:'start',confirmed:true});await f.call('record_match_movement',{action:'substitute',movement_id:'s',out_ref:refs[1],in_ref:refs[5],rotation_id:'r',confirmed:true});await f.call('control_match_usage',{action:'pause'});const out=await f.call('get_match_visual');assert.equal(out.usage.slots.def,refs[5]);assert.equal(out.visual_match.controller_id,'mcp:connector');assert.equal(f.calls.length,4);assert.match(f.calls[3].p_idempotency_key,/match-visual/);});
test('MCP prevents stale writes, implicit start and unknown action despite loose client',async()=>{const f=fixture();await assert.rejects(f.call('control_match_usage',{action:'start',confirmed:false}),/confirmação/);await assert.rejects(f.call('set_match_visual_position',{role:'gr',x:.5,y:.8,expected_updated_at:'old'}),/conflict/);await assert.rejects(f.call('control_match_usage',{action:'clear_lineup',confirmed:true}),/invalid_clock/);assert.equal(f.calls.length,0);});
test('MCP blocks unavailable substitute, preserves recorded player after removal',async()=>{const f=fixture();await f.call('control_match_usage',{action:'start',confirmed:true});f.rows.find(p=>p.id===refs[5]).payload.estado_disponibilidade='lesionado';await assert.rejects(f.call('record_match_movement',{action:'substitute',movement_id:'s',out_ref:refs[1],in_ref:refs[5],confirmed:true}),/disponível/);f.rows.find(p=>p.id===refs[1]).deleted_at='now';const out=await f.call('get_match_visual');assert.equal(out.visual_match.roster.length,7);assert.ok(out.usage.players.find(p=>p.ref===refs[1]));});
test('MCP cannot steal active browser timer and refuses deleted match',async()=>{const f=fixture();await f.call('control_match_usage',{action:'start',confirmed:true});f.match.payload.visual_match.controller_id='phone';await assert.rejects(f.call('control_match_usage',{action:'pause'}),/Outro dispositivo/);f.match.deleted_at='now';await assert.rejects(f.call('get_match_visual'),/not_found/);assert.equal(f.calls.length,1);});
