const test=require('node:test'),assert=require('node:assert/strict');
const {SEASON_TOOLS,executeSeasonTool}=require('../supabase/functions/vision-coach-mcp/seasons.mjs');
const TEAM='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',PLAYER='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',DOC='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
class Query{constructor(rows){this.rows=rows;this.filters=[];}select(){return this;}eq(k,v){this.filters.push([k,v]);return this;}is(){return this;}then(ok,no){return Promise.resolve({data:this.rows.filter(r=>this.filters.every(([k,v])=>k==='payload->>external_key'?r.payload.external_key===v:r[k]===v)),error:null}).then(ok,no);}}
function admin(){const records=[{id:PLAYER,team_id:TEAM,kind:'player',payload:{sync_id:PLAYER,nome:'Ana'},updated_at:'old'}],client={from(){return new Query(records);},async rpc(_n,a){const row={id:a.p_record_id||DOC,team_id:TEAM,kind:'document',payload:a.p_payload,updated_at:'new'};const i=records.findIndex(x=>x.id===row.id);if(i<0)records.push(row);else records[i]=row;return{data:row,error:null};}};return{client,records};}
const c={id:'connector',team_id:TEAM,scopes:['read','write']};
test('MCP exposes season read/write with team UUID validation and explicit revision confirmation',async()=>{
 assert.deepEqual(SEASON_TOOLS.map(x=>x.name),['get_team_seasons','save_team_season']);const a=admin(),args={name:'2026/27',start_date:'2026-08-01',end_date:'2027-07-31',roster:[{ref:PLAYER,name:'Ana',number:8}],activate:true,expected_revision:0,confirmed:true};
 assert.equal((await executeSeasonTool(a.client,c,'get_team_seasons',{})).record.items.length,0);const saved=await executeSeasonTool(a.client,c,'save_team_season',args);assert.equal(saved.record.items[0].roster[0].ref,PLAYER);assert.equal(saved.record.active_id,saved.record.items[0].id);assert.equal(saved.external_key,'season-index:default');assert.equal(saved.sync_id,await globalThis.VisionSeasons.stableIndexId('default'));assert.equal(a.records.filter(x=>x.payload?.type==='season_index').length,1);const reread=await executeSeasonTool(a.client,c,'get_team_seasons',{});assert.equal(reread.id,saved.id);assert.equal(reread.external_key,'season-index:default');assert.equal(reread.record.items[0].id,saved.record.items[0].id);
 await assert.rejects(()=>executeSeasonTool(a.client,c,'save_team_season',args),/record_conflict_read_again/);await assert.rejects(()=>executeSeasonTool(a.client,{...c,scopes:['read']},'save_team_season',args),/scope_write/);await assert.rejects(()=>executeSeasonTool(a.client,c,'save_team_season',{...args,confirmed:false}),/explicit_confirmation/);
});
test('MCP runtime validates season and player UUIDs, roster shape and same-team players',async()=>{const a=admin(),args={name:'2026/27',start_date:'2026-08-01',end_date:'2027-07-31',roster:[],expected_revision:0,confirmed:true};assert.equal(SEASON_TOOLS[1].inputSchema.properties.season_id.format,'uuid');await assert.rejects(()=>executeSeasonTool(a.client,c,'save_team_season',{...args,season_id:'not-a-uuid'}),/invalid_season_uuid/);await assert.rejects(()=>executeSeasonTool(a.client,c,'save_team_season',{...args,roster:{}}),/season_roster_required/);await assert.rejects(()=>executeSeasonTool(a.client,c,'save_team_season',{...args,roster:[{ref:'------------------------------------',name:'Ana'}]}),/invalid_player_uuid/);await assert.rejects(()=>executeSeasonTool(a.client,c,'save_team_season',{...args,roster:[{ref:'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',name:'Fora'}]}),/player_reference_not_found_in_team/);});
test('MCP updates the PWA season index by its stable external key and never creates a parallel index',async()=>{const a=admin(),existing=globalThis.VisionSeasons.save(null,{name:'2026/27',start_date:'2026-08-01',end_date:'2027-07-31',roster:[{ref:PLAYER,name:'Ana',number:8}],activate:true},{expected_revision:0}),syncId=await globalThis.VisionSeasons.stableIndexId('default');a.records.push({id:DOC,team_id:TEAM,kind:'document',payload:{type:'season_index',external_key:'season-index:default',sync_id:syncId,body:JSON.stringify(existing)},updated_at:'season-v1'});const read=await executeSeasonTool(a.client,c,'get_team_seasons',{});assert.equal(read.id,DOC);const saved=await executeSeasonTool(a.client,c,'save_team_season',{season_id:existing.items[0].id,name:'2026/27 revisto',start_date:'2026-08-01',end_date:'2027-07-31',roster:[{ref:PLAYER,name:'Ana',number:8}],activate:true,expected_updated_at:'season-v1',expected_revision:1,confirmed:true});assert.equal(saved.id,DOC);assert.equal(saved.sync_id,syncId);assert.equal(saved.external_key,'season-index:default');assert.equal(a.records.filter(x=>x.payload?.type==='season_index').length,1);});
test('MCP season read and write retain prior full season snapshots',async()=>{
 const a=admin(),existing=globalThis.VisionSeasons.save(null,{name:'Época anterior',start_date:'2025-08-01',end_date:'2026-07-31',roster:[{ref:PLAYER,name:'Ana',number:8}],activate:true},{expected_revision:0}),syncId=await globalThis.VisionSeasons.stableIndexId('default');
 a.records.push({id:DOC,team_id:TEAM,kind:'document',payload:{type:'season_index',external_key:'season-index:default',sync_id:syncId,body:JSON.stringify(existing)},updated_at:'season-v1'});
 const changed=await executeSeasonTool(a.client,c,'save_team_season',{season_id:existing.items[0].id,name:'Época revista',start_date:'2025-09-01',end_date:'2026-06-30',roster:[{ref:PLAYER,name:'Ana',number:8}],activate:true,expected_updated_at:'season-v1',expected_revision:1,confirmed:true});
 assert.equal(changed.record.history.at(-1).snapshot.items[0].name,'Época anterior');assert.equal(changed.record.history.at(-1).snapshot.items[0].start_date,'2025-08-01');
 const reread=await executeSeasonTool(a.client,c,'get_team_seasons',{});assert.equal(reread.record.history.at(-1).snapshot.items[0].roster[0].ref,PLAYER);
});
