const test=require('node:test'),assert=require('node:assert/strict');
const {TEAM_DEVELOPMENT_TOOLS,executeTeamDevelopmentTool}=require('../supabase/functions/vision-coach-mcp/team_development.mjs');
const TEAM='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',TRAIN='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',MATCH='cccccccc-cccc-4ccc-8ccc-cccccccccccc',DOC='dddddddd-dddd-4ddd-8ddd-dddddddddddd';
class Query{constructor(rows){this.rows=rows;this.filters=[];this.column=null;}select(){return this;}eq(k,v){this.filters.push([k,v]);return this;}is(){return this;}in(k,v){this.filters.push([k,v]);return this;}then(resolve,reject){let rows=this.rows.filter(r=>this.filters.every(([k,v])=>k==='payload->>type'?v.includes(r.payload.type):k==='payload->>external_key'?r.payload.external_key===v:r[k]===v));return Promise.resolve({data:rows,error:null}).then(resolve,reject);}}
function admin(){const records=[{id:TRAIN,team_id:TEAM,kind:'training',payload:{data:'2026-09-22',review:{status:'done',continua:'Apoio irregular',focus_outcome:'continues'}},updated_at:'training-v1'},{id:MATCH,team_id:TEAM,kind:'match',payload:{data:'2026-09-20',adversario:'Rivais',post_game:{analysis:{fields:{problems:'Perdas na saída'}}},match_events:{events:[{id:'loss-1',type:'loss',at_ms:120000,reason:'pass',zone:'def_c',note:'Passe interceptado'}]}},updated_at:'match-v1'}],client={from(){return new Query(records);},async rpc(_name,args){const row={id:args.p_record_id||crypto.randomUUID(),team_id:TEAM,kind:'document',payload:args.p_payload,updated_at:'doc-v'+(records.filter(x=>x.kind==='document').length+1)};const i=records.findIndex(x=>x.id===row.id);if(i<0)records.push(row);else records[i]=row;return{data:row,error:null};}};return{client,records};}
const c={id:'connector',team_id:TEAM,scopes:['read','write']};
test('MCP exposes semantic operations, supports unfiltered read and guards coach writes',async()=>{
 assert.deepEqual(TEAM_DEVELOPMENT_TOOLS.map(x=>x.name),['get_team_development','prepare_cross_session_priority','accept_team_priority_proposal','dismiss_team_priority_proposal','save_weekly_plan','save_team_development_goal']);const a=admin();assert.deepEqual(await executeTeamDevelopmentTool(a.client,c,'get_team_development',{}),[]);
 const args={week_start:'2026-09-23',objective:'Criar apoio',training1:TRAIN,match:MATCH,relation_note:'Aplicar no jogo',evaluation:'',expected_revision:0,confirmed:true};const saved=await executeTeamDevelopmentTool(a.client,c,'save_weekly_plan',args);assert.equal(saved.external_key,'team-week:2026-09-21');assert.equal(saved.record.training1,TRAIN);
 await assert.rejects(()=>executeTeamDevelopmentTool(a.client,c,'save_weekly_plan',{...args,expected_updated_at:'stale'}),/record_conflict_read_again/);
 await assert.rejects(()=>executeTeamDevelopmentTool(a.client,{...c,scopes:['read']},'save_weekly_plan',args),/scope_write/);
 await assert.rejects(()=>executeTeamDevelopmentTool(a.client,c,'save_weekly_plan',{...args,confirmed:false}),/explicit_confirmation/);
 const goalArgs={external_key:'team-goal:test',title:'Apoio na saída',identified_at:'2026-09-20',stage:'evaluated',sessions:[{type:'training',id:TRAIN},{type:'match',id:MATCH}],evidence:[{type:'training',id:TRAIN}],evaluation:'O apoio esteve disponível em duas sessões.',coach_decision:'Manter este foco.',expected_revision:0,confirmed:true};
 assert.equal(TEAM_DEVELOPMENT_TOOLS.find(x=>x.name==='save_team_development_goal').inputSchema.properties.evaluation.type,'string');
 await assert.rejects(executeTeamDevelopmentTool(a.client,c,'save_team_development_goal',{...goalArgs,evaluation:''}),/avaliação do treinador/);
 const goal=await executeTeamDevelopmentTool(a.client,c,'save_team_development_goal',goalArgs);assert.equal(goal.record.evaluation,goalArgs.evaluation);assert.equal(goal.record.coach_decision,goalArgs.coach_decision);
});
test('cross-session proposal validates exact current evidence, is idempotent, and requires coach decision to accept',async()=>{
 const a=admin(),evidence=[{source_type:'match',source_ref:MATCH,field:'analysis.problems',quote:'Perdas na saída',record_updated_at:'match-v1'},{source_type:'training',source_ref:TRAIN,field:'review.continua',quote:'Apoio irregular',record_updated_at:'training-v1'}],args={title:'Apoio na saída',rationale:'A dificuldade aparece no jogo e na avaliação seguinte.',hypothesis:'Confirmar se acontece sob pressão.',evidence,confirmed:true};
 await assert.rejects(executeTeamDevelopmentTool(a.client,{...c,scopes:['read']},'prepare_cross_session_priority',args),/scope_write/);
 await assert.rejects(executeTeamDevelopmentTool(a.client,c,'prepare_cross_session_priority',{...args,evidence:[{...evidence[0],quote:'texto inventado'}]}),/evidence_quote_mismatch/);
 await assert.rejects(executeTeamDevelopmentTool(a.client,c,'prepare_cross_session_priority',{...args,evidence:[{...evidence[0],record_updated_at:'old'},evidence[1]]}),/evidence_source_changed/);
 await assert.rejects(executeTeamDevelopmentTool(a.client,{...c,team_id:'ffffffff-ffff-4fff-8fff-ffffffffffff'},'prepare_cross_session_priority',args),/evidence_source_not_found_in_team/);
 const prepared=await executeTeamDevelopmentTool(a.client,c,'prepare_cross_session_priority',args);assert.equal(prepared.record.stage,'identified');assert.equal(prepared.record.agent_proposal.status,'proposed');assert.equal(prepared.record.coach_decision,'');assert.equal(prepared.record.sessions.length,2);assert.equal(prepared.record.agent_proposal.evidence_refs.length,2);
 const repeated=await executeTeamDevelopmentTool(a.client,c,'prepare_cross_session_priority',args);assert.equal(repeated.already_prepared,true);assert.equal(a.records.filter(x=>x.kind==='document').length,1);
 await assert.rejects(executeTeamDevelopmentTool(a.client,c,'accept_team_priority_proposal',{id:prepared.id,expected_updated_at:prepared.updated_at,expected_revision:prepared.record.revision,coach_decision:'',confirmed:true}),/coach_decision_required/);
 await assert.rejects(executeTeamDevelopmentTool(a.client,c,'accept_team_priority_proposal',{id:prepared.id,expected_updated_at:'stale',expected_revision:prepared.record.revision,coach_decision:'Aceito.',confirmed:true}),/record_conflict/);
 const matchRow=a.records.find(x=>x.id===MATCH);matchRow.updated_at='match-v2';await assert.rejects(executeTeamDevelopmentTool(a.client,c,'accept_team_priority_proposal',{id:prepared.id,expected_updated_at:prepared.updated_at,expected_revision:prepared.record.revision,coach_decision:'Aceito.',confirmed:true}),/evidence_source_changed/);matchRow.updated_at='match-v1';
 const accepted=await executeTeamDevelopmentTool(a.client,c,'accept_team_priority_proposal',{id:prepared.id,expected_updated_at:prepared.updated_at,expected_revision:prepared.record.revision,coach_decision:'Aceito trabalhar este princípio.',confirmed:true});assert.equal(accepted.record.agent_proposal.status,'accepted');assert.equal(accepted.record.coach_decision,'Aceito trabalhar este princípio.');assert.equal(a.records.filter(x=>x.kind==='document').length,1);
 await assert.rejects(executeTeamDevelopmentTool(a.client,c,'dismiss_team_priority_proposal',{id:prepared.id,expected_updated_at:accepted.updated_at,expected_revision:accepted.record.revision,confirmed:true}),/proposal_not_pending/);
});
test('dismissing a proposal needs confirmation and preserves its evidence/history',async()=>{
 const a=admin(),evidence=[{source_type:'training',source_ref:TRAIN,field:'review.continua',quote:'Apoio irregular',record_updated_at:'training-v1'}],args={title:'Apoio no treino',rationale:'Foco proposto a partir da avaliação.',evidence,confirmed:true},prepared=await executeTeamDevelopmentTool(a.client,c,'prepare_cross_session_priority',args);
 await assert.rejects(executeTeamDevelopmentTool(a.client,c,'dismiss_team_priority_proposal',{id:prepared.id,expected_updated_at:prepared.updated_at,expected_revision:prepared.record.revision,confirmed:false}),/explicit_confirmation/);
 const result=await executeTeamDevelopmentTool(a.client,c,'dismiss_team_priority_proposal',{id:prepared.id,expected_updated_at:prepared.updated_at,expected_revision:prepared.record.revision,confirmed:true});assert.equal(result.record.agent_proposal.status,'dismissed');assert.equal(result.record.agent_proposal.evidence_refs[0].quote,'Apoio irregular');assert.equal(result.record.history.at(-1).agent_proposal.status,'proposed');assert.equal(a.records.filter(x=>x.kind==='document').length,1);
});
test('new source revision creates a new proposal identity instead of reusing stale evidence',async()=>{
 const a=admin(),base={title:'Apoio na saída',rationale:'Relacionar avaliações.',evidence:[{source_type:'training',source_ref:TRAIN,field:'review.continua',quote:'Apoio irregular',record_updated_at:'training-v1'}],confirmed:true},first=await executeTeamDevelopmentTool(a.client,c,'prepare_cross_session_priority',base),training=a.records.find(x=>x.id===TRAIN);training.updated_at='training-v2';training.payload.review.continua='Apoio irregular sob pressão';
 const refreshed=await executeTeamDevelopmentTool(a.client,c,'prepare_cross_session_priority',{...base,rationale:'A avaliação mais recente acrescenta o contexto de pressão.',evidence:[{...base.evidence[0],quote:'Apoio irregular sob pressão',record_updated_at:'training-v2'}]});assert.notEqual(refreshed.id,first.id);assert.equal(refreshed.record.agent_proposal.evidence_refs[0].quote,'Apoio irregular sob pressão');assert.equal(a.records.filter(x=>x.kind==='document').length,2);
});
