const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../js/training_continuity.js');
const ID='b713b656-0c4d-4455-b945-c51791b28580',EX='7cc9d2a9-f492-4ffd-b67f-fd8c70128140';
const exercises=()=>[{id:7,sync_id:EX,workspace_v2:true,status:'active',nome:'Apoio',objetivo:'Dar opção',duracao_total_min:10}];
const row=()=>({id:5,sync_id:ID,team_id:'default',data:'2026-09-21',hora:'19:15',objetivo:'Passar e apoiar',blocos:[{exercise_ref:EX,phase:'principal',duration_min:10}],session:{status:'completed',blocks:[{key:'b',exercise_name:'Apoio',notes:[{id:'n',text:'Precisam de voltar a dar opção.'}]}]},review:{status:'done',melhorou:'Passe',continua:'Apoio após passe',proxima_acao:'Passar e mexer',conclusao:'Repetir'}});
async function draft(r=row()){return C.prepare(r,exercises(),await C.identities(r),{now:0});}
function change(r,extra={}){return C.update(r,{...r.continuity.proposal,success_criterion:'Observar apoios sem indicação',date:'2026-09-24',time:'19:15',...extra},exercises(),{expected_revision:r.continuity.revision,now:1});}
test('identities are deterministic across device-local IDs; target is unique per source',async()=>{const a=await C.identities(row()),b=await C.identities({...row(),id:99});assert.deepEqual(a,b);const changed=await C.identities({...row(),review:{...row().review,continua:'Novo foco'}});assert.equal(a.target_ref,changed.target_ref);assert.equal(a.memory_ref,changed.memory_ref);assert.notEqual(a.proposal_id,changed.proposal_id);assert.match(a.memory_ref,/^[a-f0-9-]{36}$/);});
test('no proposal without recorded next action or remaining issue',async()=>{for(const review of [{status:'pending'},{status:'done',melhorou:'Tudo bem'}]){const r={...row(),review};assert.throws(()=>C.prepare(r,exercises(),{}));}});
test('evidence uses exact recorded quotes, not generated claims',async()=>{const r=await draft();assert.equal(r.continuity.proposal.objective,'Passar e mexer');assert.equal(r.continuity.proposal.method,'review_template');assert.equal(r.continuity.proposal.success_criterion,'');assert.equal(r.continuity.proposal.evidence.length,5);assert.equal(r.continuity.proposal.evidence[4].quote,'Precisam de voltar a dar opção.');});
test('continuity reads a completed session review when plan review is empty',async()=>{const r={...row(),review:{},session:{...row().session,review:{status:'done',continua:'Apoio irregular',proxima_acao:'Passar e mexer',focus_outcome:'continues'}}};assert.equal(C.effectiveReview(r).status,'done');assert.equal(C.evidence(r)[0].quote,'Apoio irregular');assert.equal(C.sourceData(r).review.continua,'Apoio irregular');const prepared=await draft(r);assert.equal(prepared.continuity.proposal.objective,'Passar e mexer');assert.equal(C.memory(r,await C.identities(r)).status,'active');const saved=C.saveReview(r,{melhorou:'Melhorou',continua:'Apoio irregular',proxima_acao:'Passar e mexer'},{expected_review_key:C.reviewKey(C.effectiveReview(r)),now:0});assert.equal(saved.review.status,'done');assert.equal(saved.review.melhorou,'Melhorou');});
test('review updates preserve plan/session and require exact rendered review baseline',()=>{const r=row(),next=C.saveReview(r,{continua:'Rever cobertura',focus_outcome:'continues'},{expected_review_key:C.reviewKey(r.review),now:0});assert.equal(next.review.status,'done');assert.deepEqual(next.session,r.session);assert.deepEqual(next.blocos,r.blocos);assert.throws(()=>C.saveReview(next,{continua:'stale'},{expected_review_key:C.reviewKey(r.review)}),/mudou/);assert.throws(()=>C.saveReview(r,{},{expected_review_key:C.reviewKey(r.review)}),/observação/);});
test('one managed memory retains source and removal archives rather than invents new observation',async()=>{const r=row(),ids=await C.identities(r),m=C.memory(r,ids);assert.equal(m.external_key,'training-review-'+ID);assert.equal(m.status,'active');assert.equal(m.subject_refs[0].id,ID);const cleared=C.clearReview(r,{expected_review_key:C.reviewKey(r.review),confirmed:true});assert.equal(C.memory(cleared,ids).status,'archived');assert.deepEqual(cleared.session,r.session);});
test('proposal requires explicit approval and all planning fields',async()=>{let r=await draft();assert.throws(()=>C.approve(r,exercises(),{expected_revision:1}),/explícita/);assert.throws(()=>C.approve(r,exercises(),{expected_revision:1,confirmed:true}),/data/);r=change(r);const approved=C.approve(r,exercises(),{expected_revision:2,confirmed:true,now:2});assert.equal(approved.target.source_training_ref,ID);assert.equal(approved.target.session,undefined);assert.equal(approved.target.review.status,'pending');assert.equal(approved.target.continuity_origin.evidence.length,5);assert.equal(approved.source.continuity.proposal.status,'approved');assert.equal(approved.target.blocos[0].exercise_ref,EX);});
test('stale proposal after edited evidence is refused even if its revision matches',async()=>{let r=change(await draft());r.session.blocks[0].notes[0].text='Nova observação';assert.throws(()=>C.approve(r,exercises(),{expected_revision:r.continuity.revision,confirmed:true}),/mudou/);assert.throws(()=>change(r),/origem mudou/);});
test('changed or deleted exercises cannot be silently approved',async()=>{const r=change(await draft()),changed=exercises();changed[0].objetivo='Outro';assert.throws(()=>C.approve(r,changed,{expected_revision:2,confirmed:true}),/ficha/);assert.throws(()=>C.approve(r,[],{expected_revision:2,confirmed:true}),/apagado/);});
test('dates, duration, phase, empty selection and missing success criterion validated',async()=>{const base=await draft();for(const patch of [{date:'2026-02-31'},{date:'2026-09-21'},{time:'25:00'},{success_criterion:''},{blocks:[]}]){const r=change(base,patch);assert.throws(()=>C.approve(r,exercises(),{expected_revision:2,confirmed:true}));}assert.throws(()=>change(base,{blocks:[{exercise_ref:EX,duration_min:-1,phase:'principal'}]}));});
test('dismissal needs confirmation, preserves review, permits a new draft',async()=>{const r=await draft();assert.throws(()=>C.dismiss(r,{expected_revision:1}),/Confirma/);const gone=C.dismiss(r,{expected_revision:1,confirmed:true});assert.equal(gone.continuity.proposal.status,'dismissed');assert.deepEqual(gone.review,r.review);assert.equal((await draft(gone)).continuity.proposal.status,'draft');});
test('approval cannot be deleted as a draft or generate a second next session',async()=>{const r=change(await draft()),a=C.approve(r,exercises(),{expected_revision:2,confirmed:true});assert.throws(()=>C.dismiss(a.source,{expected_revision:3,confirmed:true}),/aprovação/);assert.throws(()=>C.prepare(a.source,exercises(),{}),/Já existe/);});
test('progress is explicit and never infers improvement from timer/presence',async()=>{const r=change(await draft()),a=C.approve(r,exercises(),{expected_revision:2,confirmed:true});assert.equal(C.progress(a.source,a.target).stage,'created');a.target.session={status:'completed'};assert.equal(C.progress(a.source,a.target).stage,'trained');a.target.review={status:'done',focus_outcome:'continues'};assert.equal(C.progress(a.source,a.target).outcome,'Continua por corrigir');});
test('memory refuses broken identities; unknown schema does not erase data',async()=>{await assert.rejects(C.identities({...row(),sync_id:'5'}));assert.throws(()=>C.state({continuity:{schema:'future'}}));});
