const test=require('node:test'),assert=require('node:assert/strict');
let api;test.before(async()=>{api=await import('../supabase/functions/vision-coach-mcp/training_sessions.mjs');});
const c={id:'connector',team_id:'team',scopes:['read','write']};
function fixture(){
 const training={id:'t',team_id:'team',kind:'training',deleted_at:null,updated_at:'v0',payload:{data:'2026-09-24',external_key:'training-test',objetivo:'Original',blocos:[{block_id:'block',exercise_name:'Passe',exercise_ref:'exercise',duration_min:10}]}};
 const player={id:'p',team_id:'team',kind:'player',deleted_at:null,payload:{nome:'Atleta teste',numero:2}};
 const rows=[training,player],audits=[];
 const admin={from(){const filters=[];return {select(){return this;},eq(key,value){filters.push(r=>(key==='payload->>external_key'?r.payload.external_key:r[key])===value);return this;},is(key,value){return this.eq(key,value);},then(resolve){return Promise.resolve({data:rows.filter(r=>filters.every(f=>f(r))).map(r=>structuredClone(r))}).then(resolve);}}},async rpc(name,args){assert.equal(name,'head_coach_put_record');const row=rows.find(r=>r.id===args.p_record_id);if(row){if(row.updated_at!==args.p_expected_updated_at)return {error:new Error('record_conflict')};row.payload=structuredClone(args.p_payload);row.updated_at='v'+(audits.length+1);}audits.push(args);return {data:{saved:true}};}};
 return {admin,training,player,audits,call:(name,args)=>api.executeSessionTool(admin,c,name,{id:'t',expected_updated_at:training.updated_at,expected_revision:training.payload.session?.revision||0,...args})};
}
test('MCP tools expose all six field-session operations',()=>{assert.equal(api.SESSION_TOOLS.length,6);assert.equal(new Set(api.SESSION_TOOLS.map(t=>t.name)).size,6);});
test('MCP read does not start a session or write data',async()=>{const f=fixture(),r=await f.call('get_training_session',{});assert.equal(r.session.status,'not_started');assert.equal(f.audits.length,0);});
test('MCP checks scopes, team and exact identity before writing',async()=>{const f=fixture();await assert.rejects(api.executeSessionTool(f.admin,{...c,scopes:['read']},'update_training_attendance',{id:'t'}),/scope_write/);await assert.rejects(api.executeSessionTool(f.admin,{...c,team_id:'other'},'get_training_session',{id:'t'}),/not_found/);await assert.rejects(f.call('get_training_session',{external_key:'training-test'}),/exactly_one/);assert.equal(f.audits.length,0);});
test('MCP attendance resolves real team player names and rejects foreign player',async()=>{const f=fixture();await f.call('update_training_attendance',{entries:[{player_ref:'p',status:'present'}]});assert.equal(f.training.payload.session.attendance[0].name,'Atleta teste');assert.equal(f.training.payload.objetivo,'Original');await assert.rejects(f.call('update_training_attendance',{entries:[{player_ref:'other',status:'present'}]}),/not_in_team/);assert.equal(f.audits.length,1);});
test('MCP control, notes and removal share browser invariants',async()=>{const f=fixture();await f.call('control_training_session',{action:'start'});assert.equal(f.training.payload.session.controller_id,'mcp:connector');await f.call('write_training_session_note',{block_key:'block',note_id:'n',text:'Boa execução'});assert.equal(f.training.payload.session.blocks[0].notes.length,1);await assert.rejects(f.call('remove_training_session_note',{block_key:'block',note_id:'n',confirmed:false}),/Confirma/);await f.call('remove_training_session_note',{block_key:'block',note_id:'n',confirmed:true});await f.call('control_training_session',{action:'pause'});await f.call('control_training_session',{action:'finish',confirmed:true});assert.equal(f.training.payload.session.status,'completed');});
test('MCP stale session/remote versions never overwrite newer data',async()=>{const f=fixture();await assert.rejects(f.call('control_training_session',{action:'start',expected_updated_at:'stale'}),/conflict/);await f.call('control_training_session',{action:'start'});await assert.rejects(f.call('control_training_session',{action:'pause',expected_revision:0}),/mudou/);assert.equal(f.audits.length,1);});
test('MCP duplicate is scoped and uses idempotency while dropping actual-session data',async()=>{const f=fixture();await f.call('control_training_session',{action:'start'});await f.call('duplicate_training_plan',{date:'2026-09-28',request_key:'repeat-safe'});const args=f.audits[1];assert.equal(args.p_team_id,'team');assert.equal(args.p_payload.source_training_ref,'t');assert.equal(args.p_payload.session,undefined);assert.equal(args.p_idempotency_key,'training-copy:connector-repeat-safe');});
