const test=require('node:test'),assert=require('node:assert/strict');
let api;test.before(async()=>{api=await import('../supabase/functions/vision-coach-mcp/training_continuity.mjs');});
const ID='b713b656-0c4d-4455-b945-c51791b28580',EX='7cc9d2a9-f492-4ffd-b67f-fd8c70128140';
const c={id:'connector',team_id:'team',scopes:['read','write']};
function fixture(){
 const source={id:ID,team_id:'team',kind:'training',deleted_at:null,updated_at:'v0',payload:{data:'2026-09-21',hora:'19:15',external_key:'continuity-test',objetivo:'Apoiar',blocos:[{exercise_ref:EX,phase:'principal',duration_min:10}],review:{status:'done',melhorou:'Passe',continua:'Apoio'}}};
 const exercise={id:EX,team_id:'team',kind:'exercise',deleted_at:null,updated_at:'e0',payload:{workspace_v2:true,status:'active',nome:'Apoio',objetivo:'Dar opção',duracao_total_min:10}};
 const rows=[source,exercise],calls=[],contextCalls=[];
 const admin={from(){const filters=[];return {select(){return this;},eq(key,value){filters.push(r=>(key==='payload->>external_key'?r.payload.external_key:r[key])===value);return this;},is(key,value){return this.eq(key,value);},then(resolve){return Promise.resolve({data:rows.filter(r=>filters.every(f=>f(r))).map(r=>structuredClone(r))}).then(resolve);}}},async rpc(name,args){assert.equal(name,'head_coach_commit_training_continuity');assert.equal(args.p_team_id,'team');assert.equal(args.p_expected_updated_at,source.updated_at);calls.push(args);const v=args.p_change;source.payload=structuredClone(v.source);source.updated_at='v'+calls.length;let m=rows.find(x=>x.id===v.memory_ref);if(!m){m={id:v.memory_ref,kind:'memory',team_id:'team',deleted_at:null};rows.push(m);}m.payload=structuredClone(v.memory);if(v.target){assert.equal(v.action,'approve');rows.push({id:v.target_ref,team_id:'team',kind:'training',payload:structuredClone(v.target),updated_at:'child',deleted_at:null});}return {data:{memory_linked:true}};}};
 const getPlanningContext=async args=>{contextCalls.push(args);return {schema:'vision-training-planning-context@1',target_date:args.target_date,team:{age_group:'Sub-8'},target_training:{ref:'d713b656-0c4d-4455-b945-c51791b28580',updated_at:'plan-v1',planned_minutes:60},roster:{available_count:4,unavailable_count:1,unknown_availability_count:0},recent_matches:[{ref:'e713b656-0c4d-4455-b945-c51791b28580',updated_at:'match-v1',date:'2026-09-20',opponent:'Rival',result:{for:1,against:2},registered_event_counts:{losses:3}}],recent_trainings:[{ref:'f713b656-0c4d-4455-b945-c51791b28580',updated_at:'training-v1',date:'2026-09-22',objective:'Apoio',planned_minutes:60,reviewed:true}],recent_exercise_use:[{exercise_ref:EX,uses:2}],recent_exercise_use_status:'recorded',semantic_evidence:[{source:{kind:'match',ref:'e713b656-0c4d-4455-b945-c51791b28580',date:'2026-09-20',path:'post_game.analysis',updated_at:'match-v1'},title:'Pressão',excerpt:'Perdas na saída curta sob pressão.'}],semantic_retrieval_statuses:['ready'],evidence_status:'sources_found',missing_data:{availability:false,semantic_evidence:false}};};
 const call=(name,args={})=>api.executeContinuityTool(admin,c,name,{id:ID,expected_updated_at:source.updated_at,expected_revision:source.payload.continuity?.revision||0,...args},{getPlanningContext});return {rows,source,exercise,admin,call,calls,contextCalls};
}
async function prepare(f){await f.call('prepare_training_continuity',{target_date:'2026-09-24'});const p=f.source.payload.continuity.proposal;await f.call('update_training_continuity',{changes:{...p,date:'2026-09-24',time:'19:15',success_criterion:'Apoiar sem indicação'}});}
test('seven tools use stable UUID references; read is side-effect-free',async()=>{assert.equal(api.CONTINUITY_TOOLS.length,7);assert.equal(api.CONTINUITY_TOOLS[0].inputSchema.properties.id.format,'uuid');assert.equal(api.CONTINUITY_TOOLS[4].inputSchema.properties.changes.properties.blocks.items.properties.exercise_ref.format,'uuid');const f=fixture(),r=await f.call('get_training_continuity');assert.equal(r.continuity.proposal,null);assert.equal(r.evidence[1].quote,'Apoio');assert.equal(f.calls.length,0);await assert.rejects(api.executeContinuityTool(f.admin,c,'get_training_continuity',{id:'local-17'}),/invalid_training_uuid/);});
test('MCP continuity reads and saves a nested session review when the plan review is empty',async()=>{const f=fixture();f.source.payload.review={};f.source.payload.session={status:'completed',review:{status:'done',melhorou:'Passe',continua:'Apoio',proxima_acao:'Passar e mexer'}};const read=await f.call('get_training_continuity');assert.equal(read.review.status,'done');assert.equal(read.evidence[0].quote,'Passe');await f.call('save_training_review',{confirmed:true,review:{conclusao:'Manter'}});assert.equal(f.source.payload.review.melhorou,'Passe');assert.equal(f.source.payload.review.conclusao,'Manter');assert.equal(f.calls.at(-1).p_change.memory.status,'active');});
test('read/write scopes and exact team identity enforced before RPC',async()=>{const f=fixture();await assert.rejects(api.executeContinuityTool(f.admin,{...c,scopes:['read']},'save_training_review',{id:ID}),/scope_write/);await assert.rejects(api.executeContinuityTool(f.admin,{...c,team_id:'other'},'get_training_continuity',{id:ID}),/not_found/);await assert.rejects(f.call('get_training_continuity',{external_key:'continuity-test'}),/exactly_one/);assert.equal(f.calls.length,0);});
test('partial coach review retains existing content and commits source+memory once only after explicit confirmation',async()=>{const f=fixture();await assert.rejects(f.call('save_training_review',{review:{proxima_acao:'Passar e mexer'}}),/explicit_confirmation_required/);await f.call('save_training_review',{confirmed:true,review:{proxima_acao:'Passar e mexer'}});assert.equal(f.source.payload.review.melhorou,'Passe');assert.equal(f.calls.length,1);const q=f.calls[0].p_change;assert.equal(q.memory.metadata.managed_by,'training_review_v1');assert.equal(q.target,null);assert.equal(q.source.objetivo,'Apoiar');});
test('unchanged draft returns as-is without overwriting human adjustments',async()=>{const f=fixture();await prepare(f);const before=structuredClone(f.source.payload.continuity.proposal);const r=await f.call('prepare_training_continuity');assert.equal(r.already_prepared,true);assert.deepEqual(f.source.payload.continuity.proposal,before);assert.equal(f.calls.length,2);});
test('continuity preparation attaches cited hybrid context and remains a draft until explicit approval',async()=>{const f=fixture();const result=await f.call('prepare_training_continuity',{target_date:'2026-09-24'});const p=result.continuity.proposal;assert.equal(f.contextCalls.length,1);assert.deepEqual(f.contextCalls[0],{target_date:'2026-09-24',question:'Apoio'});assert.equal(p.status,'draft');assert.equal(p.method,'hybrid_context_draft');assert.equal(p.planning_context.roster.available_count,4);assert.equal(p.planning_context.recent_exercise_use[0].uses,2);assert.equal(p.evidence.at(-1).source_ref,'e713b656-0c4d-4455-b945-c51791b28580');assert.equal(p.evidence.at(-1).quote,'Perdas na saída curta sob pressão.');assert.equal(f.calls.length,1);assert.equal(f.calls[0].p_change.target,null);await assert.rejects(f.call('update_training_continuity',{changes:{...p,date:'2026-09-25',time:'19:15',success_criterion:'Apoiar'}}),/data mudou em relação ao contexto/);assert.equal(f.calls.length,1);});
test('continuity draft stores recent match, training and semantic evidence from the real hybrid retriever',async()=>{
 const rag=await import('../supabase/functions/vision-coach-mcp/team_knowledge.mjs');
 const teamId='10000000-0000-4000-8000-000000000001',sourceId='b713b656-0c4d-4455-b945-c51791b28580',exerciseId=EX;
 const matchId='e713b656-0c4d-4455-b945-c51791b28580',targetId='d713b656-0c4d-4455-b945-c51791b28580',priorTrainingId='f713b656-0c4d-4455-b945-c51791b28580';
 const row=(id,kind,payload,updated_at='v1')=>({id,team_id:teamId,kind,payload,updated_at,deleted_at:null});
 const source=row(sourceId,'training',{data:'2026-09-21',hora:'19:15',objetivo:'Apoio',blocos:[{exercise_ref:exerciseId,phase:'principal',duration_min:10}],review:{status:'done',melhorou:'Passe',continua:'Apoio'}});
 const match=row(matchId,'match',{data:'2026-09-20',estado:'concluido',adversario:'Rival',golos_favor:1,golos_contra:2,post_game:{analysis:{fields:{problems:'O treinador registou perdas na saída curta sob pressão alta.'}}},match_events:{events:[{id:'loss-1',type:'loss',minute:4,zone:'def_c',reason:'pass'}]}});
 const target=row(targetId,'training',{data:'2026-09-24',hora:'19:15',objetivo:'Treino de quinta',duracao_min:60,blocos:[{exercise_ref:exerciseId,exercise_name:'Apoio',duration_min:15}]});
 const prior=row(priorTrainingId,'training',{data:'2026-09-22',objetivo:'Apoio após passe',duracao_min:60,status:'completed',session:{status:'completed',blocks:[{key:'used',exercise_ref:exerciseId,exercise_name:'Apoio',done:true,elapsed_ms:900000}],review:{status:'done',melhorou:'O apoio surgiu mais cedo, mas continua irregular.'}}});
 const records=[source,match,target,prior,row(exerciseId,'exercise',{workspace_v2:true,status:'active',nome:'Apoio',objetivo:'Dar opção após passe',duracao_total_min:15}),row('30000000-0000-4000-8000-000000000004','player',{nome:'Atleta A',plantel_ativo:true,estado_disponibilidade:'disponivel'}),row('40000000-0000-4000-8000-000000000004','game_model',{title:'Sub-8',principles:['Dar apoio após passe.']})];
 const filtersFor=(item,key)=>key==='payload->session->>status'?item.payload?.session?.status:key.startsWith('payload->>')?item.payload?.[key.slice(10)]:item[key];
 const searchResults=[{source_id:matchId,source_kind:'match',source_path:'post_game.analysis.fields.problems',source_updated_at:match.updated_at,source_date:'2026-09-20',match_ref:matchId,training_ref:null,player_ref:null,category:'match_analysis',evidence_type:'coach_observation',title:'Problema no jogo',content:'O treinador registou perdas na saída curta sob pressão alta.',metadata:{},similarity:.91,lexical_rank:.1},{source_id:priorTrainingId,source_kind:'training',source_path:'session.review.melhorou',source_updated_at:prior.updated_at,source_date:'2026-09-22',match_ref:null,training_ref:priorTrainingId,player_ref:null,category:'training_review',evidence_type:'coach_observation',title:'Avaliação do treino',content:'O apoio surgiu mais cedo, mas continua irregular.',metadata:{},similarity:.88,lexical_rank:.08}];
 const admin={from(table){const filters=[],orders=[];let limit=Infinity,start=0,end=Infinity;const candidates=table==='teams'?[{id:teamId,metadata:{escalao:'Sub-8'}}]:table==='workspace_records'?records:[];const query={select(){return this;},eq(key,value){filters.push(item=>filtersFor(item,key)===value);return this;},lt(key,value){filters.push(item=>String(filtersFor(item,key)??'')<value);return this;},in(key,values){filters.push(item=>values.includes(filtersFor(item,key)));return this;},is(key,value){filters.push(item=>filtersFor(item,key)==null&&value===null);return this;},or(){filters.push(item=>item.payload?.status==='completed'||item.payload?.session?.status==='completed');return this;},order(key,options={}){orders.push([key,options.ascending!==false]);return this;},limit(value){limit=value;return this;},range(from,to){start=from;end=to;return this;},maybeSingle(){return Promise.resolve({data:candidates.find(item=>filters.every(test=>test(item)))||null,error:null});},then(resolve){let data=candidates.filter(item=>filters.every(test=>test(item)));for(const[key,ascending]of orders.slice().reverse())data.sort((a,b)=>String(filtersFor(a,key)??'').localeCompare(String(filtersFor(b,key)??''))*(ascending?1:-1));data=data.slice(0,limit).slice(start,end+1);return Promise.resolve({data,error:null}).then(resolve);}};return query;},async rpc(name,args){if(name==='claim_team_knowledge_jobs')return{data:[]};if(name==='search_team_knowledge_chunks')return{data:searchResults};assert.equal(name,'head_coach_commit_training_continuity');assert.equal(args.p_team_id,teamId);source.payload=structuredClone(args.p_change.source);source.updated_at='saved';return{data:{memory_linked:true}};}};
 const connector={id:'connector',team_id:teamId,scopes:['read','write']},providerCalls=[];
 const provider={apiKey:'synthetic-test-key',fetchImpl:async(_url,init)=>{providerCalls.push(JSON.parse(init.body));const input=providerCalls.at(-1).input;return{ok:true,status:200,async json(){return{data:input.map((_,index)=>({index,embedding:Array.from({length:rag.teamKnowledgeTestAPI.DIMENSIONS},(_,dimension)=>dimension===0?1:0)}))};}};}};
 const result=await api.executeContinuityTool(admin,connector,'prepare_training_continuity',{id:sourceId,expected_updated_at:source.updated_at,expected_revision:0,target_date:'2026-09-24'},{getPlanningContext:args=>rag.executeTeamKnowledgeTool(admin,connector,'get_training_planning_context',args,{provider})});
 const proposal=result.continuity.proposal;
 assert.equal(proposal.status,'draft');assert.equal(proposal.planning_context.team.age_group,'Sub-8');assert.equal(proposal.planning_context.target_training.planned_minutes,60);
 assert.equal(proposal.planning_context.roster.available_count,1);assert.deepEqual(proposal.planning_context.recent_matches.map(item=>item.ref),[matchId]);assert.deepEqual(proposal.planning_context.recent_trainings.map(item=>item.ref),[priorTrainingId]);
 assert.deepEqual(proposal.planning_context.recent_exercise_use.map(item=>item.exercise_ref),[exerciseId]);assert.equal(proposal.planning_context.semantic_retrieval_statuses[0],'ready');
 assert.ok(proposal.evidence.some(item=>item.source_ref===matchId&&item.provenance==='counted_or_manual'));assert.ok(proposal.evidence.some(item=>item.source_ref===matchId&&item.provenance==='retrieved'&&item.quote.includes('perdas na saída curta')));
 assert.ok(proposal.evidence.some(item=>item.source_ref===priorTrainingId&&item.provenance==='retrieved'&&item.quote.includes('continua irregular')));
 assert.equal(providerCalls.length,2,'only synthetic local embedding requests were sent');assert.equal(result.saved,true);assert.equal(records.filter(item=>item.kind==='training').length,3,'preparation creates no follow-up training');
});
test('approval needs confirmation, uses one transaction and is replay-safe',async()=>{const f=fixture();await prepare(f);await assert.rejects(f.call('approve_training_continuity',{confirmed:false}),/aprovação explícita/);const approved=await f.call('approve_training_continuity',{confirmed:true});assert.ok(approved.followup);assert.equal(f.calls.length,3);const q=f.calls[2].p_change;assert.equal(q.target.source_training_ref,ID);assert.equal(q.target.session,undefined);assert.deepEqual(q.exercise_versions,[{id:EX,updated_at:'e0'}]);const again=await f.call('approve_training_continuity',{confirmed:true,expected_updated_at:'stale',expected_revision:0});assert.equal(again.already_approved,true);assert.equal(f.calls.length,3);});
test('deleted approved child is not recreated on retry',async()=>{const f=fixture();await prepare(f);const result=await f.call('approve_training_continuity',{confirmed:true});f.rows.find(r=>r.id===result.followup.id).deleted_at='deleted';await assert.rejects(f.call('approve_training_continuity',{confirmed:true}),/deleted/);assert.equal(f.calls.length,3);});
test('stale remote version, review and exercise changes refuse approval',async()=>{const f=fixture();await prepare(f);await assert.rejects(f.call('approve_training_continuity',{confirmed:true,expected_updated_at:'old'}),/conflict/);f.exercise.payload.objetivo='Outro objetivo';await assert.rejects(f.call('approve_training_continuity',{confirmed:true}),/ficha/);f.source.payload.review.continua='Novo';await assert.rejects(f.call('approve_training_continuity',{confirmed:true}),/mudou/);assert.equal(f.calls.length,2);});
test('dismissal and review removal preserve the plan and archive source memory',async()=>{const f=fixture();await prepare(f);await f.call('dismiss_training_continuity',{confirmed:true});assert.equal(f.source.payload.continuity.proposal.status,'dismissed');await f.call('clear_training_review',{confirmed:true});assert.equal(f.source.payload.review.status,'pending');assert.equal(f.calls.at(-1).p_change.memory.status,'archived');assert.equal(f.source.payload.blocos.length,1);});
