const test=require('node:test'),assert=require('node:assert/strict');
let api;test.before(async()=>{api=await import('../supabase/functions/vision-coach-mcp/training_sessions.mjs');});
const c={id:'connector',team_id:'team',scopes:['read','write']};
const T='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',P='cccccccc-cccc-4ccc-8ccc-cccccccccccc',X='dddddddd-dddd-4ddd-8ddd-dddddddddddd',BLOCK='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',P2='ffffffff-ffff-4fff-8fff-ffffffffffff';
function fixture(){
 const training={id:T,team_id:'team',kind:'training',deleted_at:null,updated_at:'v0',payload:{data:'2026-09-24',external_key:'training-test',objetivo:'Original',blocos:[{block_id:BLOCK,exercise_name:'Passe',exercise_ref:X,duration_min:10}]}};
 const player={id:P,team_id:'team',kind:'player',deleted_at:null,payload:{nome:'Atleta teste',numero:2}};
 const rows=[training,player],audits=[];
 const admin={from(){const filters=[];return {select(){return this;},eq(key,value){filters.push(r=>(key==='payload->>external_key'?r.payload.external_key:r[key])===value);return this;},is(key,value){return this.eq(key,value);},then(resolve){return Promise.resolve({data:rows.filter(r=>filters.every(f=>f(r))).map(r=>structuredClone(r))}).then(resolve);}}},async rpc(name,args){assert.equal(name,'head_coach_put_record');const row=rows.find(r=>r.id===args.p_record_id);if(row){if(row.updated_at!==args.p_expected_updated_at)return {error:new Error('record_conflict')};row.payload=structuredClone(args.p_payload);row.updated_at='v'+(audits.length+1);}audits.push(args);return {data:{saved:true}};}};
 return {admin,training,player,audits,call:(name,args)=>api.executeSessionTool(admin,c,name,{id:T,expected_updated_at:training.updated_at,expected_revision:training.payload.session?.revision||0,...args})};
}
test('MCP tools expose six field-session operations with UUID selectors, current revisions and confirmations',()=>{assert.equal(api.SESSION_TOOLS.length,6);assert.equal(new Set(api.SESSION_TOOLS.map(t=>t.name)).size,6);assert.equal(api.SESSION_TOOLS[0].inputSchema.properties.id.format,'uuid');assert.equal(api.SESSION_TOOLS[1].inputSchema.properties.entries.items.properties.player_ref.format,'uuid');for(const name of ['update_training_attendance','write_training_session_note','control_training_session','duplicate_training_plan']){const schema=api.SESSION_TOOLS.find(t=>t.name===name).inputSchema;assert.equal(schema.properties.confirmed.const,true);assert.ok(schema.required.includes('confirmed'));assert.ok(schema.required.includes('expected_updated_at'));assert.ok(schema.required.includes('expected_revision'));}});
test('MCP read does not start a session or write data',async()=>{const f=fixture(),r=await f.call('get_training_session',{});assert.equal(r.session.status,'not_started');assert.equal(f.audits.length,0);});
test('MCP checks scopes, team, stable UUID and exact identity before writing',async()=>{const f=fixture();await assert.rejects(api.executeSessionTool(f.admin,{...c,scopes:['read']},'update_training_attendance',{id:T}),/scope_write/);await assert.rejects(api.executeSessionTool(f.admin,{...c,team_id:'other'},'get_training_session',{id:T}),/not_found/);await assert.rejects(f.call('get_training_session',{external_key:'training-test'}),/exactly_one/);await assert.rejects(api.executeSessionTool(f.admin,c,'get_training_session',{id:'local-17'}),/invalid_training_uuid/);assert.equal(f.audits.length,0);});
test('MCP attendance resolves real team player names and rejects malformed or foreign UUIDs',async()=>{const f=fixture();await assert.rejects(f.call('update_training_attendance',{entries:[{player_ref:P,status:'present'}]}),/explicit_confirmation_required/);await assert.rejects(f.call('update_training_attendance',{confirmed:true,entries:[{player_ref:'p',status:'present'}]}),/invalid_attendance_entry/);await f.call('update_training_attendance',{confirmed:true,entries:[{player_ref:P,status:'present'}]});assert.equal(f.training.payload.session.attendance[0].name,'Atleta teste');assert.equal(f.training.payload.objetivo,'Original');await assert.rejects(f.call('update_training_attendance',{confirmed:true,entries:[{player_ref:P2,status:'present'}]}),/not_in_team/);assert.equal(f.audits.length,1);});
test('MCP control, notes and removal require explicit coach confirmations',async()=>{const f=fixture();await assert.rejects(f.call('control_training_session',{action:'start'}),/explicit_confirmation_required/);await f.call('control_training_session',{action:'start',confirmed:true});assert.equal(f.training.payload.session.controller_id,'mcp:connector');await assert.rejects(f.call('write_training_session_note',{block_key:BLOCK,note_id:'n',text:'Boa execução'}),/explicit_confirmation_required/);await f.call('write_training_session_note',{block_key:BLOCK,note_id:'n',text:'Boa execução',confirmed:true});assert.equal(f.training.payload.session.blocks[0].notes.length,1);await assert.rejects(f.call('remove_training_session_note',{block_key:BLOCK,note_id:'n',confirmed:false}),/Confirma/);await f.call('remove_training_session_note',{block_key:BLOCK,note_id:'n',confirmed:true});await f.call('control_training_session',{action:'pause',confirmed:true});await f.call('control_training_session',{action:'finish',confirmed:true});assert.equal(f.training.payload.session.status,'completed');});
test('MCP stale session/remote versions never overwrite newer data',async()=>{const f=fixture();await assert.rejects(f.call('control_training_session',{action:'start',confirmed:true,expected_updated_at:'stale'}),/conflict/);await f.call('control_training_session',{action:'start',confirmed:true});await assert.rejects(f.call('control_training_session',{action:'pause',confirmed:true,expected_revision:0}),/training_revision_conflict/);assert.equal(f.audits.length,1);});
test('MCP duplicate uses confirmation, current source revision, idempotency and drops actual-session data',async()=>{const f=fixture();await f.call('control_training_session',{action:'start',confirmed:true});await assert.rejects(f.call('duplicate_training_plan',{date:'2026-09-28',request_key:'no-confirm'}),/explicit_confirmation_required/);await assert.rejects(f.call('duplicate_training_plan',{date:'2026-09-28',request_key:'stale-version',confirmed:true,expected_updated_at:'old'}),/conflict/);await assert.rejects(f.call('duplicate_training_plan',{date:'2026-09-28',request_key:'stale-revision',confirmed:true,expected_revision:0}),/revision_conflict/);assert.equal(f.audits.length,1);await f.call('duplicate_training_plan',{date:'2026-09-28',request_key:'repeat-safe',confirmed:true});const args=f.audits[1];assert.equal(args.p_team_id,'team');assert.equal(args.p_payload.source_training_ref,T);assert.equal(args.p_payload.session,undefined);assert.equal(args.p_idempotency_key,'training-copy:connector-repeat-safe');});
