const test=require('node:test'),assert=require('node:assert/strict');
let api;test.before(async()=>{api=await import('../supabase/functions/vision-coach-mcp/training_continuity.mjs');});
const ID='b713b656-0c4d-4455-b945-c51791b28580',EX='7cc9d2a9-f492-4ffd-b67f-fd8c70128140';
const c={id:'connector',team_id:'team',scopes:['read','write']};
function fixture(){
 const source={id:ID,team_id:'team',kind:'training',deleted_at:null,updated_at:'v0',payload:{data:'2026-09-21',hora:'19:15',external_key:'continuity-test',objetivo:'Apoiar',blocos:[{exercise_ref:EX,phase:'principal',duration_min:10}],review:{status:'done',melhorou:'Passe',continua:'Apoio'}}};
 const exercise={id:EX,team_id:'team',kind:'exercise',deleted_at:null,updated_at:'e0',payload:{workspace_v2:true,status:'active',nome:'Apoio',objetivo:'Dar opção',duracao_total_min:10}};
 const rows=[source,exercise],calls=[];
 const admin={from(){const filters=[];return {select(){return this;},eq(key,value){filters.push(r=>(key==='payload->>external_key'?r.payload.external_key:r[key])===value);return this;},is(key,value){return this.eq(key,value);},then(resolve){return Promise.resolve({data:rows.filter(r=>filters.every(f=>f(r))).map(r=>structuredClone(r))}).then(resolve);}}},async rpc(name,args){assert.equal(name,'head_coach_commit_training_continuity');assert.equal(args.p_team_id,'team');assert.equal(args.p_expected_updated_at,source.updated_at);calls.push(args);const v=args.p_change;source.payload=structuredClone(v.source);source.updated_at='v'+calls.length;let m=rows.find(x=>x.id===v.memory_ref);if(!m){m={id:v.memory_ref,kind:'memory',team_id:'team',deleted_at:null};rows.push(m);}m.payload=structuredClone(v.memory);if(v.target){assert.equal(v.action,'approve');rows.push({id:v.target_ref,team_id:'team',kind:'training',payload:structuredClone(v.target),updated_at:'child',deleted_at:null});}return {data:{memory_linked:true}};}};
 const call=(name,args={})=>api.executeContinuityTool(admin,c,name,{id:ID,expected_updated_at:source.updated_at,expected_revision:source.payload.continuity?.revision||0,...args});return {rows,source,exercise,admin,call,calls};
}
async function prepare(f){await f.call('prepare_training_continuity');const p=f.source.payload.continuity.proposal;await f.call('update_training_continuity',{changes:{...p,date:'2026-09-24',time:'19:15',success_criterion:'Apoiar sem indicação'}});}
test('seven tools use stable UUID references; read is side-effect-free',async()=>{assert.equal(api.CONTINUITY_TOOLS.length,7);assert.equal(api.CONTINUITY_TOOLS[0].inputSchema.properties.id.format,'uuid');assert.equal(api.CONTINUITY_TOOLS[4].inputSchema.properties.changes.properties.blocks.items.properties.exercise_ref.format,'uuid');const f=fixture(),r=await f.call('get_training_continuity');assert.equal(r.continuity.proposal,null);assert.equal(r.evidence[1].quote,'Apoio');assert.equal(f.calls.length,0);await assert.rejects(api.executeContinuityTool(f.admin,c,'get_training_continuity',{id:'local-17'}),/invalid_training_uuid/);});
test('read/write scopes and exact team identity enforced before RPC',async()=>{const f=fixture();await assert.rejects(api.executeContinuityTool(f.admin,{...c,scopes:['read']},'save_training_review',{id:ID}),/scope_write/);await assert.rejects(api.executeContinuityTool(f.admin,{...c,team_id:'other'},'get_training_continuity',{id:ID}),/not_found/);await assert.rejects(f.call('get_training_continuity',{external_key:'continuity-test'}),/exactly_one/);assert.equal(f.calls.length,0);});
test('partial coach review retains existing content and commits source+memory once only after explicit confirmation',async()=>{const f=fixture();await assert.rejects(f.call('save_training_review',{review:{proxima_acao:'Passar e mexer'}}),/explicit_confirmation_required/);await f.call('save_training_review',{confirmed:true,review:{proxima_acao:'Passar e mexer'}});assert.equal(f.source.payload.review.melhorou,'Passe');assert.equal(f.calls.length,1);const q=f.calls[0].p_change;assert.equal(q.memory.metadata.managed_by,'training_review_v1');assert.equal(q.target,null);assert.equal(q.source.objetivo,'Apoiar');});
test('unchanged draft returns as-is without overwriting human adjustments',async()=>{const f=fixture();await prepare(f);const before=structuredClone(f.source.payload.continuity.proposal);const r=await f.call('prepare_training_continuity');assert.equal(r.already_prepared,true);assert.deepEqual(f.source.payload.continuity.proposal,before);assert.equal(f.calls.length,2);});
test('approval needs confirmation, uses one transaction and is replay-safe',async()=>{const f=fixture();await prepare(f);await assert.rejects(f.call('approve_training_continuity',{confirmed:false}),/aprovação explícita/);const approved=await f.call('approve_training_continuity',{confirmed:true});assert.ok(approved.followup);assert.equal(f.calls.length,3);const q=f.calls[2].p_change;assert.equal(q.target.source_training_ref,ID);assert.equal(q.target.session,undefined);assert.deepEqual(q.exercise_versions,[{id:EX,updated_at:'e0'}]);const again=await f.call('approve_training_continuity',{confirmed:true,expected_updated_at:'stale',expected_revision:0});assert.equal(again.already_approved,true);assert.equal(f.calls.length,3);});
test('deleted approved child is not recreated on retry',async()=>{const f=fixture();await prepare(f);const result=await f.call('approve_training_continuity',{confirmed:true});f.rows.find(r=>r.id===result.followup.id).deleted_at='deleted';await assert.rejects(f.call('approve_training_continuity',{confirmed:true}),/deleted/);assert.equal(f.calls.length,3);});
test('stale remote version, review and exercise changes refuse approval',async()=>{const f=fixture();await prepare(f);await assert.rejects(f.call('approve_training_continuity',{confirmed:true,expected_updated_at:'old'}),/conflict/);f.exercise.payload.objetivo='Outro objetivo';await assert.rejects(f.call('approve_training_continuity',{confirmed:true}),/ficha/);f.source.payload.review.continua='Novo';await assert.rejects(f.call('approve_training_continuity',{confirmed:true}),/mudou/);assert.equal(f.calls.length,2);});
test('dismissal and review removal preserve the plan and archive source memory',async()=>{const f=fixture();await prepare(f);await f.call('dismiss_training_continuity',{confirmed:true});assert.equal(f.source.payload.continuity.proposal.status,'dismissed');await f.call('clear_training_review',{confirmed:true});assert.equal(f.source.payload.review.status,'pending');assert.equal(f.calls.at(-1).p_change.memory.status,'archived');assert.equal(f.source.payload.blocos.length,1);});
