// Match visual operations: stable UUIDs, same model as the PWA, current revisions and team scopes.
import '../../../js/match_visual.js';
import '../../../js/match_events.js';
const M=globalThis.VisionMatchVisual;
const E=globalThis.VisionMatchEvents;
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const selector={id:{type:'string',format:'uuid'},external_key:{type:'string'}};
const choose={oneOf:[{required:['id'],not:{required:['external_key']}},{required:['external_key'],not:{required:['id']}}]};
const revision={expected_updated_at:{type:'string'},expected_revision:{type:'integer',minimum:0}};
function tool(name,description,properties,required,readOnly=false,destructive=false){return {name,description,inputSchema:{type:'object',properties:{...selector,...properties},required,additionalProperties:false,...choose},annotations:{readOnlyHint:readOnly,destructiveHint:destructive}};}
export const MATCH_VISUAL_TOOLS=[
 tool('get_match_visual','Read existing callup, visual 5v5 lineup, planned rotations, recorded movements and player minutes. Read-only; never infers minutes or starts a clock.',{},[],true),
 tool('save_match_visual_lineup','Set or clear the initial 5v5 lineup using called, available player UUIDs. Requires explicit coach confirmation. A started lineup is immutable; use a recorded movement instead.',{...revision,slots:{type:'object',properties:Object.fromEntries(Object.keys(M.roles).map(k=>[k,{type:'string'}])),additionalProperties:false},clear:{type:'boolean'},confirmed:{type:'boolean',const:true}},['expected_updated_at','expected_revision','confirmed']),
 tool('set_match_visual_position','Move a role in the tactical drawing using normalized coordinates. Does not swap players or alter participation. Requires explicit coach confirmation; reset restores the default layout.',{...revision,role:{type:'string',enum:Object.keys(M.roles)},x:{type:'number',minimum:.08,maximum:.92},y:{type:'number',minimum:.08,maximum:.92},reset:{type:'boolean'},confirmed:{type:'boolean',const:true}},['expected_updated_at','expected_revision','confirmed']),
 tool('edit_match_tactics','Add a cone or arrow to the shared tactical board, or delete/clear annotations. Coordinates are normalized 0–1. An explicit confirmation is required; annotations never change lineup, clock, or minutes.',{...revision,action:{type:'string',enum:['add_cone','add_arrow','delete','clear']},marking_id:{type:'string',format:'uuid'},x:{type:'number',minimum:.04,maximum:.96},y:{type:'number',minimum:.04,maximum:.96},x2:{type:'number',minimum:.04,maximum:.96},y2:{type:'number',minimum:.04,maximum:.96},note:{type:'string',maxLength:160},confirmed:{type:'boolean',const:true}},['expected_updated_at','expected_revision','action','confirmed'],false,true),
 tool('save_match_rotation','Create/edit a planned rotation only. It NEVER performs an actual substitution at its scheduled minute; a separate explicit movement is required. Reuse rotation_id when editing.',{...revision,rotation_id:{type:'string',minLength:1,maxLength:100},out_ref:{type:'string'},in_ref:{type:'string'},at_min:{type:'number',minimum:0,maximum:240},note:{type:'string',maxLength:1000}},['expected_updated_at','expected_revision','rotation_id','out_ref','in_ref','at_min']),
 tool('delete_match_rotation','Delete an explicitly confirmed unexecuted rotation; does not erase a performed substitution or match history.',{...revision,rotation_id:{type:'string'},confirmed:{type:'boolean',const:true}},['expected_updated_at','expected_revision','rotation_id','confirmed'],false,true),
 tool('control_match_usage','Start/pause/resume the first half or second half/finish only after explicit coach confirmation. Mark the second-half start while paused; this preserves elapsed match time and records the period boundary. One controller owns the clock; takeover is allowed only while paused with confirmation. reset_recording removes usage only, not the match, result or analysis. Never start a real match while testing development.',{...revision,action:{type:'string',enum:['start','pause','resume','second_half','finish','take_control','reset_recording']},confirmed:{type:'boolean',const:true}},['expected_updated_at','expected_revision','action','confirmed'],false,true),
 tool('record_match_movement','Record an explicitly confirmed substitution or role swap at the CURRENT clock time. undo_last corrects only the latest movement while paused; this is not a reverse substitution now.',{...revision,action:{type:'string',enum:['substitute','swap','undo_last']},movement_id:{type:'string',maxLength:100},out_ref:{type:'string'},in_ref:{type:'string'},role_a:{type:'string',enum:Object.keys(M.roles)},role_b:{type:'string',enum:Object.keys(M.roles)},rotation_id:{type:'string'},note:{type:'string',maxLength:1000},confirmed:{type:'boolean',const:true}},['expected_updated_at','expected_revision','action','confirmed'],false,true),
 tool('correct_match_movement','Edit or void any recorded movement while paused or after completion. The full timeline is replayed and invalid sequences are rejected atomically. Requires explicit coach confirmation and exact movement ID.',{...revision,movement_id:{type:'string',minLength:1,maxLength:100},action:{type:'string',enum:['edit','delete']},at_ms:{type:'integer',minimum:0},out_ref:{type:'string'},in_ref:{type:'string'},role_a:{type:'string',enum:Object.keys(M.roles)},role_b:{type:'string',enum:Object.keys(M.roles)},note:{type:'string',maxLength:1000},confirmed:{type:'boolean',const:true}},['expected_updated_at','expected_revision','movement_id','action','confirmed'],false,true)
];
async function find(admin,c,args){if(Boolean(args.id)===Boolean(args.external_key))throw new Error('exactly_one_match_identifier_required');if(args.id&&!UUID.test(args.id))throw new Error('invalid_match_uuid');let q=admin.from('workspace_records').select('*').eq('team_id',c.team_id).eq('kind','match').is('deleted_at',null);q=args.id?q.eq('id',args.id):q.eq('payload->>external_key',args.external_key);const {data,error}=await q;if(error)throw error;if(data?.length!==1)throw new Error(data?.length?'ambiguous_match_identity':'match_not_found');return data[0];}
async function players(admin,c){const {data,error}=await admin.from('workspace_records').select('id,payload').eq('team_id',c.team_id).eq('kind','player').is('deleted_at',null);if(error)throw error;return (data||[]).map(p=>({...p.payload,sync_id:p.id}));}
function output(row,roster){const usage=M.replay(row.payload),visual=M.state(row.payload),position_zones=Object.fromEntries(Object.entries(visual.layout).map(([role,point])=>{const zone=E.zoneFromPoint(point.x,point.y);return [role,{zone,label:E.zones[zone]}];}));usage.players=usage.players.map(player=>({...player,positions_played:M.positionsPlayed(row.payload,player.ref).map(role=>M.roles[role])}));return {id:row.id,updated_at:row.updated_at,external_key:row.payload.external_key||null,opponent:row.payload.adversario,lineup:row.payload.lineup||null,visual_match:visual,position_zones,usage,eligible_called:M.pool(row.payload,roster).filter(M.available).map(p=>({ref:p.sync_id,name:p.nome,number:p.numero??null}))};}
export async function executeMatchVisualTool(admin,c,name,args){
 if(!c.scopes?.includes('read'))throw new Error('connector_scope_read_required');const row=await find(admin,c,args),roster=await players(admin,c);
 if(name==='get_match_visual')return output(row,roster);
 if(!c.scopes?.includes('write'))throw new Error('connector_scope_write_required');
 if(['save_match_visual_lineup','set_match_visual_position','control_match_usage'].includes(name)&&args.confirmed!==true)throw new Error('explicit_confirmation_required');
 if(name==='edit_match_tactics'&&args.confirmed!==true)throw new Error('explicit_confirmation_required');
 if(!args.expected_updated_at||row.updated_at!==args.expected_updated_at)throw new Error('record_conflict_read_again');
 let cmd={expected_revision:args.expected_revision,confirmed:args.confirmed};
 if(name==='save_match_visual_lineup')cmd={...cmd,type:args.clear?'clear_lineup':'save_lineup',slots:args.slots};
 else if(name==='set_match_visual_position')cmd={...cmd,type:args.reset?'reset_layout':'position',role:args.role,x:args.x,y:args.y};
 else if(name==='edit_match_tactics'){
  if(!['add_cone','add_arrow','delete','clear'].includes(args.action))throw new Error('invalid_tactics_action');
  cmd=args.action==='add_cone'?{...cmd,type:'add_marking',id:args.marking_id,shape:'cone',x:args.x,y:args.y,note:args.note}:args.action==='add_arrow'?{...cmd,type:'add_marking',id:args.marking_id,shape:'arrow',x:args.x,y:args.y,x2:args.x2,y2:args.y2,note:args.note}:args.action==='delete'?{...cmd,type:'delete_marking',id:args.marking_id}:{...cmd,type:'clear_markings'};
 }
 else if(name==='save_match_rotation')cmd={...cmd,type:'save_rotation',id:args.rotation_id,out_ref:args.out_ref,in_ref:args.in_ref,at_min:args.at_min,note:args.note};
 else if(name==='delete_match_rotation')cmd={...cmd,type:'delete_rotation',id:args.rotation_id};
 else if(name==='control_match_usage'){if(!['start','pause','resume','second_half','finish','take_control','reset_recording'].includes(args.action))throw new Error('invalid_clock_action');cmd={...cmd,type:args.action};}
 else if(name==='record_match_movement'){if(!['substitute','swap','undo_last'].includes(args.action))throw new Error('invalid_movement_action');cmd={...cmd,type:args.action,id:args.movement_id,out_ref:args.out_ref,in_ref:args.in_ref,role_a:args.role_a,role_b:args.role_b,rotation_id:args.rotation_id,note:args.note};}
 else if(name==='correct_match_movement'){if(!['edit','delete'].includes(args.action))throw new Error('invalid_movement_correction');cmd=args.action==='delete'?{...cmd,type:'delete_movement',event_id:args.movement_id}:{...cmd,type:'correct_movement',event_id:args.movement_id,at_ms:args.at_ms,out_ref:args.out_ref,in_ref:args.in_ref,role_a:args.role_a,role_b:args.role_b,note:args.note};}
 else throw new Error('unknown_match_visual_tool');
 const payload=M.apply(row.payload,cmd,{controller_id:'mcp:'+c.id,actor:'Head Coach',players:roster});
 const {error}=await admin.rpc('head_coach_put_record',{p_team_id:c.team_id,p_kind:'match',p_payload:payload,p_record_id:row.id,p_expected_updated_at:row.updated_at,p_idempotency_key:'match-visual:'+c.id+':'+row.id+':'+row.updated_at+':'+cmd.type,p_agent_subject:'head-coach'});if(error)throw error;
 return output(await find(admin,c,{id:row.id}),roster);
}
