// Read exact match evidence and let the agent prepare a proposal distinct from coach decisions.
import '../../../js/match_visual.js';
import '../../../js/match_events.js';
import '../../../js/match_analysis.js';
import '../../../js/training_continuity.js';
const V=globalThis.VisionMatchVisual,E=globalThis.VisionMatchEvents,A=globalThis.VisionMatchAnalysis;
const C=globalThis.VisionTrainingContinuity;
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const selector={id:{type:'string',format:'uuid'},external_key:{type:'string'}};
const choose={oneOf:[{required:['id'],not:{required:['external_key']}},{required:['external_key'],not:{required:['id']}}]};
function tool(name,description,properties,required,readOnly=false){return {name,description,inputSchema:{type:'object',properties:{...selector,...properties},required,additionalProperties:false,...choose},annotations:{readOnlyHint:readOnly,destructiveHint:false}};}
const fields=Object.keys(A.fields);
export const MATCH_ANALYSIS_TOOLS=[
 tool('get_match_analysis','Read the registered match facts, events, usage and coach analysis without inferring missing facts.',{},[],true),
 {name:'get_recurring_match_patterns',description:'Read exact repeated loss patterns grouped by recorded reason and field zone across matches. Returns only counted events with stable source references; does not infer causes or recommendations.',inputSchema:{type:'object',properties:{limit:{type:'integer',minimum:2,maximum:100,default:50}},additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false}},
 {name:'get_cross_session_evidence',description:'Read exact match and training evidence for comparing recurring themes. Every item is labeled as registered fact, coach observation, interpretation, hypothesis or coach decision and includes its stable source UUID. Read-only; does not create memories or recommendations.',inputSchema:{type:'object',properties:{match_limit:{type:'integer',minimum:1,maximum:50,default:20},training_limit:{type:'integer',minimum:1,maximum:50,default:20}},additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false}},
 {name:'evaluate_cross_session_relation',description:'Ask Jev to judge whether one exact match source and one exact training source support the Head Coach’s proposed relation. Re-reads both current sources, returns the probability and citations, and never stores a fact or proposal. Requires TYPESAFE_API_KEY in the Edge Function environment.',inputSchema:{type:'object',properties:{claim:{type:'string',minLength:1,maxLength:1200},match_ref:{type:'string',format:'uuid'},match_field:{type:'string',minLength:1,maxLength:120},match_event_ref:{type:'string',maxLength:100},match_expected_updated_at:{type:'string',minLength:1,maxLength:80},training_ref:{type:'string',format:'uuid'},training_field:{type:'string',minLength:1,maxLength:120},training_event_ref:{type:'string',maxLength:100},training_expected_updated_at:{type:'string',minLength:1,maxLength:80}},required:['claim','match_ref','match_field','match_expected_updated_at','training_ref','training_field','training_expected_updated_at'],additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false}},
 tool('prepare_match_analysis','Save a clearly labeled agent proposal separately from coach observations and decisions. Requires explicit confirmation and current revisions.',{expected_updated_at:{type:'string'},expected_revision:{type:'integer',minimum:0},confirmed:{type:'boolean',const:true},proposal:{type:'object',properties:{summary:{type:'string',maxLength:3000},hypotheses:{type:'array',items:{type:'string',maxLength:1000},maxItems:10},next_priority:{type:'string',maxLength:2000},evidence_ids:{type:'array',items:{type:'string',maxLength:100},maxItems:30}},additionalProperties:false}},['expected_updated_at','expected_revision','confirmed','proposal'])
];
async function find(admin,c,args){if(Boolean(args.id)===Boolean(args.external_key))throw new Error('exactly_one_match_identifier_required');if(args.id&&!UUID.test(args.id))throw new Error('invalid_match_uuid');let q=admin.from('workspace_records').select('*').eq('team_id',c.team_id).eq('kind','match').is('deleted_at',null);q=args.id?q.eq('id',args.id):q.eq('payload->>external_key',args.external_key);const {data,error}=await q;if(error)throw error;if(data?.length!==1)throw new Error(data?.length?'ambiguous_match_identity':'match_not_found');return data[0];}
function result(row){const p=row.payload,ev=E.state(p).events,usage=V.replay(p);return {id:row.id,updated_at:row.updated_at,opponent:p.adversario||null,result:p.golos_favor==null||p.golos_contra==null?null:{for:p.golos_favor,against:p.golos_contra},events:ev,statistics:E.stats(p),usage:usage.players.map(x=>({ref:x.ref,name:x.name,elapsed_ms:x.elapsed_ms,keeper_ms:x.keeper_ms})),analysis:A.fromMatch(p),analysis_revision:A.fromMatch(p).revision};}
const ANALYSIS_KIND={summary:'coach_observation',positives:'coach_observation',problems:'coach_observation',losses:'coach_observation',recoveries:'coach_observation',offense:'coach_observation',defense:'coach_observation',transitions:'coach_observation',set_pieces:'coach_observation',player_use:'coach_observation',keep:'coach_observation',correct:'coach_observation',observations:'coach_observation',interpretation:'interpretation',hypotheses:'hypothesis',decisions:'coach_decision',next_priority:'coach_decision'};
function balancedEvidence(items,limit){const buckets={match:[],training:[]};for(const item of items){if(buckets[item.source_type])buckets[item.source_type].push(item);}const selected=[];while(selected.length<limit&&(buckets.match.length||buckets.training.length)){for(const type of ["match","training"]){if(buckets[type].length&&selected.length<limit)selected.push(buckets[type].shift());}}return selected;}
function matchEvidence(row){const p=row.payload||{},base={source_type:'match',source_ref:row.id,date:p.data||null,opponent:p.adversario||null,record_updated_at:row.updated_at||null},a=A.fromMatch(p),events=E.state(p).events,evidence=[];for(const [field,quote] of Object.entries(a.fields))if(quote)evidence.push({...base,evidence_type:ANALYSIS_KIND[field],field:'analysis.'+field,quote});const conceded=new Map(events.filter(event=>event.type==='goal_against').map(event=>[String(event.id),event]));for(const [id,quote] of Object.entries(a.goals_conceded))if(quote&&conceded.has(String(id)))evidence.push({...base,evidence_type:'hypothesis',field:'analysis.goals_conceded.'+id,event_ref:id,quote});for(const event of events)evidence.push({...base,evidence_type:'registered_fact',field:'match_event.'+event.type,event_ref:String(event.id),minute:Math.floor(event.at_ms/60000),player_ref:event.player_ref||null,zone:event.zone||null,reason:event.reason||null,side:event.side||null,quote:event.note||E.types[event.type]});return evidence;}
function trainingEvidence(row){const p={...row.payload,sync_id:row.id},evidence=C.evidence(p).map(item=>({...item,evidence_type:'coach_observation',record_updated_at:row.updated_at||null})),review=C.effectiveReview(p),outcome=review.focus_outcome;if(review.status==='done'&&outcome&&outcome!=='pending')evidence.push({source_type:'training',source_ref:row.id,date:p.data||null,record_updated_at:row.updated_at||null,evidence_type:'coach_evaluation',field:'review.focus_outcome',quote:outcome});return evidence;}
async function crossSessionEvidence(admin,c,args){if(!c.scopes?.includes('read'))throw new Error('connector_scope_read_required');const matchLimit=Math.max(1,Math.min(50,Number(args.match_limit)||20)),trainingLimit=Math.max(1,Math.min(50,Number(args.training_limit)||20));const query=kind=>admin.from('workspace_records').select('id,payload,updated_at').eq('team_id',c.team_id).eq('kind',kind).is('deleted_at',null).order('updated_at',{ascending:false}).limit(kind==='match'?matchLimit:trainingLimit);const [mr,tr]=await Promise.all([query('match'),query('training')]);if(mr.error)throw mr.error;if(tr.error)throw tr.error;const matches=mr.data||[],trainings=tr.data||[],evidence=matches.flatMap(matchEvidence).concat(trainings.flatMap(trainingEvidence)),eventItems=evidence.filter(x=>x.evidence_type==='registered_fact'),nonEvent=evidence.filter(x=>x.evidence_type!=='registered_fact'),eventLimit=150,evidenceLimit=25,visibleEvents=eventItems.slice(0,eventLimit),visibleNonEvents=balancedEvidence(nonEvent,evidenceLimit);return {schema:'cross-session-evidence@1',read_only:true,source_records:{matches:matches.length,trainings:trainings.length},evidence:visibleNonEvents.concat(visibleEvents).sort((a,b)=>String(a.date||'').localeCompare(String(b.date||''))||String(a.source_ref).localeCompare(String(b.source_ref))||String(a.field).localeCompare(String(b.field))),registered_event_count:eventItems.length,registered_events_truncated:eventItems.length>eventLimit,other_evidence_count:nonEvent.length,other_evidence_truncated:nonEvent.length>evidenceLimit,interpretation_guidance:'A recurring semantic theme is an interpretation, not a recorded fact. Cite source_ref and field for every proposed relation; keep hypotheses and coach decisions separate.'};}
async function findExactSource(admin,c,type,ref){if(!UUID.test(String(ref||'')))throw new Error('invalid_source_uuid');const kind=type==='match'?'match':'training',{data,error}=await admin.from('workspace_records').select('id,payload,updated_at').eq('team_id',c.team_id).eq('kind',kind).eq('id',ref).is('deleted_at',null);if(error)throw error;if(data?.length!==1)throw new Error(data?.length?'ambiguous_source_identity':'cross_session_source_not_found');return data[0];}
async function evaluateCrossSessionRelation(admin,c,args,{apiKey=globalThis.Deno?.env?.get?.('TYPESAFE_API_KEY'),fetchImpl=globalThis.fetch,sleepImpl=ms=>new Promise(resolve=>setTimeout(resolve,ms))}={}){
 if(!c.scopes?.includes('read'))throw new Error('connector_scope_read_required');
 if(!apiKey)throw new Error('typesafe_api_not_configured');
 if(typeof fetchImpl!=='function')throw new Error('typesafe_fetch_unavailable');
 const [matchRow,trainingRow]=await Promise.all([findExactSource(admin,c,'match',args.match_ref),findExactSource(admin,c,'training',args.training_ref)]);
 function exact(type,ref,field,eventRef,updatedAt){
  const row=type==='match'?matchRow:trainingRow;
  const sourceEvidence=(type==='match'?matchEvidence(row):trainingEvidence(row));
  const found=sourceEvidence.filter(item=>item.source_type===type&&item.source_ref===ref&&item.field===field&&(eventRef?item.event_ref===eventRef:!item.event_ref));
  if(found.length!==1)throw new Error(found.length?'cross_session_evidence_ambiguous':'cross_session_evidence_not_found');
  if(found[0].record_updated_at!==updatedAt)throw new Error('cross_session_evidence_source_changed');
  return found[0];
 }
 const match=exact('match',args.match_ref,args.match_field,args.match_event_ref,args.match_expected_updated_at);
 const training=exact('training',args.training_ref,args.training_field,args.training_event_ref,args.training_expected_updated_at);
 const state={claim:String(args.claim).trim(),match_evidence:{type:match.evidence_type,date:match.date,opponent:match.opponent,field:match.field,event_ref:match.event_ref||null,quote:match.quote,zone:match.zone||null,reason:match.reason||null},training_evidence:{type:training.evidence_type,date:training.date,field:training.field,quote:training.quote}};
 const body={model:'jev-latest',state,questions:{support:{type:'noul',instructions:{question:'Does the proposed relation have direct support in both the match and training evidence?',claim:state.claim,match_evidence:state.match_evidence,training_evidence:state.training_evidence,guardrails:'Judge only whether the same underlying football principle is addressed. Do not infer cause, learning, improvement, transfer, or effectiveness from shared wording or temporal order. Coach interpretations and hypotheses are claims, not registered facts; a coach evaluation is an explicit evaluation, not proof of causation.'},criteria:{true:'Both exact sources provide direct, compatible support for the proposed relation.',false:'The relation is absent, weak, ambiguous, contradicted, or supported by only one source.'}}}};
 let response;for(let attempt=0;attempt<3;attempt++){
  try{response=await fetchImpl('https://api.typesafe.ai/v1/systemone',{method:'POST',headers:{Authorization:'Bearer '+apiKey,'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(12000)});}catch(_){throw new Error('typesafe_request_failed');}
  if(response.ok||![429,529].includes(response.status)||attempt===2)break;
  const retryAfter=response.headers?.get?.('retry-after'),retryAfterMs=retryAfter&&Number.isFinite(Number(retryAfter))?Number(retryAfter)*1000:retryAfter?Date.parse(retryAfter)-Date.now():NaN,delay=Number.isFinite(retryAfterMs)?Math.max(0,Math.min(5000,retryAfterMs)):250*2**attempt;
  await sleepImpl(delay);
 }
 if(!response.ok)throw new Error('typesafe_request_failed_'+response.status);
 let result;try{result=await response.json();}catch(_){throw new Error('typesafe_response_invalid');}
 const answer=result?.answers?.support?.noul;
 if(result?.answers?.support?.type!=='noul'||typeof answer!=='number'||!Number.isFinite(answer)||answer<0||answer>1)throw new Error('typesafe_response_invalid');
 return{schema:'cross-session-relation-judgment@1',judgment:'semantic_support_probability',probability:answer,model:result.model||null,claim:state.claim,evidence:[{source_type:'match',source_ref:match.source_ref,record_updated_at:match.record_updated_at,field:match.field,event_ref:match.event_ref||null,evidence_type:match.evidence_type,quote:match.quote},{source_type:'training',source_ref:training.source_ref,record_updated_at:training.record_updated_at,field:training.field,event_ref:training.event_ref||null,evidence_type:training.evidence_type,quote:training.quote}],coach_review_required:true,writes_performed:false,interpretation:'Probabilidade de apoio semântico do Jev; não é facto desportivo, causa, transferência de aprendizagem nem decisão do treinador.'};
}
function aggregateRecurringPatterns(rows){const groups=new Map();for(const row of rows){const p=row.payload||{},events=E.state(p).events,seen=new Set();for(const event of events){if(event.type!=='loss'||!event.reason||!event.zone)continue;const key=event.reason+'|'+event.zone,eventKey=String(event.id);if(seen.has(eventKey))continue;seen.add(eventKey);let g=groups.get(key);if(!g){g={reason:event.reason,reason_label:E.lossReasons[event.reason],zone:event.zone,zone_label:E.zones[event.zone],event_count:0,matches:new Map()};groups.set(key,g);}g.event_count++;let match=g.matches.get(row.id);if(!match){match={match_ref:row.id,external_key:p.external_key||null,date:p.data||null,opponent:p.adversario||null,event_ids:[]};g.matches.set(row.id,match);}match.event_ids.push(eventKey);}}
 return [...groups.values()].map(g=>({...g,matches:[...g.matches.values()]})).filter(g=>g.matches.length>=2&&g.event_count>=2).sort((a,b)=>b.matches.length-a.matches.length||b.event_count-a.event_count||a.reason.localeCompare(b.reason)||a.zone.localeCompare(b.zone)).map(({matches,...g})=>({...g,matches}));}
export async function executeMatchAnalysisTool(admin,c,name,args){if(!c.scopes?.includes('read'))throw new Error('connector_scope_read_required');if(name==='get_cross_session_evidence')return crossSessionEvidence(admin,c,args);if(name==='evaluate_cross_session_relation')return evaluateCrossSessionRelation(admin,c,args);if(name==='get_recurring_match_patterns'){const limit=Math.max(2,Math.min(100,Number(args.limit)||50)),{data,error}=await admin.from('workspace_records').select('id,payload,updated_at').eq('team_id',c.team_id).eq('kind','match').is('deleted_at',null).order('updated_at',{ascending:false}).limit(limit);if(error)throw error;return {origin:'Contagem exata de perdas registadas; apenas motivo e zona explícitos.',matches_examined:(data||[]).length,minimum_distinct_matches:2,patterns:aggregateRecurringPatterns(data||[])};}const row=await find(admin,c,args);if(name==='get_match_analysis')return result(row);if(name!=='prepare_match_analysis')throw new Error('unknown_match_analysis_tool');if(!c.scopes?.includes('write'))throw new Error('connector_scope_write_required');if(args.confirmed!==true)throw new Error('explicit_confirmation_required');if(!args.expected_updated_at||row.updated_at!==args.expected_updated_at)throw new Error('record_conflict_read_again');const old=A.fromMatch(row.payload);if(args.expected_revision!==old.revision)throw new Error('analysis_revision_conflict_read_again');const events=E.state(row.payload).events,ids=new Set(events.map(x=>String(x.id))),refs=args.proposal?.evidence_ids||[];if(refs.some(x=>!ids.has(String(x))))throw new Error('evidence_event_not_found');const proposal={status:'proposed',prepared_by:'Head Coach',prepared_at:new Date().toISOString(),source_analysis_revision:old.revision,source_events_revision:E.state(row.payload).revision,summary:String(args.proposal?.summary||'').slice(0,3000),hypotheses:(args.proposal?.hypotheses||[]).map(x=>String(x).slice(0,1000)),next_priority:String(args.proposal?.next_priority||'').slice(0,2000),evidence_ids:refs.map(String)};const payload={...row.payload,post_game:{...(row.payload.post_game||{}),analysis:{...old,agent_proposal:proposal}}};const {error}=await admin.rpc('head_coach_put_record',{p_team_id:c.team_id,p_kind:'match',p_payload:payload,p_record_id:row.id,p_expected_updated_at:row.updated_at,p_idempotency_key:'match-analysis:'+c.id+':'+row.id+':'+row.updated_at+':proposal',p_agent_subject:'head-coach'});if(error)throw error;return result(await find(admin,c,{id:row.id}));}
