// Coach-owned longitudinal athlete objectives, with stable references and no public rankings.
import '../../../js/player_goals.js';
import '../../../js/player_archive.js';
import '../../../js/match_visual.js';
const G=globalThis.PlayerGoals,P=globalThis.PlayerArchive,M=globalThis.VisionMatchVisual,UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,selector={id:{type:'string',format:'uuid'},external_key:{type:'string'}},choose={oneOf:[{required:['id'],not:{required:['external_key']}},{required:['external_key'],not:{required:['id']}}]};
export const PLAYER_GOAL_TOOLS=[
 {name:'get_player_development_goals',description:'Read development goals and their evidence for one team athlete.',inputSchema:{type:'object',properties:selector,required:[],additionalProperties:false,...choose},annotations:{readOnlyHint:true,destructiveHint:false}},
 {name:'get_player_participation_history',description:'Read one athlete’s training attendance, match call-ups, recorded starts, entries/exits, minutes and positions. Unknown minutes remain null; this tool never ranks athletes.',inputSchema:{type:'object',properties:selector,required:[],additionalProperties:false,...choose},annotations:{readOnlyHint:true,destructiveHint:false}},
 {name:'manage_player_development_goal',description:'Add, update or explicitly delete a coach-defined development goal. Progress status is always entered by the coach, never inferred.',inputSchema:{type:'object',properties:{...selector,action:{type:'string',enum:['save','delete']},goal_id:{type:'string',format:'uuid'},expected_updated_at:{type:'string'},expected_revision:{type:'integer',minimum:0},confirmed:{type:'boolean',const:true},title:{type:'string',maxLength:200},started_at:{type:'string',format:'date'},status:{type:'string',enum:Object.keys(G.states)},evidence_refs:{type:'array',items:{type:'object',properties:{type:{type:'string',enum:['match','training','observation']},id:{type:'string',format:'uuid'}},required:['type','id'],additionalProperties:false},maxItems:30},exercise_refs:{type:'array',items:{type:'string',format:'uuid'},maxItems:30},notes:{type:'string',maxLength:3000}},required:['action','goal_id','expected_updated_at','expected_revision','confirmed'],additionalProperties:false,...choose},annotations:{readOnlyHint:false,destructiveHint:true}},
 {name:'get_archived_player_development',description:'Read retained development goals for one permanently removed athlete by exact shared UUID. Returns historical_only=true and stable evidence/exercise references; it does not report current roster status or infer improvement.',inputSchema:{type:'object',properties:{player_ref:{type:'string',format:'uuid'}},required:['player_ref'],additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false}}
];
async function find(admin,c,args){if(Boolean(args.id)===Boolean(args.external_key))throw new Error('exactly_one_player_identifier_required');if(args.id&&!UUID.test(args.id))throw new Error('invalid_player_uuid');let q=admin.from('workspace_records').select('*').eq('team_id',c.team_id).eq('kind','player').is('deleted_at',null);q=args.id?q.eq('id',args.id):q.eq('payload->>external_key',args.external_key);const{data,error}=await q;if(error)throw error;if(data?.length!==1)throw new Error(data?.length?'ambiguous_player_identity':'player_not_found');return data[0];}
const safeGoal=goal=>{const value=goal&&typeof goal==='object'?goal:{},refs=Array.isArray(value.evidence_refs)?value.evidence_refs:[],history=Array.isArray(value.history)?value.history:[];return{id:UUID.test(String(value.id||''))?String(value.id):null,title:String(value.title||'').slice(0,200),started_at:String(value.started_at||'').slice(0,10)||null,status:Object.hasOwn(G.states,String(value.status||''))?value.status:null,notes:String(value.notes||'').slice(0,3000),updated_at:value.updated_at||null,evidence_refs:refs.filter(ref=>['match','training','observation'].includes(ref?.type)&&UUID.test(String(ref?.id||''))).map(ref=>({type:ref.type,id:ref.id})),exercise_refs:(Array.isArray(value.exercise_refs)?value.exercise_refs:[]).filter(ref=>UUID.test(String(ref||''))),history:history.map(item=>{const prior=safeGoal({...item,history:[]});return prior;})};};
async function getArchivedPlayerDevelopment(admin,c,playerRef){
 const externalKey='player-archive:default:'+playerRef;
 const{data,error}=await admin.from('workspace_records').select('id,payload,updated_at').eq('team_id',c.team_id).eq('kind','document').eq('payload->>type','player_archive').eq('payload->>external_key',externalKey).is('deleted_at',null);
 if(error)throw error;if(data?.length!==1)throw new Error(data?.length?'ambiguous_player_archive':'player_archive_not_found');
 let archive;try{archive=P.state({type:'player_archive',body:data[0].payload?.body});}catch{throw new Error('player_archive_invalid');}
 if(archive.player?.ref!==playerRef)throw new Error('player_archive_identity_mismatch');
 return{historical_only:true,archive_status:'archived',archive_ref:data[0].id,archive_updated_at:data[0].updated_at||null,archived_at:archive.archived_at||null,revision:Number.isInteger(archive.development_goals.revision)?archive.development_goals.revision:null,player:{ref:archive.player.ref,name:String(archive.player.name||'Atleta').slice(0,160),age_group:String(archive.player.age_group||'').slice(0,80)||null},goals:archive.development_goals.items.map(safeGoal)};
}
async function exists(admin,c,kind,id){if(!UUID.test(String(id||'')))return false;const{data,error}=await admin.from('workspace_records').select('id').eq('team_id',c.team_id).eq('kind',kind).eq('id',id).is('deleted_at',null);if(error)throw error;return!!data?.length;}
async function participationHistory(admin,c,player){const id=player.id;const query=kind=>admin.from('workspace_records').select('id,payload,updated_at').eq('team_id',c.team_id).eq('kind',kind).is('deleted_at',null);const [mr,tr]=await Promise.all([query('match'),query('training')]);if(mr.error)throw mr.error;if(tr.error)throw tr.error;const matches=[];for(const row of mr.data||[]){const p=row.payload||{},s=M.state(p),called=(p.callup?.player_ids||[]).some(ref=>String(ref)===id),rostered=s.roster.some(x=>String(x.ref)===id),initial=s.initial_slots||M.initialSlots(p),started=!!s.started_at,starter=started&&Object.values(initial).some(ref=>String(ref)===id),events=s.events.filter(ev=>!ev.voided_at),entries=events.filter(ev=>ev.type==='substitute'&&String(ev.in_ref)===id),exits=events.filter(ev=>ev.type==='substitute'&&String(ev.out_ref)===id);if(!called&&!rostered&&!starter&&!entries.length&&!exits.length)continue;const participated=started&&(rostered||starter||entries.length>0||exits.length>0),usage=participated?M.replay(p).players.find(x=>String(x.ref)===id):null;matches.push({match_ref:row.id,updated_at:row.updated_at||null,date:p.data||null,opponent:p.adversario||null,called_up:called,started_as_starter:!!starter,entries:entries.map(ev=>Math.floor(ev.at_ms/60000)),exits:exits.map(ev=>Math.floor(ev.at_ms/60000)),minutes_ms:usage?usage.elapsed_ms:null,minutes_known:!!usage,positions_played:participated?M.positionsPlayed(p,id).map(role=>M.roles[role]):[]});}matches.sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))||String(a.match_ref).localeCompare(String(b.match_ref)));const trainings=[];for(const row of tr.data||[]){const p=row.payload||{},attendance=p.session?.attendance||[],entry=attendance.find(x=>String(x.player_ref)===id&&x.status!=='unknown');if(!entry)continue;trainings.push({training_ref:row.id,updated_at:row.updated_at||null,date:p.data||null,objective:p.objetivo||null,attendance:entry.status});}trainings.sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))||String(a.training_ref).localeCompare(String(b.training_ref)));const known=matches.filter(x=>x.minutes_known);return{schema:'player-participation-history@1',player_ref:id,player_updated_at:player.updated_at||null,summary:{training_records:trainings.length,call_ups:matches.filter(x=>x.called_up).length,recorded_starts:matches.filter(x=>x.started_as_starter).length,entries:matches.reduce((n,x)=>n+x.entries.length,0),exits:matches.reduce((n,x)=>n+x.exits.length,0),matches_with_recorded_minutes:known.length,matches_without_recorded_minutes:matches.length-known.length,total_minutes_ms:known.length?known.reduce((n,x)=>n+x.minutes_ms,0):null},training_records:trainings,match_records:matches,provenance:'Attendance comes from explicit training attendance; starts and substitutions come from the saved match roster and movement log; minutes and positions come from the recorded match clock. Null minutes mean no clock record, not zero.'};}
export async function executePlayerGoalTool(admin,c,name,args){if(!c.scopes?.includes('read'))throw new Error('connector_scope_read_required');if(!['get_player_development_goals','get_player_participation_history','manage_player_development_goal','get_archived_player_development'].includes(name))throw new Error('unknown_player_goal_tool');if(name==='get_archived_player_development'){if(!UUID.test(String(args?.player_ref||'')))throw new Error('invalid_player_uuid');return getArchivedPlayerDevelopment(admin,c,String(args.player_ref));}if(name==='manage_player_development_goal'&&!['save','delete'].includes(args.action))throw new Error('invalid_goal_action');const row=await find(admin,c,args),state=G.state(row.payload);if(name==='get_player_development_goals')return{id:row.id,updated_at:row.updated_at,revision:state.revision,goals:state.items};if(name==='get_player_participation_history')return participationHistory(admin,c,row);if(!c.scopes?.includes('write'))throw new Error('connector_scope_write_required');if(!UUID.test(String(args.goal_id||'')))throw new Error('invalid_goal_uuid');if(args.confirmed!==true)throw new Error('explicit_confirmation_required');if(!args.expected_updated_at||args.expected_updated_at!==row.updated_at)throw new Error('record_conflict_read_again');if(args.expected_revision!==state.revision)throw new Error('goal_revision_conflict_read_again');let command;if(args.action==='delete')command={type:'delete',id:args.goal_id,confirmed:true,expected_revision:state.revision};else{if(!args.title||!args.started_at||!args.status)throw new Error('goal_fields_required');for(const ref of args.evidence_refs||[])if(!await exists(admin,c,ref.type==='observation'?'memory':ref.type,ref.id))throw new Error('goal_evidence_not_found');for(const exercise of args.exercise_refs||[])if(!await exists(admin,c,'exercise',exercise))throw new Error('goal_exercise_not_found');command={type:'save',expected_revision:state.revision,goal:{id:args.goal_id,title:args.title,started_at:args.started_at,status:args.status,evidence_refs:args.evidence_refs||[],exercise_refs:args.exercise_refs||[],notes:args.notes||''}};}const payload=G.apply(row.payload,command,{now:Date.now()});const{error}=await admin.rpc('head_coach_put_record',{p_team_id:c.team_id,p_kind:'player',p_payload:payload,p_record_id:row.id,p_expected_updated_at:row.updated_at,p_idempotency_key:'player-goal:'+c.id+':'+row.id+':'+row.updated_at+':'+args.action+':'+args.goal_id,p_agent_subject:'head-coach'});if(error)throw error;const saved=await find(admin,c,{id:row.id}),next=G.state(saved.payload);return{id:row.id,updated_at:saved.updated_at,revision:next.revision,goals:next.items};}
