import '../../../js/seasons.js';
const S=globalThis.VisionSeasons;
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export const SEASON_TOOLS=[
 {name:'get_team_seasons',description:'Read archived team seasons, stable roster references, and active period.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false}},
 {name:'save_team_season',description:'Create or update an archived season and roster. Requires coach confirmation and current document revision.',inputSchema:{type:'object',properties:{season_id:{type:['string','null'],format:'uuid'},name:{type:'string',minLength:1,maxLength:60},start_date:{type:'string',format:'date'},end_date:{type:'string',format:'date'},roster:{type:'array',maxItems:100,items:{type:'object',properties:{ref:{type:'string',format:'uuid'},name:{type:'string',maxLength:120},number:{type:['integer','null']}},required:['ref','name'],additionalProperties:false}},activate:{type:'boolean'},expected_updated_at:{type:'string'},expected_revision:{type:'integer',minimum:0},confirmed:{type:'boolean',const:true}},required:['name','start_date','end_date','roster','expected_revision','confirmed'],additionalProperties:false},annotations:{readOnlyHint:false,destructiveHint:false}}
];
const KEY='season-index:';
async function record(admin,c){const{data,error}=await admin.from('workspace_records').select('*').eq('team_id',c.team_id).eq('kind','document').eq('payload->>external_key',KEY+c.team_id).is('deleted_at',null);if(error)throw error;if(data?.length>1)throw new Error('ambiguous_season_index');return data?.[0]||null;}
export async function executeSeasonTool(admin,c,name,args){if(!c.scopes?.includes('read'))throw new Error('connector_scope_read_required');if(name!=='get_team_seasons'&&name!=='save_team_season')throw new Error('unknown_season_tool');if(name==='save_team_season'){if(args.season_id!=null&&!UUID.test(String(args.season_id)))throw new Error('invalid_season_uuid');if(!Array.isArray(args.roster))throw new Error('season_roster_required');if(args.roster.length>100)throw new Error('season_roster_limit_exceeded');for(const p of args.roster){if(!p||!UUID.test(String(p.ref||'')))throw new Error('invalid_player_uuid');if(!String(p.name||'').trim()||(p.number!=null&&!Number.isInteger(p.number)))throw new Error('invalid_season_roster_entry');}}const row=await record(admin,c);if(name==='get_team_seasons')return row?{id:row.id,external_key:row.payload.external_key,updated_at:row.updated_at,record:S.state({body:row.payload.body})}:{record:S.state(null),updated_at:null};if(!c.scopes?.includes('write'))throw new Error('connector_scope_write_required');if(args.confirmed!==true)throw new Error('explicit_confirmation_required');if(row&&(!args.expected_updated_at||row.updated_at!==args.expected_updated_at))throw new Error('record_conflict_read_again');if(!row&&args.expected_updated_at)throw new Error('record_not_found_read_again');const old=S.state(row?{body:row.payload.body}:null);if(old.revision!==args.expected_revision)throw new Error('domain_revision_conflict_read_again');const value=S.save(row?{body:row.payload.body}:null,{id:args.season_id||null,name:args.name,start_date:args.start_date,end_date:args.end_date,roster:args.roster,activate:args.activate===true},{expected_revision:args.expected_revision});for(const p of args.roster){const{data,error}=await admin.from('workspace_records').select('id,payload').eq('team_id',c.team_id).eq('kind','player').eq('id',p.ref).is('deleted_at',null);if(error)throw error;if(!data?.length)throw new Error('player_reference_not_found_in_team');}
 const key=KEY+c.team_id,payload={...(row?.payload||{}),team_id:c.team_id,type:'season_index',title:'Arquivo de épocas',target_date:value.items.find(x=>x.id===value.active_id)?.start_date||null,status:'ready',external_key:key,sync_id:row?.payload?.sync_id||await S.stableIndexId(c.team_id),body:JSON.stringify(value),created_by:row?.payload?.created_by||'agent',created_by_label:row?.payload?.created_by_label||'Head Coach',updated_by:'agent',updated_by_label:'Head Coach'};const{data,error}=await admin.rpc('head_coach_put_record',{p_team_id:c.team_id,p_kind:'document',p_payload:payload,p_record_id:row?.id||null,p_expected_updated_at:row?.updated_at||null,p_idempotency_key:'season-index:'+c.id+':'+args.expected_revision+':'+value.revision,p_agent_subject:'head-coach'});if(error)throw error;return{id:data.id,external_key:key,updated_at:data.updated_at,record:S.state({body:data.payload.body})};}
