// Semantic access to weekly plans and team development objectives.
import '../../../js/team_development.js';
import '../../../js/match_analysis.js';
import '../../../js/match_events.js';
import '../../../js/training_continuity.js';
const D=globalThis.TeamDevelopment;
const A=globalThis.VisionMatchAnalysis,E=globalThis.VisionMatchEvents,C=globalThis.VisionTrainingContinuity;
const identifier={id:{type:'string',format:'uuid'},external_key:{type:'string',maxLength:120}};
const choose={oneOf:[{required:['id'],not:{required:['external_key']}},{required:['external_key'],not:{required:['id']}}]};
function tool(name,description,properties,required,readOnly=false){return{name,description,inputSchema:{type:'object',properties:{...identifier,...properties},required,additionalProperties:false,...choose},annotations:{readOnlyHint:readOnly,destructiveHint:false}};}
const refs={type:'array',maxItems:10,items:{type:'object',properties:{type:{type:'string',enum:['training','match']},id:{type:'string',format:'uuid'}},required:['type','id'],additionalProperties:false}};
export const TEAM_DEVELOPMENT_TOOLS=[
 {name:'get_team_development',description:'Read weekly plans or the explicit team development stage and supporting sessions.',inputSchema:{type:'object',properties:identifier,additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false}},
 {name:'prepare_cross_session_priority',description:'Save a reviewable Head Coach proposal for a team priority, grounded in current exact match/training evidence. Keeps interpretation and hypothesis separate, leaves coach_decision empty, and does not approve or create a training.',inputSchema:{type:'object',properties:{title:{type:'string',minLength:1,maxLength:200},rationale:{type:'string',minLength:1,maxLength:3000},hypothesis:{type:'string',maxLength:3000},evidence:{type:'array',minItems:1,maxItems:12,items:{type:'object',properties:{source_type:{type:'string',enum:['match','training']},source_ref:{type:'string',format:'uuid'},field:{type:'string',maxLength:100},event_ref:{type:'string',maxLength:100},quote:{type:'string',minLength:1,maxLength:5000},record_updated_at:{type:'string'}},required:['source_type','source_ref','field','quote','record_updated_at'],additionalProperties:false}},confirmed:{type:'boolean',const:true}},required:['title','rationale','evidence','confirmed'],additionalProperties:false},annotations:{readOnlyHint:false,destructiveHint:false}},
 tool('accept_team_priority_proposal','Accept a reviewed team priority proposal only after the coach explicitly supplies the decision. Does not create a training.',{expected_updated_at:{type:'string'},expected_revision:{type:'integer',minimum:0},coach_decision:{type:'string',minLength:1,maxLength:3000},confirmed:{type:'boolean',const:true}},['expected_updated_at','expected_revision','coach_decision','confirmed']),
 tool('dismiss_team_priority_proposal','Dismiss a team priority proposal only with explicit coach confirmation; preserves its history and evidence.',{expected_updated_at:{type:'string'},expected_revision:{type:'integer',minimum:0},confirmed:{type:'boolean',const:true}},['expected_updated_at','expected_revision','confirmed']),
 tool('save_weekly_plan','Create or update a weekly plan. This prepares a proposal only; the coach controls and approves training plans.',{week_start:{type:'string',format:'date'},objective:{type:'string',maxLength:1000},training1:{type:['string','null'],format:'uuid'},training2:{type:['string','null'],format:'uuid'},match:{type:['string','null'],format:'uuid'},relation_note:{type:'string',maxLength:500},evaluation:{type:'string',maxLength:3000},expected_updated_at:{type:'string'},expected_revision:{type:'integer',minimum:0},confirmed:{type:'boolean',const:true}},['week_start','objective','expected_revision','confirmed']),
 tool('save_team_development_goal','Create or update a team objective using coach-provided evidence and explicit stage; never infer improvement.',{title:{type:'string',maxLength:200},identified_at:{type:'string',format:'date'},stage:{type:'string',enum:D.stages},sessions:refs,evidence:refs,observations:{type:'string',maxLength:3000},interpretation:{type:'string',maxLength:3000},hypothesis:{type:'string',maxLength:3000},evaluation:{type:'string',maxLength:3000},coach_decision:{type:'string',maxLength:3000},expected_updated_at:{type:'string'},expected_revision:{type:'integer',minimum:0},confirmed:{type:'boolean',const:true}},['title','stage','expected_revision','confirmed'])
];
async function find(admin,c,args){if(Boolean(args.id)===Boolean(args.external_key))throw new Error('exactly_one_document_identifier_required');let q=admin.from('workspace_records').select('*').eq('team_id',c.team_id).eq('kind','document').is('deleted_at',null);q=args.id?q.eq('id',args.id):q.eq('payload->>external_key',args.external_key);const{data,error}=await q;if(error)throw error;if(data?.length>1)throw new Error('ambiguous_document_identity');return data?.[0]||null;}
function output(row){return{id:row.id,external_key:row.payload.external_key||null,updated_at:row.updated_at,type:row.payload.type,title:row.payload.title,record:row.payload.type==='weekly_plan'?D.week({body:row.payload.body}):D.teamGoal({body:row.payload.body})};}
async function checkRefs(admin,c,list){for(const ref of list||[]){if(!/^[0-9a-f-]{36}$/i.test(ref.id))throw new Error('invalid_stable_reference');const kind=ref.type==='training'?'training':'match';const{data,error}=await admin.from('workspace_records').select('id').eq('team_id',c.team_id).eq('kind',kind).eq('id',ref.id).is('deleted_at',null);if(error)throw error;if(!data?.length)throw new Error('session_reference_not_found_in_team');}}
async function sourceEvidence(admin,c,item){if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(item.source_ref||''))throw new Error('invalid_evidence_source_uuid');const{data,error}=await admin.from('workspace_records').select('*').eq('team_id',c.team_id).eq('kind',item.source_type).eq('id',item.source_ref).is('deleted_at',null);if(error)throw error;if(data?.length!==1)throw new Error('evidence_source_not_found_in_team');const row=data[0];if(row.updated_at!==item.record_updated_at)throw new Error('evidence_source_changed_read_again');let quote='';if(item.source_type==='match'&&item.field.startsWith('analysis.')){const field=item.field.slice('analysis.'.length),key=field.startsWith('goals_conceded.')?field.slice('goals_conceded.'.length):field;if(field.startsWith('goals_conceded.'))quote=A.fromMatch(row.payload).goals_conceded[key]||'';else quote=A.fromMatch(row.payload).fields[key]||'';}else if(item.source_type==='match'&&item.field.startsWith('match_event.')){const ev=E.state(row.payload).events.find(x=>String(x.id)===String(item.event_ref));if(ev&&item.field==='match_event.'+ev.type)quote=ev.note||E.types[ev.type];}else if(item.source_type==='training'){const tr=C.evidence({...row.payload,sync_id:row.id}).find(x=>x.field===item.field);quote=tr?.quote||'';}if(!quote||quote!==item.quote)throw new Error('evidence_quote_mismatch_read_again');return{type:item.source_type,id:row.id,field:item.field,event_ref:item.event_ref||null,quote:item.quote,record_updated_at:row.updated_at};}
async function prepareCrossSessionPriority(admin,c,args){if(args.confirmed!==true)throw new Error('explicit_confirmation_required');const verified=[];for(const item of args.evidence)verified.push(await sourceEvidence(admin,c,item));const unique=[...new Map(verified.map(x=>[x.type+':'+x.id+':'+x.field+':'+(x.event_ref||''),x])).values()];if(unique.length!==verified.length)throw new Error('duplicate_evidence_reference');const evidenceHash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify([String(args.title).trim(),unique.map(x=>[x.type,x.id,x.field,x.event_ref,x.quote,x.record_updated_at]).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)))]))),hash=[...new Uint8Array(evidenceHash)].map(x=>x.toString(16).padStart(2,'0')).join(''),key='cross-priority-v1:'+hash.slice(0,40);const existing=await find(admin,c,{external_key:key});if(existing)return{...output(existing),already_prepared:true};const sessions=[...new Map(unique.map(x=>[x.type+':'+x.id,{type:x.type,id:x.id}])).values()],evidenceRefs=unique.map(x=>({type:x.type,id:x.id,field:x.field,event_ref:x.event_ref,quote:x.quote,record_updated_at:x.record_updated_at})),value=D.saveGoal(null,{title:String(args.title).trim(),identified_at:new Date().toISOString().slice(0,10),stage:'identified',evidence:sessions,sessions,exercises:[],observations:'',interpretation:String(args.rationale).trim(),hypothesis:String(args.hypothesis||'').trim(),coach_decision:'',agent_proposal:{status:'proposed',rationale:String(args.rationale).trim(),prepared_by:'Head Coach',prepared_at:new Date().toISOString(),evidence_refs:evidenceRefs}},{expected_revision:0}),payload={team_id:c.team_id,type:'team_goal',title:value.title,target_date:value.identified_at,status:'ready',external_key:key,refs:sessions,body:JSON.stringify(value),created_by:'agent',created_by_label:'Head Coach',updated_by:'agent',updated_by_label:'Head Coach'},rpc=await admin.rpc('head_coach_put_record',{p_team_id:c.team_id,p_kind:'document',p_payload:payload,p_record_id:null,p_expected_updated_at:null,p_idempotency_key:'cross-priority:'+key,p_agent_subject:'head-coach'});if(rpc.error)throw rpc.error;return{...output(rpc.data),already_prepared:false};}
async function decidePriorityProposal(admin,c,name,args){if(args.confirmed!==true)throw new Error('explicit_confirmation_required');if(name==='accept_team_priority_proposal'&&!String(args.coach_decision||'').trim())throw new Error('coach_decision_required');const row=await find(admin,c,args);if(!row||row.payload.type!=='team_goal')throw new Error('team_priority_proposal_not_found');if(!args.expected_updated_at||row.updated_at!==args.expected_updated_at)throw new Error('record_conflict_read_again');const old=D.teamGoal({body:row.payload.body});if(old.revision!==args.expected_revision)throw new Error('domain_revision_conflict_read_again');if(old.agent_proposal?.status!=='proposed')throw new Error('proposal_not_pending');const status=name==='accept_team_priority_proposal'?'accepted':'dismissed';if(status==='accepted')for(const ref of old.agent_proposal.evidence_refs||[])await sourceEvidence(admin,c,{source_type:ref.type,source_ref:ref.id,field:ref.field,event_ref:ref.event_ref,quote:ref.quote,record_updated_at:ref.record_updated_at});const value=D.saveGoal({body:row.payload.body},{...old,coach_decision:status==='accepted'?String(args.coach_decision).trim():old.coach_decision,agent_proposal:{...old.agent_proposal,status}},{expected_revision:old.revision}),payload={...row.payload,status:'ready',body:JSON.stringify(value),updated_by:'agent',updated_by_label:'Head Coach'},rpc=await admin.rpc('head_coach_put_record',{p_team_id:c.team_id,p_kind:'document',p_payload:payload,p_record_id:row.id,p_expected_updated_at:row.updated_at,p_idempotency_key:'team-priority-decision:'+c.id+':'+row.id+':'+old.revision+':'+status,p_agent_subject:'head-coach'});if(rpc.error)throw rpc.error;return output(rpc.data);}
export async function executeTeamDevelopmentTool(admin,c,name,args){if(!c.scopes?.includes('read'))throw new Error('connector_scope_read_required');const write=name!=='get_team_development';if(write&&!c.scopes?.includes('write'))throw new Error('connector_scope_write_required');
 if(name==='prepare_cross_session_priority')return prepareCrossSessionPriority(admin,c,args);
 if(name==='accept_team_priority_proposal'||name==='dismiss_team_priority_proposal')return decidePriorityProposal(admin,c,name,args);
 if(name==='get_team_development'){if(args.id||args.external_key){const row=await find(admin,c,args);return row?output(row):null;}const{data,error}=await admin.from('workspace_records').select('*').eq('team_id',c.team_id).eq('kind','document').is('deleted_at',null).in('payload->>type',['weekly_plan','team_goal']);if(error)throw error;return(data||[]).map(output);}
 if(!['save_weekly_plan','save_team_development_goal'].includes(name))throw new Error('unknown_team_development_tool');if(args.confirmed!==true)throw new Error('explicit_confirmation_required');
 const weekly=name==='save_weekly_plan';if(weekly&&!args.week_start)throw new Error('week_start_required');const key=weekly?'team-week:'+D.monday(args.week_start):args.external_key;if(!args.id&&!key)throw new Error('external_key_required_for_goal');const selector=args.id?{id:args.id}:{external_key:key};const row=await find(admin,c,selector);if(row&&(!args.expected_updated_at||row.updated_at!==args.expected_updated_at))throw new Error('record_conflict_read_again');if(!row&&args.expected_updated_at)throw new Error('record_not_found_read_again');
 const old=row?weekly?D.week({body:row.payload.body}):D.teamGoal({body:row.payload.body}):null;if((old?.revision||0)!==args.expected_revision)throw new Error('domain_revision_conflict_read_again');let value,payload;
 if(weekly){const sessions=[args.training1&&{type:'training',id:args.training1},args.training2&&{type:'training',id:args.training2},args.match&&{type:'match',id:args.match}].filter(Boolean);await checkRefs(admin,c,sessions);value=D.saveWeek(row?{body:row.payload.body}:null,{week_start:args.week_start,objective:args.objective,training1:args.training1,training2:args.training2,match:args.match,links:[{from:args.training1,to:args.training2,note:args.relation_note},{from:args.training2,to:args.match,note:args.relation_note}],evaluation:{summary:args.evaluation||'',evidence:[]}}, {expected_revision:args.expected_revision});value.relation_note=String(args.relation_note||'').slice(0,500);payload={...(row?.payload||{}),team_id:c.team_id,type:'weekly_plan',title:'Semana · '+value.week_start,target_date:value.week_start,status:'ready',external_key:key,refs:sessions,body:JSON.stringify(value),created_by:row?.payload?.created_by||'agent',created_by_label:row?.payload?.created_by_label||'Head Coach',updated_by:'agent',updated_by_label:'Head Coach'};}
 else{await checkRefs(admin,c,args.sessions||[]);value=D.saveGoal(row?{body:row.payload.body}:null,{title:args.title,identified_at:args.identified_at,stage:args.stage,sessions:args.sessions||[],evidence:args.evidence||[],observations:args.observations,interpretation:args.interpretation,hypothesis:args.hypothesis,evaluation:args.evaluation,coach_decision:args.coach_decision},{expected_revision:args.expected_revision});payload={...(row?.payload||{}),team_id:c.team_id,type:'team_goal',title:value.title,target_date:value.identified_at,status:'ready',external_key:key||('team-goal:'+crypto.randomUUID()),refs:args.sessions||[],body:JSON.stringify(value),created_by:row?.payload?.created_by||'agent',created_by_label:row?.payload?.created_by_label||'Head Coach',updated_by:'agent',updated_by_label:'Head Coach'};}
 const{data,error}=await admin.rpc('head_coach_put_record',{p_team_id:c.team_id,p_kind:'document',p_payload:payload,p_record_id:row?.id||null,p_expected_updated_at:row?.updated_at||null,p_idempotency_key:'team-development:'+c.id+':'+(row?.id||payload.external_key)+':'+args.expected_revision+':'+value.revision,p_agent_subject:'head-coach'});if(error)throw error;return output(data);
}
